### ISSUE TITLE
[Firefox] Use of getAttributeNode() is deprecated. Use getAttribute() instead.

### ISSUE THREAD

**Issue by crobinson42** [google/recaptcha#102]
I get this console warning in Firefox v45.0

https://www.dropbox.com/s/okr9186yvmvs6ed/Screenshot%202016-03-27%2009.22.12.png?dl=0

**Comment by JohnTendik** [comment]
Having the same issue.  I feel like Firefox has become the new Internet Explorer where developers have to constantly do separate styles and scripts for browser support. Damnit Firefox...

I'd code the simple simple change myself and skip the horrid wait for the workaround, but unfortunately the script gets loaded from Google's server.. Damnit Google...

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
