### ISSUE TITLE
Recaptcha audio challenge language

### ISSUE THREAD

**Issue by PierreCavalet** [google/recaptcha#106]
I can't find any documentation on whether it is possible or not to get the audio challenge in a specific language. I've managed to get the widget in french but the audio challenge still is in english. Is there any way I can get a french audio challenge ?

**Comment by feerz** [comment]
Hello, Pierre. I'm facing the same issue with the i18n for spanish. All written labels of the widget display in spanish as expected, but the audio challenge is still in english. I've done extensive research on the matter, and could not find any conclusive answer, although i suspect the support does not cover the audio files.
Did you find any solution for this?

**Comment by PierreCavalet** [comment]
Hello feerz. Sadly I did not. We just gave up on the custom audio challenge since it was not that important for us, but if you find a solution, let me know!

**Comment by cristianokbc** [comment]
+1

We are not able to use recaptcha baceause it lacks the option to set the audio challenge language.

**Comment by leandroferes** [comment]
+1

Need to change the audio challenge language, otherwise I'm going to have to use another captcha solution or develop my own.  :(

**Comment by rcsilva83** [comment]
+1

recaptcha is great but it lacks multi language support to be "enterprise ready" in non English-speaking countries.

**Comment by ninrod** [comment]
Facing the same issue here. It is currently the only issue stoping us from using recaptcha.

**Comment by italofaguiar** [comment]
It would be great if we had the option of audio set in olther languages other than english.

**Comment by Ace766** [comment]
Setting audio language is a mandatory feature for me

**Comment by zachsigal** [comment]
Same issue here

**Comment by jdeyla** [comment]
Same issue here, and is a pity that this kind of tool,  after succeeding WCAG 2 1st and 2nd principles, fails the easiest 3rd for all non-english people: Understandable. 

Working together we could all send tons of audio numbers in foreign languages. 
It's just a matter in will

**Comment by franciscoabh** [comment]
Same issue here. Like @jdeyla  said, we´d like to know if we can help with this issue in some matter.

Ps: We need audio in Brazilian Portuguese.

**Comment by Renrhaf** [comment]
same issue, we need audio in french.

**Comment by jamilaPS** [comment]
Hello, I need to use the reCaptcha audio challange in Portuguese due accessibility rules. Is there a way to set the audio language for Portuguese or provide my own custom audio library?

**Comment by profDreco** [comment]
Hello. I need as well audio in portuguese, for accessibility rules.

**Comment by laghi** [comment]
Same issue here. As @profDreco said, we also have a lot of clients with complete visual impairment

**Comment by fefedao** [comment]
+1 same issue here

**Comment by Marizabel** [comment]
+1 same issue here, we need audio in portuguese.

**Comment by erichsilvestre** [comment]
+1

**Comment by rikatz** [comment]
+1 here for Brazilian Portuguese. Brazilian Law enforces government agencies to have accessibility options, including sound challenge. 

Not having a Portuguese Audio challenge is impeditive for us.

Thanks!

**Comment by emovere** [comment]
+1

**Comment by rafaelchagasb** [comment]
+1

**Comment by siz184** [comment]
+1 here for Russian

**Comment by warexschan** [comment]
+1 Russian!

**Comment by dtedesco** [comment]
+1 here for Brazilian Portuguese.

**Comment by rpierote** [comment]
+1 here for Brazilian Portuguese.

**Comment by felipegiotto** [comment]
+1 here for Brazilian Portuguese.

**Comment by y0chimitsu** [comment]
+1 here for Brazilian Portuguese.

**Comment by rowan-m** [comment]
I'm updating the `v1.2` branch to support the v3 API for reCAPTCHA which doesn't show challenges, just returns a confidence score for the user. This might help you. You can see a demo at: https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php

**Comment by yibup** [comment]
For Portuguese, hl=pt currently works for both images and audio, and hl=pt-BR only works for the images.

**Comment by MichaelOwaboye** [comment]
+1 same issue with audio on v1.2
