### ISSUE TITLE
IE8 retaining recaptcha (refresh and get an audio challenge) buttons even after completion of recaptcha validation

### ISSUE THREAD

**Issue by Rajarshi75198** [google/recaptcha#114]
In pure Internet Explorer 8 (not in compatibility mode), the browser is retaining the recaptcha refresh and get an audio challenge buttons in the page even after successfully completion of recaptcha. This is probably due to the fact that the iframe with title "recaptcha challenge" which contains the recaptcha images,  is being set as "visibility: hidden", and not getting removed from DOM, and this is somehow not working in IE8.

**Comment by stamster** [comment]
Is that for v2 or v1 recaptcha? IE8 is not supported anyway.

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
