### ISSUE TITLE
Keyboard only: focus is not reliably transferred to the image selection area

### ISSUE THREAD

**Issue by mattbrundage** [google/recaptcha#115]
In Internet Explorer 11 and Edge 13, using only the keyboard, upon checking the checkbox, the image selection area is loaded, but focus is not transferred to the image selection area.

In other browsers such as Firefox and Chrome, focus is correctly transferred to the first focusable element within the image selection area, namely the CAPTCHA reload button.

Reduced test case: https://www.google.com/recaptcha/api2/demo
In this demo, an IE 11 user must tab six times after checking the checkbox to reach the first focusable element within the image selection area. Similarly, an Edge 13 user must tab twice.

The reduced test case actually makes this problem seem less serious than it actually is -- on typical web pages with dozens of focusable elements, the user must tab through all remaining focusable elements on the page before the image selection area gains focus -- likely because the image selection area is appended to the body tag.

**Comment by mattbrundage** [comment]
Retesting your demo, it appears that this issue no longer affects IE 11. However, this issue still affects Edge (I'm on v. 14).

In Edge, the user must tab six times after checking the checkbox to reach the first focusable element within the image selection area.

The expected behavior, of course, is that focus is correctly transferred to the first focusable element within the image selection area,

@rowan-m, do you have any feedback on this?

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.

**Comment by mattbrundage** [comment]
[Edge is dead to me now.](https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/). Keep being awesome.
