### ISSUE TITLE
How to include recaptcha libs with direct download (no composer)

### ISSUE THREAD

**Issue by micheledallatorre** [google/recaptcha#117]
Docs is incorrect, there is no _autoload.php_ file as written in https://github.com/google/recaptcha#direct-download-no-composer 

I had to write the following instead.
```php
require_once('ReCaptcha\ReCaptcha.php');
require_once('ReCaptcha\RequestMethod.php');
require_once('ReCaptcha\RequestParameters.php');
require_once('ReCaptcha\Response.php');
require_once('ReCaptcha\RequestMethod\Post.php');
```

**Comment by rowan-m** [comment]
The docs specify `src/autoload.php` which is here: https://github.com/google/recaptcha/blob/master/src/autoload.php

Of course, it is just optional. You can require the files directly too.

**Comment by micheledallatorre** [comment]
Sorry, my fault, I misread it!
:+1:
