### ISSUE TITLE
Leaving the g-recaptch response out of form submission

### ISSUE THREAD

**Issue by tazcrzy** [google/recaptcha#118]
Help please. I need to remove from the email received after the user verifies they are not a bot, the recaptcha code in the email Here is a sample of the code I am using (BTW not a programmer), can you help? Thanks in advance.  

$email;$comment;$captcha;
if(isset($_POST[’email’])){
$email=$_POST[’email’];
}if(isset($_POST[‘comment’])){
$email=$_POST[‘comment’];
}if(isset($_POST[‘g-recaptcha-response’])){
$captcha=$_POST[‘g-recaptcha-response’];
}
if(!$captcha){
echo ‘Please check the the captcha form.’;
exit;
}
$secretKey = “6Lc…CB_HhsKvxeC”; (shorted for security)
$ip = $_SERVER[‘REMOTE_ADDR’];
$response=file_get_contents(“https://www.google.com/recaptcha/api/siteverify?secret=”.$secretKey.”&response=”.$captcha.”&remoteip=”.$ip);
$responseKeys = json_decode($response,true);
if(intval($responseKeys[“success”]) !== 1) {
echo ‘You are a robot’;
} else {
echo ‘Please wait a moment’;
}

Here is a sample of the response: 
When a web form is submitted I get the following characters, which I want to eliminate:
g-recaptcha-response: 03AHJ_Vuu8sZp6B_lzdL0ZPxJd9enuTmWEfz7Tt8rqzK1pQmDfwb8SrCV4AZ9f3gPAbcDo6flxsWhB4Trpbje9-ikbW87WW6d15a_6KhvUbvfQgWDsXlPtMKv02maz2UDvnIExaeMbWiuUNJQb_HvJrpLlcCclKGias5NPUgyptnyjkT3lHL0-2Te-G4dio6SiqavS4H-uF9oHlvuoty7PG7gdmKRjHAviAeZa2Yf6Xk1G4igdeJTsjqXnXtFydcFL5-X69otjuCMSxVBDR5thQJIrzducUjFMAVb948opbRktSeFmro4sSX3QzllZXI1azpOqZZoeiX0XAAvf-pKLIZa5t9TuO3D_ltJuLJBbtijXDsnCn94FPVmudZPUXv_k1LQeT_GDprYONJKqf69Dt9mhPwWh3Oz53mXiEbsrJCrVjNAzx-vz7px5nfbkRkrtVA2gSH4UvKAd52MuNY3mb4_GplkOjZ4WRoNZl2EDxofhkKHhFjn3Cb22sCi7qTqS20qfkbaU9orTtez9KvR1LROTl2XOPk3Nhqs_g2Jm_qmuMBtFhnIN8ZNdniJoyCR5HHOJYRJNLM2uvCUY5I3vMRQeWQCNGU-cEzWfoQ-WiFJqFRPkRDHh0YBJXJQlgQ9634bI4tiPJ1YzA6pkRPB-B24WIC2yw4xDcc2kHfg5nhqlqcvCNbgciRlQMi8rdIb0SxbkuWvR2NgGdC5VTXfXZSxrw88ZXV2FPbnTzBWVNSlFvkRt8mwXSerfaiVR901WRL-R1x608A-zzZJsyDVRoN29Mv9Ed7gOEH0CvONao4XkMBv3cTPFWH-5LK-DbirSaRSdlXMZ4da3whd_ruwIwEXZhzRlQDL0ISFdEcjZhpIyaJedJMDF_pH-uvbQuB1lF6xV4WbiI2j-bHWtqUoGm4BD9fF5iR0mSTJvQtEVVrkCb6w1D9xW2iXsG5iYq-

**Comment by LeonidasJP** [comment]
Before mailing the form, call `unset($_POST['g-recaptcha-response']);` after validating the ReCaptcha status (eg. just after the 'Please wait a moment'-echo)

Also, perhaps you should check the code before implementing it, the variable containing the submitted E-mail address will be overridden by the Comment posted in your second if-statement (to be exact, at `$email = $_POST['comment'];`)

**Comment by mira255** [comment]
Hi,
I have similar problem. Please help me .... 
I received this mesage every time at the end of every mail from my form (g-recaptcha-response : 03AEHxw......). I wish to hide (g-recaptcha-response : 03AEHxw......) I'm not a programmer ...
Thanks in advance!!!

this is my code:
$email_subject = "xxx";
$email_body = "xxx \n";
foreach($_POST as $key => $value)
{
    $email_body .= "$key : $value \n";
}
$headers = "From: $myemail\n"; 
mail(/*to*/$myemail,$email_subject,$email_body,$headers);
function post_captcha($user_response) {
        $fields_string = '';
        $fields = array(
            'secret' => 'xxxxxx',
            'response' => $user_response
        );
        foreach($fields as $key=>$value)
        $fields_string .= $key . '=' . $value . '&';
        $fields_string = rtrim($fields_string, '&');

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, 'https://www.google.com/recaptcha/api/siteverify');
        curl_setopt($ch, CURLOPT_POST, count($fields));
        curl_setopt($ch, CURLOPT_POSTFIELDS, $fields_string);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, True);

        $result = curl_exec($ch);
        curl_close($ch);

        return json_decode($result, true);
    }

    $res = post_captcha($_POST['g-recaptcha-response']);

    if (!$res['success']) {
       echo '<p>Please go back and make sure you check the security CAPTCHA box.</p><br>';
    } else {
       echo '<br><p>CAPTCHA was completed successfully!</p><br>';
    }
	
?>

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
