### ISSUE TITLE
Foutieve vertalingen van bepaalde vragen bij afbeeldingen (Winkelpui, Straatnamen, Straatnaamborden, enz)

### ISSUE THREAD

**Issue by primalkriek** [google/recaptcha#120]
Google maakt een foutieve vertaling bij het kiezen van afbeeldingen:
1. Selecteer alle afbeeldingen met een winkelpui => dit moet zijn: winkelpunt of etalage
2. Selecteer alle afbeeldingen met een straatnaam => dit moet zijn: Selecteer alle afbeeldingen met verkeersborden of straatnamen of straatnaamborden afhankelijk van de foto's die worden getoond.

Zie voorbeelden:
![voorbeelden](https://cloud.githubusercontent.com/assets/2353546/17801617/7271e106-65eb-11e6-8fb9-b3a24c0b80ea.png)

**Comment by raknjak** [comment]
Hey Kriek,
winkelpui is een bestaand woord - daar had ik de eerste keer ook zoeits van wtf is dit
Dus enkel de laatste is niet correct denk ik? Waarschijnlijk is Google hier aan't falen.
groeten

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
