### ISSUE TITLE
Chrome raises 'cross-origin security exception' and recaptcha fails when inside a TBS Modal

### ISSUE THREAD

**Issue by eozelius** [google/recaptcha#121]
Hello, I am experiencing a strange issue that is specific to Chrome Version 52.0.2743.82 m (64-bit) from a windows 7, MacOS, and linux mint machines.

I have a Twitter Bootstrap 3.3.7 modal with form, and a recaptcha inside the modal.

`<div id="entry" class="modal" role="dialog">`
`...`
`<%= recaptcha_tags>`
`</div>`

The reCaptcha works for all other browsers, but in Chrome the blue spinner just continues to turn indefinitely. The JS error in the console is as follows

Uncaught SecurityError: Blocked a frame with origin "https://www.google.com" from accessing a frame with origin "https://rndev.mcfinternal.com". Protocols, domains, and ports must match.

My application is a ruby on rails app with apache on a linux server.  (I can provide more info if necessary.)

The issue can be viewed/tested at https://rndev.mcfinternal.com/ (you will get a warning that we are using a self-signed cert.) Or at http://recognitionnotes.com/ (production site)

Thank you for your help.

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.

**Comment by HoshiYamazaki** [comment]
I have the same issue, so I think it's still relevant:
https://github.com/google/recaptcha/issues/288
