### ISSUE TITLE
Recaptcha Fallback Puzzle isDisplayed Hook or Property

### ISSUE THREAD

**Issue by ShayanZafar** [google/recaptcha#122]
Hello, 

I have recently upgraded from Recaptcha version 1 to 2. I know there is a case where a puzzle can be displayed under certain conditions. I want to know if there is a property returned by the API or some value i can hook onto to adjust for the size of the recaptcha when this fallback puzzle is displayed?

something like fallbackPuzzleDisplayed or some hook would be helpful. I am open to any alternative solutions.

 [Question - Stackoverflow](http://stackoverflow.com/questions/39395360/check-if-google-recaptcha-v2-puzzle-is-displayed)

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
