### ISSUE TITLE
reCaptcha challenge overlay blocks the page on iPad

### ISSUE THREAD

**Issue by tommykamkcm** [google/recaptcha#126]
Hello, i am writing to report an issue happened on iPads (based on my test results, it is an iPad-only, not iOS version related issue)

I've looked for a site which is using reCaptcha and having this issue.
To replicate this issue, please get your iPad ready, go to [https://www.quora.com/signup/email?code](https://www.quora.com/signup/email?code), and:

1. Tick the "I'm not a robot" checkbox for multiple times until you can see the image challenge overlay
2. Either finish the challenge or dismiss the overlay. (Pay attention on which part of the form is being covered / blocked, see attached)
3. Tap on the blocked area, you should not be able to edit the input fields
![screenshot_1](https://cloud.githubusercontent.com/assets/1722447/18902389/50b73110-8585-11e6-9fb3-434cb7015a57.png)

I've also did a screencap on safari web inspector and found that even though the overlay was hidden (visibility: hidden), its width and height were non-zero i.e. 402px x 602px (also tested it on iPhone and the size was 320px x 0px)
![screenshot_2](https://cloud.githubusercontent.com/assets/1722447/18902398/5f55aefe-8585-11e6-80a0-4d0bc00831fa.png)

To temporarily fix the issue on my site (sorry cannot disclose the link here), i've add the following code:
`// dependency: http://is.js.org/
function fixReCaptchaBlocking() {
  if (is.ipad()) {
    setInterval(function(){
      var newH = 0;
      var $reCaptchaIframe = $('iframe[title="recaptcha challenge"]');
      if ($reCaptchaIframe) {
        var $reCaptchaOverlay = $reCaptchaIframe.parent();
        var h = $reCaptchaOverlay.height();
        var visibility = $reCaptchaOverlay.css('visibility');
        if (visibility == 'hidden' && h > newH) {
          $reCaptchaOverlay.height(newH);
        }
      }
    }, 1000);
  }
}`

I really appreciate if one of the developers can take a look into this issue. Thank you very much!

**Comment by jasonfedor** [comment]
Hi - we've found the problem and this should be fixed within two weeks. Thank you for the report!
