### ISSUE TITLE
Unable to change alternative audio challenge language

### ISSUE THREAD

**Issue by cristianokbc** [google/recaptcha#128]
Sometimes reCAPTCHA shows an alternative audio challenge asking the user to select phrases which best match a category. Unfortunately it always shows the challenge in english. It should match the user's language or have an option to disable this kind of challenge.

![2016-10-14_11-33-38](https://cloud.githubusercontent.com/assets/8117027/19391468/2201b090-9203-11e6-8f0a-ed483670bb50.png)

**Comment by ninrod** [comment]
+1. somewhat related to google/recaptcha#106.

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
