### ISSUE TITLE
Problem with reCaptcha on Youtube and other Google sites

### ISSUE THREAD

**Issue by wellington1993** [google/recaptcha#129]
Hello,

See this: https://webcompat.com/issues/3355

I have a problem when use sites with reCaptcha included.
Why the script run many times when normal site usage?

And why my processor usage up when script generate alerts.
Sorry my ignorance and my poor English.

Contact me anytime.

![845f794d-d280-40e5-971f-bff1c99ffe62](https://cloud.githubusercontent.com/assets/6920053/19485708/a03f4190-953a-11e6-8121-9497bfe58a3f.jpg)
![ea2e5522-2266-402d-b256-bf5c67ce8c46](https://cloud.githubusercontent.com/assets/6920053/19485707/a03cc28a-953a-11e6-8282-eb0b2da5a42b.jpg)

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
