### ISSUE TITLE
Image Captcha action buttons not responsive in a modal in IE10/11

### ISSUE THREAD

**Issue by warrendodsworth** [google/recaptcha#132]
I've found that the image captcha popups action buttons at the bottom do not work while the recaptcha widget is inside a modal (magnific popup) in IE 10 and IE 11. Intermittently it works in IE 10 and sometimes in IE11 after several clicks on the Verify button.

Manually setting z-index to max on the action buttons seems to work well.

![image](https://cloud.githubusercontent.com/assets/1066996/20587961/83a848a4-b265-11e6-8856-7e1ea3515fa7.png)

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
