### ISSUE TITLE
Traps keyboard: Can not tab past the checkbox element

### ISSUE THREAD

**Issue by monkier** [google/recaptcha#135]
A user using the keyboard cannot tab away from the checkbox, whether it is checked or not. After checking the checkbox via the space button, the user is able to tab past the checkbox and hit the next focusable item, the "privacy" link. But as soon as the user tabs back to the checkbox, they are trapped again and unable to tab in either direction.

This fails [WCAG 2.1.2](https://www.w3.org/WAI/WCAG20/quickref/#qr-keyboard-operation-trapping) No Keyboard Trap.

Steps to reproduce:

1. Visit [https://www.google.com/recaptcha/api2/demo](https://www.google.com/recaptcha/api2/demo)
2. Press tab until you reach the checkbox
3. Attempt to tab past the checkbox and notice you cannot

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
