### ISSUE TITLE
Use X-Forwarded-For header in example

### ISSUE THREAD

**Issue by pelchats** [google/recaptcha#139]
For HTTP websites using reCAPTCHA, the captcha requests will be HTTPS. This means that users using an HTTP proxy will have a different remote IP than that seen by the captcha server (since HTTP request will go through the proxy, but not HTTPS requests). The website should probably look at the X-Forwarded-For header (if present) to get the remote IP.

The X-Forwarded-For header is easily spoofable, but it still seems like a better approach than breaking captchas for proxy users (which is a large fraction of Android traffic: https://developer.chrome.com/multidevice/data-compression).

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
