### ISSUE TITLE
Always returns false.

### ISSUE THREAD

**Issue by matteo1990** [google/recaptcha#140]
```
 if(isset($_POST['user_mail']) && isset($_POST['g-recaptcha-response']))
	{
		$captcha = $_POST['g-recaptcha-response'];
	$secretKey = "[my secret key]";
		$ip = $_SERVER['REMOTE_ADDR'];
			$response = file_get_contents("https://www.google.com/recaptcha/api/siteverify?secret=".$secretKey."&response=".$captcha."&remoteip=".$ip);
 			$responseKeys = json_decode($response,true);
 			var_dump($http_response_header);
 			if(intval($responseKeys["success"]) === 1)
 			{
 				send_mail();
 			}
 			else
 			{
 				echo '<script>window.alert("Insert captcha.");</script>';
 			}
 		}
```

This is not working, yet the same code correctly works in another website. 
I've checked out the keys, and they are right. Google code snippets before the end of </head> tag and into form are also correct. 

I've also try to debug with

` var_dump($http_response_header);`
but it returns _NULL_.

Any ideas on how to fix this? :/
Thank you !

**Comment by powellkarind** [comment]
I'm working with the same issue. We are looking into the **firewall** being a problem because the exact same coded I'm using works from two other web servers. ... We're in troubleshooting mode. Stay tuned. 

BUT just as a "thing you can try" (you probably already did this....) -- have you tried moving your last parameter in the string to the beginning? I know it sounds silly, but you never know in this weird world...
STRING TO TRY: `?remoteip=.$ip&secret=".$secretKey."&response=".$captcha`

I'll let you know about the firewall and if it was an issue or not.

**Comment by vgolubeva** [comment]
I had the same problem on localhost. In my case problem was in SSL sertificate (I undestood it when I tried to use `curl_exec` for sending data and got a look at `var_dump(curl_error($ch))`). After downloading `cacert.pem `and configuring `php.ini ` the issue was resolved!

**Comment by senseimknight** [comment]
I've run into the same issue. The strangest part is a client-side call to grecaptcha.getResponse() returns to correct response. For some reason it's just not setting g-recaptcha-response.
So my workaround was to set a data-callback function to populate a hidden field with the response and use that server-side instead. The hidden input also helps with ease of client-side validation.
eg:

```
<div class="g-recaptcha" data-callback="captcha_onclick" data-sitekey="######"></div>
<input type="hidden" name="recaptcha" id="recaptchaValidator" />
```
javascript:
```
function captcha_onclick() {
	document.getElementById('recaptchaValidator').value = grecaptcha.getResponse();
}
```
server-side:
```
if(isset($_POST['user_mail']) && isset($_POST['recaptcha'])) {
	$captcha = $_POST['recaptcha'];
	...
}
```

**Comment by rowan-m** [comment]
Are you still running into this issue?

**Comment by senseimknight** [comment]
@rowan-m Yes, I ran into this issue again last week with a new implementation.

**Comment by rowan-m** [comment]
I'd suggest trying some of the alternate request methods:
```php
// uses http://php.net/fsockopen
$recaptcha = new \ReCaptcha\ReCaptcha($secret, new \ReCaptcha\RequestMethod\SocketPost());
// uses http://php.net/curl_exec
$recaptcha = new \ReCaptcha\ReCaptcha($secret, new \ReCaptcha\RequestMethod\CurlPost());
```

Also take a look at what I'm doing in the examples: https://github.com/google/recaptcha/tree/master/examples

**Comment by dmpe** [comment]
@rowan-m Hi Rowan, 
Currently, I am using v3 (in combination with invisible reCAPTCHA) and have faced exactly same problem as others here. 

Though, I am pretty sure that when I first implemented this in my application, it has worked correctly - initially at least (i.e. token was binded e.g. to some button and then for instance in Django one could fetch it via `request.POST.get('g-recaptcha-response', False)` (either a token or python's `False`))

Unfortunately, somehow it has stopped working (i.e. started to return always false) and @senseimknight advice/solution has been perfect for me. 
As (s)he has described, one has to <b>explicitly bind the token to some input/div/button tag</b>.

onSubmit function:
```	
function onSubmit(token) {
		document.getElementById("form-login").submit();
}
```

another JS code somewhere on the same page:
```
	grecaptcha.ready(function() {
		grecaptcha.execute('key', {action: 'login'}).then(function(token) {
			console.log(token);
			$("#recaptchaValidator").val(token);  // important - done via Jquery
		});
	});
```

Consequently, you can have HTML button like this:

```
<button class="g-recaptcha" 
id="recaptchaValidator"  // for binding the value
data-sitekey="key" 
name="g-recaptcha-response"  // used for later fetching the value of token in Django
type="submit" 
data-callback="onSubmit">Login</button>
```


Now, my wish: Can you improve a bit the v3 documentation and add some more information other than saying just `Send the token to your backend with the request to verify`. Maybe, explicitly saying that binding of the token to some tag (e.g. through Jquery) is necessary. 

In fact, in verify page, one can also read that token can be fetched via `g-recaptcha-response POST parameter when the user submits the form on your site`. And that has confused me a bit as I though you can fetch it immediately with that POST parameter when the form has been submitted. 

Thank you.
