### ISSUE TITLE
how to validate google recaptcha in spring boot?

### ISSUE THREAD

**Issue by jachuchl** [google/recaptcha#141]
public class GoogleReCaptchaChecker {

        @Value("${google.recaptcha.url}")
        private String url;

        @Value("${google.recaptcha.secret-key}")
        private String secretKey;

        @Value("${google.recaptcha.site-key}")
        private String siteKey;

        @Autowired
        RestTemplate restTemplate;

        public Boolean validateGoogleReCaptcha(String reCaptchaResponseStr, String remoteAddr) {
            try {
                ReCaptchaImpl reCaptcha = new ReCaptchaImpl();
                reCaptcha.setPrivateKey(secretKey);
                ReCaptchaResponse reCaptchaResponse = reCaptcha.checkAnswer(remoteAddr, siteKey, reCaptchaResponseStr);
                return reCaptchaResponse.isValid();
            } catch (Exception e) {
                e.printStackTrace();
                return false;
            }

        }

    }

**Comment by jachuchl** [comment]
checkAnswer(String remoteAddr, String challenge, String response)

what is the second parameter challenge?

**Comment by jachuchl** [comment]
This is my code but always return false, but I don't know what are the arguments need to be passed.is there any dependency to do ReCaptcha validation. I'm using this net.tanesha.recaptcha4j(version-0.0.7) dependency

**Comment by Duttabhi** [comment]
can any please tell checkAnswer(); why it is not working


this my process.jsp
<%@ page import="net.tanesha.recaptcha.ReCaptchaImpl"%>
<%@ page import="net.tanesha.recaptcha.ReCaptchaResponse"%>
<html>
<body>
    <%
        String remoteAddr = request.getRemoteAddr();
        ReCaptchaImpl reCaptcha = new ReCaptchaImpl();
        reCaptcha.setPrivateKey("6Lc611sUAAAAAOTs00Z5GRyov7BA5WDufKy0qbCN");
        String challenge = request.getParameter("recaptcha_challenge_field");
        String uresponse = request.getParameter("recaptcha_response_field");
        
        
        System.out.println("XXXXXXXXXXXXXXXXXXXXX");
        
        
        ReCaptchaResponse reCaptchaResponse = reCaptcha.checkAnswer(remoteAddr, challenge, uresponse);
        if (reCaptchaResponse.isValid())
        {
            out.print("Answer was entered correctly!");
        } else
        {
            out.print("Answer is wrong");
        }
    %>
</body>
</html>

**Comment by rowan-m** [comment]
This repo is for the PHP client library. You may have better luck asking on StackOverflow or looking through this article: http://www.baeldung.com/spring-security-registration-captcha
