### ISSUE TITLE
How to integrate reCAPTCHA into an iOS mobile Application 

### ISSUE THREAD

**Issue by rishisattoor** [google/recaptcha#142]

**Comment by evenluo** [comment]
So, is there any guide for iOS app?

**Comment by mrazam110** [comment]
Any guide?

**Comment by jotae85** [comment]
nothing yet? 😢

**Comment by rowan-m** [comment]
There's nothing official for iOS. You could take a look at https://github.com/fjcaetano/ReCaptcha which appears to wrap a webview, but I have not tried it.

**Comment by brunomunizaf** [comment]
It's mid 2019 and still nothing?

**Comment by Juanpaie** [comment]
When is reCAPTCHA going mobile?

**Comment by ELezov** [comment]
We need guide for integrate reCAPTCHA V3 for iOS. Revolution is comming.

**Comment by Frank-Dell** [comment]
PayPal redirects users to a webpage containing reCAPTCHA "I'm not a robot" checkbox.

**Comment by leanmarg** [comment]
There are other alternatives to CAPTCHA / reCAPTCHA for verifying "Humanity. Have you looked at the use of biometrics for this use case?

**Comment by Frank-Dell** [comment]
> There are other alternatives to CAPTCHA / reCAPTCHA for verifying "Humanity". Have you looked at the use of biometrics for this use case?

Thank you! But what about users havn't enrolled Face ID / Touch ID or devices not support biometric authentication at all?

**Comment by leanmarg** [comment]
> > There are other alternatives to CAPTCHA / reCAPTCHA for verifying "Humanity". Have you looked at the use of biometrics for this use case?
> 
> Thank you! But what about users havn't enrolled Face ID / Touch ID or devices not support biometric authentication at all?

@Frank-Dell, there are other biometric authentication options beyond the traditional touch or face options. Most smartphones have sensors such as accelerometer and gyroscope and those can help create a profile to uniquely identify a person. There are companies that provide mobile SDKs to do this. I am involved with one called Unify ID that has [APIs ](https://developer.unify.id/) for Human Detection and authentication. You can check out their stack and let me know what you think

**Comment by 3duard0** [comment]
Recaptcha enterprise has support for iOS, any particular reason for common recaptcha not having support?

**Comment by thomas126** [comment]
Would really be interested in this? Amy reason why recaptcha is not available in iOS app or web interface?

**Comment by k-sai-kiranmayee** [comment]
Hello all! Just a quick question! So reCaptcha is not for any native apps?

> When is reCAPTCHA going mobile?

Still in progress @rowan-m?

**Comment by samuelhepditch** [comment]
https://gist.github.com/jkereako/d111ff6f4594873d409d3194371d6732 this is a great resource which helped me to implement v2. Using a hidden webview you can get it to work in your application.

**Comment by lawgimenez** [comment]
Is it available on iOS now? In the year of our lord 2022?
