### ISSUE TITLE
file_get_contents(): SSL operation failed with code

### ISSUE THREAD

**Issue by chelkaz** [google/recaptcha#147]
PHP 7+ DOMAIN without https, only 80 port
- google/recaptcha/src/ReCaptcha/RequestMethod/Post.php', 68
- I add 

`'ssl' => array(
                'verify_peer' => false,
            ),`
**Getting started is good**

**Comment by Azuka** [comment]
See [#167](https://github.com/google/recaptcha/issues/167#issuecomment-321197062)

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
