### ISSUE TITLE
User problems with Firefox on Linux

### ISSUE THREAD

**Issue by wellington1993** [google/recaptcha#148]
I have problems with core script on daily use.
Sorry my ignorance.

Attached image with the problem. 
http://i.imgur.com/SMtQ3OC.png

![smtq3oc png](https://cloud.githubusercontent.com/assets/6920053/24077264/9c7b00cc-0c26-11e7-8ba7-bb721c4902c5.jpeg)

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
