### ISSUE TITLE
Add PHP 5.4 / PHP 5.3 support back

### ISSUE THREAD

**Issue by alexhass** [google/recaptcha#149]
I still need to support Drupal 7 and this has a minimum requirement of 5.3. I have not seen a single change between reCAPTCHA lib 1.1.2 and 1.1.3 that requires to discontinue support of older PHP versions.

**Comment by yamlfd** [comment]
BUMP

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.

**Comment by Prizem** [comment]
This is still relevant. Drupal 7 is still supported and still supports PHP 5.3. Now the issue is that the recaptcha Drupal module maintainer has updated the module to reflect this PHP 5.5 requirement when it's apparently unnecessary.

**Comment by rowan-m** [comment]
You can still use v1.1.2 
PHP 5.4 was EOL over 3 years ago, I won't be adding support for that back into new versions.

**Comment by alexhass** [comment]
As you waited now ~3 years to comment on this issue - it became a bit more obsolete. But you should never remove php support that early next time. 

I still get complains where redhat users complain that their old php 5.3/5.4 is still supported by redhat.
