### ISSUE TITLE
js of recaptcha produce warning code DOM7011 in IE11. Fix it!

### ISSUE THREAD

**Issue by AngelTs** [google/recaptcha#151]
"<script type="text/javascript" src="https://www.google.com/recaptcha/api.js"></script>"
generate in IE11 the warning
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337

**Comment by Hoween** [comment]
I think that Google is better target for your request. This project doesn't have anything to do with Google recaptcha provider ;-)

**Comment by JasonThomasData** [comment]
"Fix it!" lol

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
