### ISSUE TITLE
ReCaptcha V2 puzzle images are not loading on IE when domain name is an IDN

### ISSUE THREAD

**Issue by thisarattr** [google/recaptcha#152]
We are using reCaptcha on a IDN name web site (eg: http://somename.xn--ngbc5azd). This page is working fine in all the browsers, expect IE.
On IE it loads the reCaptcha box, but when we click on reCaptcha box it does not load the puzzle images. Error on console is as below,
`access denied recaptcha__en.js, Line: 342`

However, this same code works fine for regular domain names, in all the browsers including IE.

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.

**Comment by antmorozov** [comment]
Hey @rowan-m 
Should I make a new issue or you can re-open this one?

**Comment by antmorozov** [comment]
I think it might be related to this bug in IE/Edge (they send incorrect values for Origin and Referer headers on IDN):

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8075637/

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
