### ISSUE TITLE
Acessablity issue on Recptcha on IOS when you are on a web page using 

### ISSUE THREAD

**Issue by di348f** [google/recaptcha#153]
When you are on a webpage that has Recptcha with accessibility on and screen reader - The Recptcha  sequence is incorrect - You are getting an empty page on the Recptcha  frame. 

Steps to recreate: 
1. Enable accessibility on I phone using the following steps:
  a. Go to settings 
  b. Go to General
  c. Go to accessibility
  d. Go to Voice Over 
  e. set "VoiceOver" to On 
This will enable "talk Back" n your iphone. 
2. Open Safari and go the following url: https://www.cricketwireless.com/myaccount.html#/register
3. Use the screen to scroll right to move from one field to another 
4. After you get to the link "Please confirm that you're human"  Scroll to right again to the Recptcha process. 
5. This is where you see the issue - an empty page is getting opened. Attached are screen captures of the issue. You can see teh empty page on 2.PNG file 
6. if you scroll to the right again - You are on the Recptcha   screen. 

![1](https://cloud.githubusercontent.com/assets/21080562/25242793/e96d7f0c-25c8-11e7-8cfa-6184bf6ade8d.png)
![2](https://cloud.githubusercontent.com/assets/21080562/25242794/e96e6584-25c8-11e7-8d98-921217ce25dc.png)
![3](https://cloud.githubusercontent.com/assets/21080562/25242795/e96f6fb0-25c8-11e7-88a7-eb996b012eea.png)

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
