### ISSUE TITLE
Recaptcha analytics empty excel report

### ISSUE THREAD

**Issue by jckhan** [google/recaptcha#157]
We are getting success/fail  responses from the server side validation , but when we look a the analytics there are no request for such domain registered in the excel.

One theory is that we registered the same domain with two different google accounts , but we are using the keys of the second one we registered , we don´t know if this could be a factor for registering the requests in the analytics .

**Comment by az0** [comment]
I have the same issue, and according to this link there is a minimum traffic level

https://stackoverflow.com/questions/43686745/google-recaptcha-v2-analytics

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
