### ISSUE TITLE
Can't set a value for tabindex

### ISSUE THREAD

**Issue by troywarr** [google/recaptcha#160]
Per the [developer docs](https://developers.google.com/recaptcha/docs/display), there should be three ways to set the value of the reCAPTCHA widget's `tabindex` attribute:

1. include a `data-tabindex` attribute on the widget's HTML element and load the widget automatically ([example](https://codepen.io/troywarr/pen/rmqWyX?editors=1000))
1. include a `data-tabindex` attribute on the widget's HTML element and load the widget explicitly ([example](https://codepen.io/troywarr/pen/MmPbvd?editors=1000))
1. load the widget explicitly and pass a `tabindex` parameter to the `grecaptcha.render()` method ([example](https://codepen.io/troywarr/pen/dWgOKW?editors=1000))

I have not been able to successfully change the value of `tabindex` from the default of `0` to any other value using the approaches above. My expectation is that the `#recaptcha-anchor` element inside of the widget's iframe should contain the value that I've set when the widget loads.

The end result of the issue is that the tabbing order of the reCAPTCHA widget can't be changed. In any of the examples above, try:

1. clicking inside the first text input (just above the reCAPTCHA widget) to focus it
1. pressing `tab` to advance to the next element on the screen

Notice that the next element to receive focus is the text input just below the reCAPTCHA widget, which has `tabindex="3"`. Only after tabbing from this text input does the checkbox in the reCAPTCHA widget gain focus. My expectation is that the tab order would proceed from top to bottom through the three elements on the page.

**Comment by adaptabi** [comment]
A good [repo](https://codepen.io/troywarr/pen/MmPbvd?editors=1000) that shows this.
The bug is missing the `tabindex` attribute on the `iframe` itself, hence the `iframe` is considered the lowest `tabIndex` in the curent document

**Comment by gnarmedia** [comment]
This is still an issue.  I'm running into this bug and I can't make the forms behave properly for our site, this is a major problem for us.

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.

**Comment by glen-84** [comment]
@rowan-m Please re-open, this is still an issue AFAIK.

**Comment by adaptabi** [comment]
This is still a bug and never got fixed

**Comment by williamlivingstone** [comment]
I was running into some captcha tabindex issues and found that by removing all tabindex references on the form, that solved my problem!

**Comment by scottbommarito** [comment]
@rowan-m - We are still seeing this issue. We run an ASP.NET app with an `invisible` ReCaptcha widget. We would like to set the `tabindex` to `-1` so that the widget does not get tabbed to while tabbing through the form. [Unfortunately, despite setting `data-tabindex` to `-1`](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/App_Code/ViewHelpers.cshtml#L655), the widget is unaffected.

**Comment by Swimburger** [comment]
We have a similar setup as @scottbommarito, except we hide the widget and use the snippet provided on [ReCaptcha FAQ](https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-v3-badge-what-is-allowed) to still be compliant to the ReCaptcha terms.
The snippet works great and tabbing works as expected, but the hidden widget still receives tabindex which is confusion as it is invisible.

**Comment by AlexeyKosov** [comment]
Why is it closed? Please consider reopening and looking into this.

**Comment by Kataklizmic** [comment]
This is an issue for me as well. For now, I did what @williamlivingstone said and removed all of the tabindexes, which resulted in the tabbing functioning as desired. 

It is frustrating that I spent so much time trying to get it to work by following Google's documentation  without knowing there was a bug with it!

**Comment by bwgraves** [comment]
Can confirm this is still an issue :(

**Comment by mertthesamael** [comment]
Hello from 2024, it's still an issue
