### ISSUE TITLE
Recaptcha iframe and sandbox attribute

### ISSUE THREAD

**Issue by DigTK** [google/recaptcha#162]
We recently ran a security scan on our website and one of the things it pointed out was 
> An external insecure or misconfigured iframe was identified.

This happened on a page that has no iframes, but includes a recaptcha.

Their suggested solution is to add the `sandbox` attribute to the insecure iframe, but I don't see a way on how I would do that for the recaptcha since all you put on the page is a `div` with your sitekey. Additionally I have my doubts that the recaptcha would work in a sandboxed iframe.

How would I resolve this issue?

**Comment by jasonfedor** [comment]
We should have sandbox settings on our iframes within a few weeks, thanks for the report.

**Comment by DigTK** [comment]
Are there any updates regarding this issue?
