### ISSUE TITLE
Captcha challenge renders with broken layout and blank squares

### ISSUE THREAD

**Issue by PeterA** [google/recaptcha#164]
On some mobile devices the captcha challenge sometimes renders with a broken layout and includes blank squares when the captcha challenge has four columns of squares.

The behavior was encountered on an Android mobile device while using the Chrome browser. The same behavior was not exhibited on the same device using the built in browser.

The broken layout tends to happen on challenges that present four columns of squares to tap on. However, some four column challenges rendered without a problem. 

**Device tested on:**
Device: Huwai Y336-U02
OS: Android 4.4.2
Browser: Chrome v51.0.2704.81

**Steps to reproduce:**
- Visit Google's [Recaptcha Demo Page](https://www.google.com/recaptcha/api2/demo)
- Tap the "I am not a robot" check box
- Click the refresh icon or 'skip' button until a captcha comes up that has a broken display

**Screenshot 1 of four column broken captcha:**
![screenshot_2017-06-08-12-26-12](https://user-images.githubusercontent.com/145472/26916452-28a5e4e6-4c4a-11e7-81a5-32fcf693328a.png)

**Screenshot 2 of four column broken captcha:**
![screenshot_2017-06-08-12-24-43](https://user-images.githubusercontent.com/145472/26916689-025cb64c-4c4b-11e7-9db9-3d1f2354dad7.png)

**Screenshot of four column captcha that render without defect on the same device:**
![screenshot_2017-06-08-12-25-31](https://user-images.githubusercontent.com/145472/26916477-44463cb4-4c4a-11e7-9e02-a78503cb90db.png)

**Screenshot of Google's demo captcha form being used for the test:**
![screenshot_2017-06-08-12-24-06](https://user-images.githubusercontent.com/145472/26916540-7b7882f0-4c4a-11e7-8d2f-d30858462ecd.png)

**Comment by venky352** [comment]
I am also seeing this issue. Looking forward for the solution.

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
