### ISSUE TITLE
Add Root CAs pinning for www.google.com request

### ISSUE THREAD

**Issue by emanuelb** [google/recaptcha#165]
It's known that Google implement Root CAs pinning for some of it's websites in chrome browser, see:
https://www.imperialviolet.org/2011/05/04/pinning.html
The same mechanism can be implemented in the library (allow only used Root CAs), as it only send requests to host:
www.google.com

fix:
limit the Root CAs that can sign the certificate for request to: www.google.com (as done in chrome, which help detect attacks such as: https://security.googleblog.com/2011/08/update-on-attempted-man-in-middle.html)

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
