### ISSUE TITLE
recaptcha_en.js issue

### ISSUE THREAD

**Issue by roger-link** [google/recaptcha#166]
We are running into issues with https://www.google.com/recaptcha/api.js. Specifically with recaptcha_en.js.  It seems there is an issue with these lines or maybe we're using the api incorrectly. Sorry in advance if this is a problem on our end.

It seems there might have been an update last week:
https://www.gstatic.com/recaptcha/api2/r20170613131236/recaptcha__en.js

Chrome and Firefox are broken. 
Safari < 10 works.

Possibly broken code:
  k.addEventListener("test", null, b);
  k.removeEventListener("test", null, b);

The piece of code erroring out:

 var Yd = !B || 9 <= Number(bc)
      , Zd = !B || 9 <= Number(bc)
      , $d = B && !E("9");
    !D || E("528");
    Nb && E("1.9b") || B && E("8") || Lb && E("9.5") || D && E("528");
    Nb && !E("8") || B && E("9");
    var ae = function() {
        if (!k.addEventListener || !Object.defineProperty)
            return !1;
        var a = !1
          , b = Object.defineProperty({}, "passive", {
            get: function() {
                a = !0
            }
        });
        **k.addEventListener("test", null, b);
        k.removeEventListener("test", null, b);**
        return a
    }();

**Comment by mvcdev** [comment]
We're also now getting this error

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
