### ISSUE TITLE
How to force CURL over file_get_contents?

### ISSUE THREAD

**Issue by IsaacHub** [google/recaptcha#167]
By default the `file_get_contents()` is used as the request method from the file `RequestMethod/Post.php`. 
In the php config of the server, `allow_url_fopen` is set to `0`(off), so I couldn't use this recaptcha service, `No wrapper found` error is thrown. CURL is the only way I should go for.

 _changing the `allow_url_fopen` flag is NOT allowed. can't do it from htaccess or ini_set, it won't work._

I need to use CURL request method from the file `RequestMethod/CurlPost.php` and override the default `file_get_contents()`. **How to do that?** Why users are not given the choice of available request methods?

```
require_once __DIR__ . '/recaptcha/autoload.php';
$recaptcha = new \ReCaptcha\ReCaptcha('_SECRET_KEY_');
```
and upon submitting the form, I did:
```
$resp = $recaptcha->verify($_POST['g-recaptcha-response'], $_SERVER['REMOTE_ADDR']);
if ($resp->isSuccess()) {
//my code
}
```

**Comment by sktan** [comment]
You will need to initialise the ReCaptcha object with the CurlPost class.

    $recaptcha = new \ReCaptcha\ReCaptcha('_SECRET_KEY_', new RequestMethod\CurlPost());

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.

**Comment by msrumon** [comment]
Thanks @rowan-m. I was looking for this solution.
