### ISSUE TITLE
Recaptcha new sandbox attributes causes exception in older browsers

### ISSUE THREAD

**Issue by lishid** [google/recaptcha#168]
In https://github.com/google/recaptcha/issues/162, new sandbox attributes have been added. Since then, older browsers which did not support the new attributes would fail to load recaptcha.

In my testing, this is happening to a Cordova app using UIWebView on iOS. My user agent is `Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27`

```
Error while parsing the 'sandbox' attribute: 'allow-modals', 'allow-popups-to-escape-sandbox' are invalid sandbox flags.
rb — recaptcha__en.js:518
kd — recaptcha__en.js:1139
od — recaptcha__en.js:1195:82
pd — recaptcha__en.js:1175
Wo — recaptcha__en.js:10609
Xo — recaptcha__en.js:10619
render — recaptcha__en.js:10850
aq — recaptcha__en.js:11061
dq — recaptcha__en.js:11145
eq — recaptcha__en.js:11164
```

According to [this SO question and answer](https://stackoverflow.com/a/40067953), the only way to ensure backwards compatibility is to add the new sandbox attributes retroactively.

**Comment by lishid** [comment]
@jasonfedor I believe you are the right person to ping.

**Comment by fox94610** [comment]
Getting this error in Safari 10.1.1  on submit...

![image](https://user-images.githubusercontent.com/243347/28432998-042f56b8-6d3f-11e7-82ed-e04d3d45faa1.png)

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
