### ISSUE TITLE
reCaptcha screen freezes upon clicking 'Skip' and 'Get a new challenge' buttons

### ISSUE THREAD

**Issue by tejrish** [google/recaptcha#170]
**Issue:**  Clicking of 'Skip' and 'Get a new challenge' buttons over and over causes the reCaptcha screen to freeze.  

**Frequency:** We have seen this issue multiple times on Google's reCaptcha Demo page (https://www.google.com/recaptcha/api2/demo) and also on our application that uses reCaptcha.

**Steps to reproduce:**
1. Click on ‘I’m not a Robot’ checkbox on the page.
2. On the reCaptcha page, if you see 'Verify' button, click on the 'Get a new challenge' button until you see the 'Skip' button.
3. Click on 'Skip' button.
4. Repeat steps 2 and 3 over and again for a few times and notice that the reCaptcha screen freezes.  When this happens, clicking on ‘I’m not a Robot’ checkbox on the home page loads the same frozen image.  User is unable to proceed at this point.

At this point, the only option is to reload the page again, which means all the data entered on the page is lost.  The user will have to re-enter the data in all fields again.

**Expected result:**
The screen should not freeze upon clicking the Skip and 'Get a new challenge' button repeatedly. 

**Attachments:**
1. Error seen on Google's reCaptcha Demo page.
[](url)
![recaptcha_error_on_frequently_clicking_refresh_ _skip_on_google_demo_page](https://user-images.githubusercontent.com/30242905/28284171-f0c50f70-6ae4-11e7-9f86-fb21008f1d3c.PNG)

2. Errors seen on our application page.
![2_recaptcha_error_on_frequently_clicking_refresh_ _skip](https://user-images.githubusercontent.com/30242905/28284502-04a83598-6ae6-11e7-8198-7df1a63de3ed.PNG)
![1_recaptcha_error_on_frequently_clicking_refresh_ _skip](https://user-images.githubusercontent.com/30242905/28284501-04a69530-6ae6-11e7-9e39-1ddbb64a981a.PNG)

**Comment by ryanmurakami** [comment]
We've also noticed this on multiple devices while testing an application using recaptcha. For more information, we are using invisible recaptcha in our case.

**Comment by tearhear18** [comment]
i encounter same when new popup challenge appear it looks like it prevent javascript execution

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
