### ISSUE TITLE
Recaptcha project is dead?

### ISSUE THREAD

**Issue by guylando** [google/recaptcha#171]
1)This github repository code has not been updated for 5 month.
2)This github repository has numerous open issues, much more than closed issues.
3)More importanly: the official recaptcha discussion board is filled with unanswered complaints: https://groups.google.com/forum/#!forum/recaptcha
4)The recaptcha has numerous bugs, returns 404\410 errors a lot, shows wrong text for pictures, and more.

I am coming to the conclusion that google abandoned support for the recaptcha? It is weird because this product has so many users.

Our startup considered using the invisible recaptcha but now from the reasons above we are searching for an alternative unless google will release an update in the next days.

It would be nice to hear from google official that the project is abandoned so that we can start to look for an alternative starting from today.

**Comment by cordoval** [comment]
@guylando did you find an alternative?

**Comment by guylando** [comment]
@cordoval we currently disabled the recaptcha in our product and have set this task to the future

**Comment by guylando** [comment]
@jasonfedor I saw you answer a question regarding a bug, why are you not answering this issue question and nobody else is answering? Don't you care if people think this project is unmaintained?

**Comment by AaronMalenfant** [comment]
The reCAPTCHA product is still supported and in active development.This github repository is only for the php library for reCAPTCHA and not for the product itself, so opening issues here will not necessarily be visible to the development team. If you need to report a bug please use support@recaptcha.net.

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
