### ISSUE TITLE
ReCaptcha issues

### ISSUE THREAD

**Issue by Alkaris** [google/recaptcha#173]
Everytime when it's click on all the images of cars, and I select all that I could, but there are no more to select, and I hit verify, it will always return an error saying `Sorry, Please try again` every time, when I got clear visuals that there are no more images of cars that are visible to be selected.

Same deal is with needing to click every image that has street signs. These ones completely do not make any sense at all. I select all the visible square that HAVE signs on them, and some images will be positioned in a way where the sign and squares you need to click on are in other square spaces too, even by that little bit  into the square next to it. Other times I'm shown images of signs that are blurred out, it doesn't always make itself clear on what you need to actually click. blurred street signs to me I think you DON'T need to click on.

Street Signs that are stood on poles, don't even count as a sign, since you just need to click on the board of the sign you see. The solver algo for knowing what's a sign and what isn't is broken, because it doesn't know what's on the image, and what squares need to be clicked on.

**Comment by fugueink** [comment]
Street signs are driving me crazy!

I do fine with cars, buses, roads, bridges, but street signs baffle me!  I can't tell what does or does not count as a street sign, and I am familiar with several languages sufficiently to tell commercial signs from traffic-related signs. But I can't find any rhyme or reason to what the system considers a "street sign". Do signs labeling streets count? Exit signs on highways? Pedestrian crossings?

I just can't crack it, so the system decides I'm "sending random signals" and blocks me out. It should be automatic that after a while the system tries some other object, but it won't. Only those blasted street signs!

**Comment by Alkaris** [comment]
@fugueink They're pretty annoying too, see you don't know whether if you have to click on the squares that only just have the street signs on them or if it means to the entire thing, pole that it's sitting on, or that tiny edge of a sign that bleeds into the next square.

**Comment by rowan-m** [comment]
This isn't directly related to the PHP code which is what this repo focuses on. However, you might want to look at the v3 support in the most recent release. That uses a wholly invisible reCAPTCHA that just returns a confidence score for the request. This might alleviate some of your issues. Example hosted at https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php
