### ISSUE TITLE
Recaptcha not rendered for Headless Chrome

### ISSUE THREAD

**Issue by vinaynp123** [google/recaptcha#174]
Running webpage with recaptcha with testing keys in headless chrome(chromedriver_2.31.exe) wont render the recaptcha, instead shows like below,
![k0ecu](https://user-images.githubusercontent.com/10628426/28908353-e1a8589e-7840-11e7-9174-749d079dacc1.png)

**Comment by ConsultJL** [comment]
@vinaynp123 Did you ever find a solution for this? I'm running into it myself.

**Comment by SuperCorks** [comment]
Same here

**Comment by vinaynp123** [comment]
@ConsultJL @SuperCorks I created a QA environment which ignores recaptcha and hence solved my issue.

**Comment by bjharo** [comment]
I'm seeing this as well.  Unfortunately, disabling recaptcha isn't an option as I have tests specifically around it.

**Comment by zavodnyuk** [comment]
try to set custom User-Agent with compatible one (e.g. from your real browser). 
`   capabilities: {
     'browserName': 'chrome',
     chromeOptions: {args: [ "user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36", "--headless", "--disable-gpu" ]
     }` worked for selenium/protractor on js

**Comment by bjharo** [comment]
@zavodnyuk That worked perfectly. Thanks!

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
