### ISSUE TITLE
Reset error

### ISSUE THREAD

**Issue by Honzaik** [google/recaptcha#175]
When I run grecaptcha.reset(id) there is an error 
![selection_011](https://user-images.githubusercontent.com/1215544/29129541-6b57c4ea-7d27-11e7-9305-050a99c90fb3.png)
am I doing something wrong? it is not caused by wrong id because I have only one captcha and the id is 0 is checked - thats what it is supposed to be for first captcha render right?

**Comment by jasonfedor** [comment]
Thanks for the report - please give us some more information to be able to reproduce (ideally the url where this is happening, browser, etc).

**Comment by Honzaik** [comment]
Tried to recreate it but the error is not shown. probably issues with my site also so i guess false alarm. but still. if I reset the captcha is the callback function called? I want to remove the styling on the outer div of the captcha as you can see here. https://honzaik.xyz/captcha/ it works only onload but when reset (2s after completing captcha) the callback is not called.

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
