### ISSUE TITLE
ReCaptcha V2 Audio (Words Only) doesn't work on Safari, IE, and Microsoft Edge

### ISSUE THREAD

**Issue by KevMLewis** [google/recaptcha#178]
This problem only happens when the audio prompt says "Press PLAY and enter the **words** you hear".  On safari, getting this prompt results in the page reloading. On all other browsers mentioned in the title, the audio just doesn't play when you press the "Play" button.

To reproduce, just keep refreshing the audio challenge until the prompt says "Press PLAY and enter the **words** you hear". It usually takes a few refreshes to make it switch from "numbers" to "words".

This occurs on all ReCaptcha V2 implementations I have seen. Here is a link to the google demo - https://www.google.com/recaptcha/api2/demo

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
