### ISSUE TITLE
Support for china

### ISSUE THREAD

**Issue by raypo1984** [google/recaptcha#188]
The recaptcha files never loads in China, it's a huge pain for the users and the products that use recaptcha[1] ,please consider to server it in googleapis.com or google.cn also , since these domain works fine in China[1], thank you!

[1] https://www.google.com/search?q=reCAPTCHA+china
[2] http://ping.chinaz.com/fonts.googleapis.com
http://ping.chinaz.com/google.cn

**Comment by jliu666** [comment]
Maybe you can use reCAPTCHA.net for it. @raypo1984  :smile:

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
