### ISSUE TITLE
Links Privacy and Terms doesn't work on IE 11 and Edge

### ISSUE THREAD

**Issue by Calystod** [google/recaptcha#191]
Hello,

We have notice links Privacy and Terms doesn't work on the captcha, nothing happen when we click on them. You can test here: https://www.google.com/recaptcha/api2/demo

Apparently, it's a bug of browsers but maybe a workaround exist.

If I remove the target, the page is open in the iframe.
If I change the target by _parent, it's work but open the link in the same page, not in a new tab.

**Comment by miksh7** [comment]
The links seem to work fine in latest IE11 (11.112.171134.0) / Edge (17.17134)

**Comment by rowan-m** [comment]
Closing older issues, please re-open if it's still a problem in current versions.

**Comment by ndegwaz** [comment]
This is still an issue in IE and Edge

**Comment by rowan-m** [comment]
This should be fixed now. Let me know if it's still not working.

**Comment by wanderingalbatross913** [comment]
Our web application is using google recaptcha v2. When the recaptcha loaded in windows applications via embedded Internet Explorer browser (latest IE 11), the Privacy and Terms link on the recaptcha doesn’t open.
The issue does not exist in latest IE 11 browser on the same pc.
