### ISSUE TITLE
'render=explicit' not working properly

### ISSUE THREAD

**Issue by MCStreetguy** [google/recaptcha#195]
When trying to render Captchas programmatically it appears that the first on page is already rendered, even if the Script-tag is set to `?render=explicit` and wrong values are used.

api script tag:
``` Html
<script src="https://www.google.com/recaptcha/api.js?render=explicit&amp;onload=initCaptchas&amp;hl=de" async defer></script>
```

example recaptcha element:
``` Html
<div class="g-recaptcha" data-sitekey="6LeHxC8...KXPSY" data-size="invisible" data-callback="captchaResponseHandler">
```

js file:
``` JavaScript
function captchaResponseHandler(response) {
  console.log('User submitted reCaptcha. Server responded: '+response.toString());
}

function initCaptchas() {
  var _run = function() {
    $('.g-recaptcha').each(function(index,element) {
      if(!$(element).children().length) {
        var id = grecaptcha.render(element, {}, true);
        $(element).attr('widget-id',id);

        if($(element).data('size') == 'invisible') {
          $(element).parents('form').on('submit',function(e) {
            grecaptcha.execute(id);
          });
        }
      }
    });
  }

  if($(document).find('.ajax-form').length) {
    $(document).on('ajaxStop',_run);
  } else {
    _run();
  }
}
```

When my function gets called the element is already filled with an visible captcha box, even if `data-size="invisible"` is present. Therefore my script skips the element to prevent the '... has already been rendered on this element' error.
Why is this? Shouldn't the api.js skip the rendering process with the `render=explicit` param?
I've triple checked my code and am pretty sure this is not my fault.
All functions defined in my js file get called at respective time (as callback of api.js and after all ajax-request have been finished).

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
