### ISSUE TITLE
new error after upgrading php

### ISSUE THREAD

**Issue by edwardsmarkf** [google/recaptcha#196]
PHP 5.4.16 (cli) (built: Nov  6 2016 00:29:02)

PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /usr/local/lib/php/recaptcha-master/src/ReCaptcha/RequestMethod/Post.php on line 68

PHP Warning:  file_get_contents(): Failed to enable crypto in /usr/local/lib/php/recaptcha/recaptcha-master/src/ReCaptcha/RequestMethod/Post.php on line 68

PHP Warning:  file_get_contents(https://www.google.com/recaptcha/api/siteverify): failed to open stream: operation failed in /usr/local/lib/php/recaptcha/recaptcha-master/src/ReCaptcha/RequestMethod/Post.php on line 68

EDIT:  probably a certification issue....

**Comment by divinity76** [comment]
i've seen some version of this error countless times on stackoverflow, its usually fixed by simply upgrading your OpenSSL lib, it's some fixed bug with some old version of OpenSSL

**Comment by KSVQ** [comment]
This is not an adequate answer,. Problem occurs often and in various scenarios where OpenSSL version is not old

**Comment by divinity76** [comment]
well, at least post the relevant libcurl & openssl versions as reported by `<?php phpinfo(~0);`, should look like this: 
![image](https://user-images.githubusercontent.com/1874996/39710260-92a7d704-521c-11e8-9af1-1c7e0f34d9eb.png)

**Comment by rowan-m** [comment]
Is this issue still occurring for anyone? If so, please provide further details.

**Comment by rowan-m** [comment]
Try making use of some of the alternate request methods:
```php
// uses http://php.net/fsockopen
$recaptcha = new \ReCaptcha\ReCaptcha($secret, new \ReCaptcha\RequestMethod\SocketPost());
// uses http://php.net/curl_exec
$recaptcha = new \ReCaptcha\ReCaptcha($secret, new \ReCaptcha\RequestMethod\CurlPost());
```
