### ISSUE TITLE
"pictures with roads" want me to click on pictures with road signs but no roads

### ISSUE THREAD

**Issue by divinity76** [google/recaptcha#197]
sometimes you get a `click on all the pictures with roads, when there are none left, click next` challenge,

problem is, there seems to be 3 pictures that include road signs, but the road itself is not actually on the picture, which it apparently expects you to click on as well. so either the pictures where the road is not visible, should be excluded, or the text should be "click on all the pictures with roads or road signs"

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
