### ISSUE TITLE
Ability to disable audio CAPTCHA

### ISSUE THREAD

**Issue by pzero24** [google/recaptcha#198]
I understand the audio CAPTCHA is used for accessibility for the visually impaired. However, it renders a CAPTCHA 100% ineffective because of how good speech recognition software has gotten.

Can there be a way to turn this off? If not, there is no point to using the CAPTCHA anymore.

**Comment by davidtgq** [comment]
+1 but considering Google's culture, I wouldn't expect them to want to associate their brand with such a move that could easily be twisted into making them look bad with the SJW's

**Comment by rowan-m** [comment]
I'm updating the `v1.2` branch to support the v3 API for reCAPTCHA which doesn't show challenges, just returns a confidence score for the user. This might help you. You can see a demo at: https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php
