### ISSUE TITLE
google/recaptcha Exception

### ISSUE THREAD

**Issue by suvathiks** [google/recaptcha#199]
Hi,

We are getting below error while checking the Recaptcha .

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.google.com') does not match the recipient window's origin ('http://localhost').

Can you please suggest any solution.

**Comment by AdamSalma** [comment]
I'm also having this issue. Is there a way to disable origin checking?

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.

**Comment by AdamSalma** [comment]
+1
