### ISSUE TITLE
Please make the code more abstract from Google's implementation today

### ISSUE THREAD

**Issue by billmeier** [google/recaptcha#201]
I use the routines, but find that it is better to have the output of

            <div class="g-recaptcha" data-sitekey="<?php echo $siteKey; ?>"></div>

In one function and

            <script type="text/javascript"
                    src="https://www.google.com/recaptcha/api.js?hl=<?php echo $lang; ?>">
            </script>

in another function. Then you don't have to worry about the exact syntax and API calls, etc. Google makes. You just call the function and you get the right code. I know that the API URL has changed in the past. Google also recommends that script be put in the <head> of the document and use async defer as well. https://developers.google.com/recaptcha/docs/display

Not a bug per say I guess, but a suggestion for more modular and independent code. No "Google" stuff in your HTML code.

Thanks for your consideration

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
