### ISSUE TITLE
reCAPTCHA puzzle is positioned relative to the center of body, not the viewport.

### ISSUE THREAD

**Issue by cfviotti** [google/recaptcha#208]
So, I have a very specific issue. Our site has a reCAPTCHA widget inside a sidebar that is positioned outside of the body. For this sidebar to be visible, we only need to add a negative margin-left to the body.
So when the captcha cannot identify the user as real person, the puzzle is rendered but positioned relative to the body, which in our case is too far from the reCAPTCHA widget or simply outside the screen when on mobile. Ideally the puzzle box should be positioned relative to the viewport, but I'm afraid that may be not be easy to fix. 
A quickfix would be to simply apply the same margin to the parent div containing the puzzle, but it lacks any class or attribute that could be used to easily select it. Could there be any other workaround? I'd rather not refact our sidebar just because of reCAPTCHA.

**Image examples:**
![](https://i.imgur.com/9zDywOu.png)
<img src="https://i.imgur.com/QsE4fTl.png" height="700">
![](https://i.imgur.com/MDlgKjN.png)

**Comment by Ayushman7** [comment]
Hi to all, i have used the recaptcha widget in angular material modal.Sometimes when i proceed and clicks on recaptcha   widgets then a puzzle box comes and this puzzle box comes far away from the recaptcha widget.I tried to solve this issue but nothing good happened.Please suggest some solution if you find some.Thanks.

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
