### ISSUE TITLE
Publish over NPM

### ISSUE THREAD

**Issue by damianobarbati** [google/recaptcha#214]
Would please consider publishing this over NPM? 
Lots of developers do use webpack or rollup to bundle their web apps and are not using `<script src="whatever"></script>` anymore :)

**Comment by nsuchy** [comment]
PHP doesn't work like that but there's composer 🥇

**Comment by damianobarbati** [comment]
@nsuchy I have no idea what you're talking about.
Anyway I'm referring to this piece of code a developer has to include:
```
<script src='https://www.google.com/recaptcha/api.js'></script>
```
Which ships just the following:
```
/* PLEASE DO NOT COPY AND PASTE THIS CODE. */(function() {if (!window['___grecaptcha_cfg']) { window['___grecaptcha_cfg'] = {}; };if (!window['___grecaptcha_cfg']['render']) { window['___grecaptcha_cfg']['render'] = 'onload'; };window['__google_recaptcha_client'] = true;var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;po.src = 'https://www.gstatic.com/recaptcha/api2/v1517207450225/recaptcha__en.js'; var elem = document.querySelector('script[nonce]');var nonce = elem && (elem['nonce'] || elem.getAttribute('nonce'));if (nonce) { po.setAttribute('nonce', nonce); }var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);})();
```
Which would be nice to be included with a simple:
```npm add recaptcha```

**Comment by nsuchy** [comment]
The repository is the PHP Client for validating responses. As for the client side stuff, there is an npm package for verifying the captchas in a node.js app (See: https://www.npmjs.com/package/recaptcha), there's also https://www.npmjs.com/package/react-recaptcha for client side.

**Comment by damianobarbati** [comment]
Oh I see: thanks for clarifying.
By the way neither of them is packaging the official script, they seem to both require you to include that manually.
Do you have any idea who is mantaining this hosted file `https://www.google.com/recaptcha/api.js`?
Or which repo is hosting it?

**Comment by nsuchy** [comment]
The reCaptcha Team at Google Maintains it, as for repo it's a client side API, I don't think that part is open sourced, I may be wrong.

**Comment by damianobarbati** [comment]
Who may I ask to have the script being "officially" published over NPM? Any contact? 😅

**Comment by nsuchy** [comment]
@damianobarbati I'm not a Google employee nor do I know any, I'm not sure if there's an official contact for this. The issue is probably the only thing you can do.

**Comment by damianobarbati** [comment]
Thanks for the help anyway @nsuchy , closing this :)
