### ISSUE TITLE
require('src/autoload.php');   fails

### ISSUE THREAD

**Issue by CMorawetz** [google/recaptcha#215]
I am following the straightforward directions from:
https://www.paperpencilwriteup.com/step-by-step-guide-to-integrate-google-recaptcha-2-0.html
to upgrade recaptcha in my form from V1 to V2.
The form works fine:
    http://www.oskarmorawetz.com/MusicOrders/MusicOrderForm.php

In my form's POST ACTION file, I do some HTML output, and then on the line:
`require('../recaptcha/v2/src/autoload.php');`
the code goes into never-never land and never returns (I have a print statement before and after the require - the one before prints, the one after doesn't). And yes, it's finding the autoload.php file - I've tested that.

I've downloaded the whole recaptcha library and placed it (unmodified) in the directory ../recaptcha/v2
I am trying to use the Direct Download method. Is there something special I need to do to the downloaded files so that they don't get a php error and fail? What am I doing wrong/missing?

Any help greatly appreciated, thanks!

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
