### ISSUE TITLE
ADA issue with textarea

### ISSUE THREAD

**Issue by leetoufong** [google/recaptcha#217]
Hi. I have a client who is VERY ADA compliant with their sites. Think insurance policies, etc.

There is an issue with the generated `<textarea>` element coming from the reCaptcha plugin. In the DOM, it's directly after the iframe and has an id of `g-recaptcha-response`. Simply, it's just missing a form label that corresponds with that specific textarea input field. Is this something that can be added with the next release? Or is there something I can do? Theoretically, I could add a static label from my end and call it a day but...then I'm not even sure what the statistics are on screen readers and Javascript or if it's disabled even.

Thoughts? Suggestions?

**Comment by NicolasKulka** [comment]
+1

**Comment by victorsantoss** [comment]
+1

**Comment by rowan-m** [comment]
You might want to look at the v3 support in the most recent release. That uses a wholly invisible reCAPTCHA that just returns a confidence score for the request. This might alleviate some of your issues. Example hosted at https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php

**Comment by Abvirk** [comment]
+1

**Comment by cahuizar** [comment]
Why is this closed? Current v3 does not address this issue, the textarea is still missing a form label. This can be easily fixed by adding `aria-hidden: true`

**Comment by mcrowell** [comment]
This is still an issue. Any plans to add the aria-hidden: true to the <textarea></textarea>?

**Comment by leetoufong** [comment]
This still seems like a rather simple fix. Rather than closing, I think just add a `aria-hidden=true` or a visibly hidden label with correct `for` attr.
