### ISSUE TITLE
Jquery Validation in Modal form

### ISSUE THREAD

**Issue by Nisarg1792** [google/recaptcha#218]
This is my code! I am slighly confused. where to do Recapatcha validation before submit the button? Thanks~ 

```
$("#Maincontact").validate({
			rules: {
		 		inputbox: "required",
		 		firstname: { required: true,},
		        lastname: { required: true,},
		        email: {	required: true,
		        			email: true
				},
		        phone: {
		        	required: true,
		            phonenumber: true
		        },
			},
		 	messages: {
		    	firstname: "Please enter your first name",
	        	lastname: "Please enter your last name",
		        email: "Please enter a valid email address",
		        phone: "Please enter a valid phone number"
			},
		 	errorElement: "span",
		 	errorClass: "form-error",
		 	invalidHandler: function(form, validator) {	},
		 	submitHandler: function (form) {
		 		var firstname 		= $('#firstname1').val();
				var lastname 		= $('#lastname1').val();
				var message			= $('#message').val();
				var email 			= $('#email1').val();
				var phone 			= $('#phone1').val();
				var gcaptchaVal 	= $("#g-recaptcha-response").val();
			var jqxhr = $.post( "mail_send.php", { firstname: firstname, lastname: lastname,email: email,phone: phone,message: message, gcaptcha: gcaptchaVal }, function(data) {
				if(data == '1'){
					$('#emailAlert1').addClass('green');
					$('.formItems-body').hide();
					$('#emailAlert1').html('Message sent successfully');
				} else {//alert('hie');die;
					$('#emailAlert1').removeClass('green');
					$('#emailAlert1').html(data);
				}
				}).done(function(data) {
				}).fail(function(data) {
					alert( "An error occured. Please try again" );
				});
				return false;
			}
		});
	});
```

**Comment by magic-77** [comment]
Hi, for Client-side Verification you can do it this way. I'm using invisible reCAPTCHA.
Don't forget to use Server-side Verification too
Load API with Callback
`<script src="https://www.google.com/recaptcha/api.js?onload=onloadCaptcha&render=explicit" async defer></script>`

JS:
`function onloadCaptcha() {
    grecaptcha.render(document.getElementById('recaptcha'), {
        'sitekey': '__SITEKEY__',
        'callback': function (response) {
            if (response) {
                _form.submit();
            }
        }
    }, true);
}`

Jquery Validator:
`submitHandler: function (form) {
      // Check if Google Captcha Object is initialized
      if (typeof grecaptcha !== 'undefined') {
         // Execute Google Captcha
         // Submit will be fired in Render Callback Function
         grecaptcha.execute();
          return _form = form;
       }
 }`

**Comment by Nisarg1792** [comment]
@magic-77 I already Load API with call back script but still having issue with JQuery validator and I have already done server side verification.

**Comment by magic-77** [comment]
Hi, can you describe your Issue

**Comment by Nisarg1792** [comment]
It's not validating recaptcha from Client side. I want to do mandatory client side validation. Form is submitting without recaptcha. If you can take a look my submit handler(modal code), that would be really appreciated. Thanks Again

**Comment by magic-77** [comment]
It does not Validate, because you are not telling the API to do this.
You have to move your Logic inside "grecaptcha.render" Callback function, as you can see my Code

**Comment by Nisarg1792** [comment]
grecaptcha.execute(); only works with invisible captcha and I am using visible captcha.

**Comment by magic-77** [comment]
Did you tried to move the "grecaptcha.render" inside "submitHandler"?

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
