### ISSUE TITLE
recaptcha puzzle box positioned far away from the google recaptcha widgets

### ISSUE THREAD

**Issue by Ayushman7** [google/recaptcha#219]
Hi to all, i have used the recaptcha widget in angular material modal.Sometimes when i proceed and clicks on recaptcha widgets then a puzzle box comes and this puzzle box comes far away from the recaptcha widget.I tried to solve this issue but nothing good happened.Please suggest some solution if you find some.Thanks.

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
