### ISSUE TITLE
Spam pass recaptcha with keyword "google"

### ISSUE THREAD

**Issue by stoneshower** [google/recaptcha#220]
I recently get many spam emails even though I use recaptcha. 
I have "company" input field and the common but strange thing is spam always has "google" in lowercase in the company field. Do you think this is somehow the way to pass recaptcha?

**Comment by AOlivar** [comment]
I have the same problem with recaptcha V2

**Comment by rowan-m** [comment]
Use of "google" in the field shouldn't make a difference to passing. I've updated this library to support v3 of the API now which gives you finer grained control over what requests you want to consider genuine.
