### ISSUE TITLE
Is Mailhide no longer supported?

### ISSUE THREAD

**Issue by hodgesmr** [google/recaptcha#221]
I noticed today that the v1 API for recpatcha had been turned off as of March 31 2018.

Now my mailhide links show a warning:

<img width="612" alt="screen shot 2018-04-03 at 5 57 20 pm" src="https://user-images.githubusercontent.com/1208575/38281603-92a299c0-3768-11e8-8f40-c23f3292fbfe.png">

But there's no clear way to upgrade to the v2 API. The [mailhide home page](https://www.google.com/recaptcha/admin#mailhide) still generates links that appear to use the old API.

Has mailhide been abandoned?

**Comment by DaveOzric** [comment]
Just spent a half hour trying to figure this out. Why is Google so confusing?? 

Anyone?

**Comment by gemmell** [comment]
Ditto. Leaves us in limbo.

**Comment by DaveOzric** [comment]
I signed up for this for now. 
[(http://www.webestools.com/antispam-email-protection-obfuscate-email-address-website-code-spam-javascript-base64-email-encoding-crypt.html)]

**Comment by PackerlandWebsites** [comment]
After searching the reCAPTCHA in Google Groups, I've found a thread where Google responded to the issue: https://groups.google.com/forum/#!topicsearchin/recaptcha/mailhide/recaptcha/CxzVXBI6G84

Basically, mailhide has been discontinued. :(

**Comment by simo1994** [comment]
This is obscene. Users who protected their email behind this service don't expect their email addresses to be subsceptible to scraping, like they are now.
Either upgrade mailhide, or take it offline completely.

**Comment by MrBryan** [comment]
"AI could solve the most difficult variant of distorted text at 99.8% accuracy. That's why we decided to deprecate reCAPTCHA V1."

**COME ON**, second most valuable company in the world! Not a dead end here... use something more complicated than distorted text without screwing everyone relying on your service

**Comment by MrBryan** [comment]
Or just let the stupid thing continue working even if AI means some percentage of sophisticated bots will get the email rather than billions more basic ones

**Comment by stefan2904** [comment]
The deprecation of reCAPTCHA V1 has nothing to do with the deprecation of mailhide. Google could operate mailhide using v2?

**Comment by wilk-polarny** [comment]
@stefan2904 Of course they could, but I doubt they will.

**Comment by marcelstoer** [comment]
Gee, wondering what it will take until Google at least considers migrating mailhide to reCAPTCHA v2.

**Comment by adamnoffie** [comment]
Suggested alternative:  http://scr.im

**Comment by hanshuo** [comment]
I couldn't wait for the migration to happen. Instead, I wrote a replacement of Mailhide that uses reCAPTCHA v2: https://github.com/hanshuo/mailhide2

**Comment by eximius313** [comment]
Also affected :(

**Comment by rowan-m** [comment]
The v1 version of the API and Mailhide are no longer supported. I've just released a new version of this library along with some examples of the different current reCAPTCHA variants on which you could build something similar to Mailhide.

**Comment by eximius313** [comment]
@rowan-m could you provide url to the examples?

**Comment by rowan-m** [comment]
https://github.com/google/recaptcha/tree/master/examples
https://recaptcha-demo.appspot.com/

**Comment by simo1994** [comment]
So @rowan-m -- let me understand this: Google will leave massive amounts of mail addresses unprotected on Mailhide pages instead of updating the Mailhide code to v2?
This is nonsensical. Either discontinue the service and take it offline, or update to v2. People who decided to use Mailhide don't want their email address exposed to crawlers.
I wonder how this even fits with EU GDPR, since it doesn't seem like Mailhide gives an easy option to take a Mailhide URL offline. An email address is personal data.

**Comment by eximius313** [comment]
@rowan-m I can not find "Mailhide" example among the ones that you've linked. Am I missing something?

**Comment by detailyang** [comment]
sad. Google always close some small but beautiful thing:(

**Comment by Kasonz** [comment]
Hi guys, I recently published a work to provide the free service just like mailhide, you can take a look :) https://mailhide.io

**Comment by irishgeoff22** [comment]
You can [hide email on website with captcha](https://veilmail.io) using veilmail.io

**Comment by chrisma** [comment]
> Hi guys, I recently published a work to provide the free service just like mailhide, you can take a look :) https://mailhide.io

Hi @Kasonz, thanks a lot for providing the mailhide.io service. However, it seems down (probably has been for some time). Any alternatives you'd recommend? Thanks!

**Comment by Kasonz** [comment]
> > Hi guys, I recently published a work to provide the free service just like mailhide, you can take a look :) https://mailhide.io
> 
> Hi @Kasonz, thanks a lot for providing the mailhide.io service. However, it seems down (probably has been for some time). Any alternatives you'd recommend? :) Thanks!

Hello @chrisma , oh, just saw the comment, it's already fixed, it was due to my credit card got expired...
