### ISSUE TITLE
Access recaptcha through reverse proxy

### ISSUE THREAD

**Issue by hkworker2002** [google/recaptcha#223]
Following discussion below, we have setup Apache reverse proxy for accessing Google recaptcha for serving China user access purpose: 
https://github.com/google/recaptcha/issues/87

However we found that for all recaptcha traffic going through reverse proxy, it always require input recaptcha by selecting image even we have set the Security Preference to the lowest value. (with direct access recaptcha service, we just need to click the checkbox "I am not a robot"

It seems that all request going through reverse proxy are under high risk and require additional verification. Any one have idea to overcome this?

Thanks.

**Comment by rowan-m** [comment]
Reliability of results and user experience if you're going through a proxy is really out of scope for this repo. I've updated the code to allow for setting of an explicit URL and I'm happy to take PRs that add `RequestMethod`s for better working within a proxy.
