### ISSUE TITLE
Not working for Google AVPI v2

### ISSUE THREAD

**Issue by pablomoreno61** [google/recaptcha#224]
Instead of using _submitHTTPGet you have to use something like:

    private function _submitHTTPPOST($path, $data)
    {
        $verify = curl_init();
        curl_setopt($verify, CURLOPT_URL, $path);
        curl_setopt($verify, CURLOPT_POST, true);
        curl_setopt($verify, CURLOPT_POSTFIELDS, http_build_query($data));
        curl_setopt($verify, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($verify, CURLOPT_RETURNTRANSFER, true);
        $response = curl_exec($verify);

        return $response;
    }

**Comment by rowan-m** [comment]
Is this issue still occurring for you?

**Comment by rowan-m** [comment]
Try making use of some of the alternate request methods:
```php
// uses http://php.net/fsockopen
$recaptcha = new \ReCaptcha\ReCaptcha($secret, new \ReCaptcha\RequestMethod\SocketPost());
// uses http://php.net/curl_exec
$recaptcha = new \ReCaptcha\ReCaptcha($secret, new \ReCaptcha\RequestMethod\CurlPost());
```
