### ISSUE TITLE
reverse proxy google invisible recaptcha

### ISSUE THREAD

**Issue by yourenyouyu** [google/recaptcha#225]
Because of google's service unaccessable in China, I tried to reverse proxy google invisible recaptcha service and meet some unsolvable problems, the captcha just shows every  time, and need to pass like 7~10+ captcha per try. Here's what I do

[this is my nginx conf](https://gist.github.com/yourenyouyu/fca64552e69273fa58bd43f68a430036)

**Comment by rowan-m** [comment]
Reliability of results and user experience if you're going through a proxy is really out of scope for this repo. I've updated the code to allow for setting of an explicit URL and I'm happy to take PRs that add `RequestMethod`s for better working within a proxy.
