### ISSUE TITLE
Use recaptcha without google.com domain

### ISSUE THREAD

**Issue by grishin** [google/recaptcha#227]
As google.com domain is blocked in Russia from today all calls to recaptcha fail. We changed all calls to https://www.recaptcha.net domain but it still fails. 

I found that https://www.gstatic.com/recaptcha/api2/v1523860362251/recaptcha__en.js internally calls to google.com/recaptcha/ even if it is served from recaptcha.net base url. Diving deeper into code I found some internal (undocumented?) parameter p.__recaptcha_api that possibly changes the base url. 

![image](https://user-images.githubusercontent.com/3284017/39189558-2f415ef6-47db-11e8-9a09-184f5eaaf7ce.png)

Still I can't understand how should this configuration be passed to internal script. Is there any documentation or examples for using recaptcha in such conditions?

**Comment by rowan-m** [comment]
Reliability of results and user experience if you're going through a proxy is really out of scope for this repo. I've updated the code to allow for setting of an explicit URL and I'm happy to take PRs that add `RequestMethod`s for better working within a proxy. There's quite a bit of discussion on #87 that may help.

**Comment by varunachar** [comment]
This is still an issue. There are still requests that go to google.com domain from the script loaded via recaptcha.net. Has a workaround been published somewhere I can take a look? I prefer not to setup a proxy just for this.
