### ISSUE TITLE
Empty response

### ISSUE THREAD

**Issue by xpowert** [google/recaptcha#228]
Hello, I set up captcha and when I do a security check it gives me error wrong captcha, so I check the response and I always get an empty response. 
My PHP file. Right now it prints out the response, what is always empty.

`///Start Captcha
		
		$captcha		= HTTP::_GP('g-recaptcha-response', '');
		if (Config::get('capaktiv') === '1')
		{
			
            require('./includes/libs/reCAPTCHA/autoload.php');
				
				
            $recaptcha = new \ReCaptcha\ReCaptcha(Config::get('capprivate'));
            $resp = $recaptcha->verify($captcha, Session::getClientIp());
			$reaper = $captcha;
            if (!$resp->isSuccess())
            {
                $errors[]	= $reaper;
				
            }
		}
		
		///End captcha`

Live version here -> http://eogame.a2hosted.com

**Comment by rowan-m** [comment]
I'm not sure of the context of your code, but you could try:

```php
$captcha = HTTP::_GP('g-recaptcha-response', '');

if (Config::get('capaktiv') === '1') {
    require('./includes/libs/reCAPTCHA/autoload.php');
    $recaptcha = new \ReCaptcha\ReCaptcha(Config::get('capprivate'));
    $resp = $recaptcha->verify($captcha, Session::getClientIp());

    if (!$resp->isSuccess()) {
        $errors = $resp->getErrorCodes();
    }
}
```
