### ISSUE TITLE
reCAPTCHA not rendering until refresh 

### ISSUE THREAD

**Issue by luckyvs1** [google/recaptcha#229]
Recently (today) we noticed the reCAPTCHA would not load on the first render, but does render on a refresh.

Were there any recent changes or issues that may have changed the rendering of the reCAPTCHA?

Thanks

**Comment by LukasBeaton** [comment]
I am having the same issue. The recaptcha used to work fine and now it only works once and then the page needs to be refreshed...

**Comment by strngerABC** [comment]
We're having a very similar issue. It will load the first time, but if the user navigates to a different part of the site, then comes back to the original page, the recaptcha will not load. However, if they refresh the page it shows up again.

Just to be clear, we are using recaptcha version 2

**Comment by viciousbraun** [comment]
This is my solution as my project is also experiencing this issue. The code below requires jQuery. I also had to explicitly render the recaptcha

`	$(document).ready( function(){
		setTimeout(function(){
			if($('#DIV_ID').children().length === 0) {
				grecaptcha.render('DIV_ID', {
					'sitekey' : 'YOUR_SITE_KEY', 
					'callback' : recaptchaCallback
				});
			}
		}, 500);
	});`

The UI for my project actually has 4 recaptchas implemented, however only one of them is experiencing this loading issue.

**Comment by strngerABC** [comment]
We did the exact same thing (conceptually), but I don't like the solution as it feels very "hacky." We were hoping Google could provide some insight as to why it's happening and/or patch the problem so we don't have to do this.

**Comment by luckyvs1** [comment]
The above issue is tied to reCaptcha v2 and also noticed sites such as Reddit no longer have an explicit reCaptcha on login or registration just recently. 

Even with the above there seems to be little to no information regarding this issue elsewhere including the google forums (https://groups.google.com/forum/m/#!forum/recaptcha).

**Comment by paxa1887** [comment]
I am having the same issue. The reCaptcha is not rendering until refresh, in incognito mode.

**Comment by acclaimuser** [comment]
We are getting this error now which has been working for long time.

Uncaught TypeError: (intermediate value)(intermediate value).push is not a function

**Comment by rowan-m** [comment]
This isn't directly related to the PHP code which is what this repo focuses on. However, you might want to look at the v3 support in the most recent release. That uses a wholly invisible reCAPTCHA that just returns a confidence score for the request. This might alleviate some of your issues. Example hosted at https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php

**Comment by anliner1992** [comment]
> ```js
> $(document).ready( function(){
> 	setTimeout(function(){
> 		if($('#DIV_ID').children().length === 0) {
> 			grecaptcha.render('DIV_ID', {
> 				'sitekey' : 'YOUR_SITE_KEY', 
> 				'callback' : recaptchaCallback
> 			});
> 		}
> 	}, 500);
> });
> ```

how to convert this into function component or class component

**Comment by riyazSoftW** [comment]
try this is its working for me useEffect(() => {
    const parentDiv = document.getElementById("captcha-parent")!;
    ReactDOM.render(
      <ReCAPTCHA
        sitekey="KEY"
        onChange={() => {
          setFieldValue("recaptcha", true);
        }}
      />,
      parentDiv,
    );
  }, []);

**Comment by riyazSoftW** [comment]
try this its working for me
```
const parentDiv = document.getElementById("captcha-parent")!;
ReactDOM.render(
<ReCAPTCHA
sitekey="KEY"
onChange={() => {
setFieldValue("recaptcha", true);
}}
/>,
parentDiv,
);
}, []);
```

**Comment by nohestmm** [comment]
> try this its working for me add this peace of code in the same component where you want to add reCaptcha
> 
> ```
> useEffect(()=>{
> const parentDiv = document.getElementById("captcha-parent")!;
> ReactDOM.render(
> <ReCAPTCHA
> sitekey="KEY"
> onChange={() => {
> //
> }}
> />,
> parentDiv,
> );
> }, []);
> ```

This!!! thank you

**Comment by nohestmm** [comment]
my solution in React

import React, { useState, useEffect } from 'react';
import ReCAPTCHA from "react-google-recaptcha";
import useBoletero from "../hooks/useBoletero";

const RecaptchaButton = () => {
  const [showCaptcha, setShowCaptcha] = useState(false);
  const { setIsRecaptchaValid, recaptchaRef} = useBoletero();



  const handleRecaptchaChange = () => {

    setIsRecaptchaValid(true);
  };
  
  useEffect(() => {
    const shouldShowCaptcha = true;

    if (shouldShowCaptcha) {
      setShowCaptcha(true);
    }

  }, []);

  

  return (
    <>
    {
      showCaptcha && (
      <ReCAPTCHA
      ref={recaptchaRef}
      sitekey="6Le9BiYpAAAAAIkovoTSlNkqRtcwEAbbL5btbL6y"
      onChange={handleRecaptchaChange}
      className="flex w-100 justify-center"
    />
      )
    }
 </>
  )
}

export default RecaptchaButton;

**Comment by nohestmm** [comment]
`import React, { useState, useEffect } from 'react';
import ReCAPTCHA from "react-google-recaptcha";
import useBoletero from "../hooks/useBoletero";

const RecaptchaButton = () => {
  const [showCaptcha, setShowCaptcha] = useState(false);
  const { setIsRecaptchaValid, recaptchaRef} = useBoletero();



  const handleRecaptchaChange = () => {

    setIsRecaptchaValid(true);
  };
  
  useEffect(() => {
    const shouldShowCaptcha = true;

    if (shouldShowCaptcha) {
      setShowCaptcha(true);
    }

  }, []);

  

  return (
    <>
    {
      showCaptcha && (
      <ReCAPTCHA
      ref={recaptchaRef}
      sitekey=""
      onChange={handleRecaptchaChange}
      className="flex w-100 justify-center"
    />
      )
    }
 </>
  )
}

export default RecaptchaButton;`
