### ISSUE TITLE
Recaptcha is so buggy as hell

### ISSUE THREAD

**Issue by Raj2032** [google/recaptcha#231]
Honestly Recpatcha is so bad that we should use the traditional captcha codes.

Before recaptcha used to be great most of the times I used to check on the box and it was fine. Now everytime i click ont he check box I am forced to "Find all the cars" for example. WHy do you give such hard to see images with cars that are placed so far back to make it nearly impossible to see for example? Why cant you just have simple non cartoon images. Also it keeps saying that "Your computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit our help page" So now everytime I want to do something, I have to deal with this crap. Websites are so unusable because of this. Please fix it and make it what it used to be like.

**Comment by KyranRana** [comment]
I strongly agree. Very buggy.

I can't even click the images on some examples as the tick keeps fading out. Needs major improvement.

**Comment by Raj2032** [comment]
Google ain't gonna fix anything, but rather they are going to make it even
worse, they have always been downgrading YouTube and Google+. Before,
Google captcha used to hardly ever ask for me to do the pictures shit and
it was an awesome service.

**Comment by tara2** [comment]
We are taking it off our site today (28June '18) - for the past 7 days we've had unhappy customers contacting us by other means as they can't use the recaptcha.  A pity!

**Comment by ip1981** [comment]
Quoting https://productforums.google.com/forum/#!topic/websearch/tFHDAsX4Ypk

> FIRST OF ALL, FUCK YOU GOOGLE COMPANY, PLEASE GO AND EAT SHIT. I'VE BEEN USING YOUR APPS FOR SO LONG AND NOW YOU COME OUT WITH YOUR STUPID AND FUCK UP IDEA WHICH IS RECAPTCHA. IT SLOWING US IN SURFING THE INTERNET, ALWAYS ASKING THE BULLSHIT AND FUCK QUESTION. IF YOU WANT TO HAVE THAT APPS WHAT SO EVER, MAKE SIMPLER...LAST BUT NOT LEAST, FUUUUUUUCCCCCCCKKKKKKKK YOU GOOGLE FOR YOUR STUPID RECAPTCHA...FUCK YOU AND GO FUCK YOUR SELF.

I simple cannot login (not register!) on some sites, because their admins think  recaptcha is so great. Eat shit.

**Comment by Raj2032** [comment]
Sorry to hear about that mate. Discord is the shittiest to be honest, when
I am using it, for no reaosn it locks me out and asks me to do this shitty
recaptha questions. Most of the attempts I do is wrong for some fucking
reason. When I get it right it then asks me to do it again. And it may even
sometimes state that my comptuer is sending automatic quiries please try
again later. So fucking stupid I wish we can go back to the traditional
captcha codes, they were way better. Fuck Google. THey have no idea what
the fuck they are doing.

**Comment by rowan-m** [comment]
These are issues with the reCAPTCHA service itself rather than the client library, which is what this repo focuses on. There are additional support options at https://groups.google.com/forum/#!forum/recaptcha that may be more appropriate for you.

**Comment by Raj2032** [comment]
May I ask why is Google not doing anything to fix this shit?

**Comment by eypsilon** [comment]
Google needs lot of help to label all the spy pics, they collect from all over the world ... and to make it looks fine, they claim it's for their self driving AI improvement ...

**Comment by Raj2032** [comment]
Google should get fucked.

**Comment by zakjakub** [comment]
Why will be this fucking shit solved? It has about 99% false-negative! You're stupid idiots!

**Comment by KyranRana** [comment]
Just to update, Recaptcha v3 is now being developed and hopefully it should completely get rid of these very frustrating puzzles...

https://developers.google.com/recaptcha/docs/v3

**Comment by Raj2032** [comment]
Lets hope it worsks thanks for that

**Comment by Raj2032** [comment]
I know right. Gaygle is only going to get worse.

**Comment by pienisieni** [comment]
The only thing a responsible person can do at this point, is to contact services using recaptcha and complain to them just how annoying it is. But what better alternative can I recommend?

Or would that even change anything..?

**Comment by ip1981** [comment]
I am a robot. Proof: https://www.youtube.com/watch?v=U2q1f1ECMP4

**Comment by victorhramos** [comment]
who developed that stupid buggy shit?

**Comment by 12earth** [comment]
i am done.  this is getting removed tomorrow!

what ever they did broke it.

**Comment by julian-weinert** [comment]
Agree to everyone here. REcaptcha is the worst crap I've seen.
You simply make it harder for humans to use the internet.
Permanently clicking 50 images of traffic lights, bikes and crosswalks doesn't do shit. And after all you're rejected. Whenever I encounter this shit I'm struggling to use the service I want to.

PLEASE GOOGLE, just stop it. Remove it or replace it with a useless button.
If someone wants to get around it programmatically they will. That is the simple nature of the internet. The only ones you're locking out are humans.

**Comment by victorhramos** [comment]
you just need to answer 247274827423746524 times

**Comment by JHeartyP** [comment]
recaptcha is so bugged it's constantly taking me 5 to 10 minutes to get a valid response -.- recaptcha is cancer

**Comment by tcojean** [comment]
This is quite literally a pile of bugs. I can confirm it takes 5 to 10 minutes to get any capcha done. This tool is a pure waste of time for everyone on the internet. Fix your shit.

**Comment by SergeiMinaev** [comment]
Recaptcha ruins user experience

**Comment by laztname** [comment]
recaptcha is takes longer time, please, i take 6-15 to confirm that i'm not a robot --"

**Comment by deniskx** [comment]
google captcha developers will be burn in hell

**Comment by Jean-Daniel** [comment]
There is not a single day where I don't have to stop an order in progress and have to find an other vendor because of this shit.

The only purpose of this thing it to help google to train its AI for autonomous vehicle, and it work so bad that I'm happy to live in a place where there is no Google car on the read…

**Comment by ChazizYT** [comment]
You'd think the headphone icon would work (the text one). But it doesn't do anything it just says that you're a bot...

Google's Logic:

**BOTS = HUMANS
actual HUMANS = BOTS**

**Comment by proninyaroslav** [comment]
The creators of reCAPTCHA will be in hell forever collecting puzzles of their crappy brainchild.

**Comment by Serpens66** [comment]
always clicking every correct picture, but in 90% of the cases it says I should repeat! I hate this buggy nonsense!

**Comment by uq1** [comment]
This is a firewall around the internet and anti competitive. They do not block their own "bot".

I **demand** google block it's bot. Good for the gander, good for the goose.

**Comment by egandunning** [comment]
**Please just let me type the garbled letters**. Much better than training your ML algorithm.

**Comment by azamet90** [comment]
while life != finish
     solverecaptcha()

**Comment by Raj2032** [comment]
XDDDDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by zooid** [comment]
> google captcha developers will be burn in hell

They should not burn in hell they should be forced to do endless recapture.

**Comment by Joe23232** [comment]
@zooid 

Lol so true :)

**Comment by real-marshal** [comment]
Obligatory FUCK RECAPTCHA AND GOOGLE. Spent 5 minutes trying to solve this shit. Says try again, after multiple attempts it closes and then I have to pick another set of cars, buses, bikes & crosswalks. Then the images start to slooooowly fade in and out making me incredibly mad. I guess a robot would be more patient.

**Comment by Raj2032** [comment]
Honelsty fuck Google
