### ISSUE TITLE
Transparent overlayer after clicking on recaptcha

### ISSUE THREAD

**Issue by Narduw** [google/recaptcha#234]
Hi! I'm having an issue where after clicking the recaptcha in Iphone 5, 5SE (but also on Android on outdated 'Browser' app - sorry I cannot test in other devices) the page gets covered by a white/transparent overlayer.

Similarly to [this other issue](https://github.com/google/recaptcha/issues/126).

However, I do not even get to see the challenge, just a white/transparent overlayer and nothing else.

Image:
![overlayer issue](https://user-images.githubusercontent.com/16376552/40536814-9bc46fec-600d-11e8-84fd-0b55ff01aacf.PNG)

Also: it stays like this until it timeouts.

EDIT: This is the div that appears:
`<div style="width: 100%; height: 100%; position: fixed; top: 0px; left: 0px; z-index: 2000000000; background-color: #fff; opacity: 0.5;  filter: alpha(opacity=50)"></div>`

Any help would be appreciated.

Thanks!

**Comment by rowan-m** [comment]
This isn't directly related to the PHP code which is what this repo focuses on. However, you might want to look at the v3 support in the most recent release. That uses a wholly invisible reCAPTCHA that just returns a confidence score for the request. This might alleviate some of your issues. Example hosted at https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php
