### ISSUE TITLE
Recaptcha v3 always returns a 0.9 score

### ISSUE THREAD

**Issue by AOlivar** [google/recaptcha#235]
I have a problem with recaptcha V3, always return request is 0.9 score and this a problem? keep sending the form.

**Comment by atlanteh** [comment]
Happens to me too

**Comment by cristiano-belloni** [comment]
Happens to me too.

**Comment by cristiano-belloni** [comment]
@AOlivar - could you edit te tile to something like "Recaptcha v3 always returns a 0.9 score"? That might be easier to read.

**Comment by sliterok** [comment]
UPD: 2 of 11 users got score 0.3. That was static score(at least for 20-30 minutes stayed the same). Other 9 has gotten score of 0.9 (also static)

**Comment by atlanteh** [comment]
What I did was open my site in incognito mode. never hovering or interacting with the website. I had developer tools opened, and using the console & selector I clicked a button which calls the recaptcha.
I still got 0.9.

**Comment by sliterok** [comment]
@atlanteh as far as i understend it uses your ip adress and seraches actions from google-included websites or google itself.
I may ask you to use proxy and try it again.

**Comment by atlanteh** [comment]
It doesn't seem right. If I'm behind a router, all the computers will have the same external ip address.

**Comment by sliterok** [comment]
Nonetheless it looks like it's working this way...
(based on my little research doing more "actions" doesn't change score anyhow)

**Comment by sliterok** [comment]
One of my users is using(!) Chrome 63, but he's getting 0.3 score

**Comment by mhervy** [comment]
@sliterok I'm using Chrome 66

**Comment by Timeo73** [comment]
Same problem here. I always get 0.9 score. Is it normal?

**Comment by rowan-m** [comment]
This is more of a question with the reCAPTCHA service rather than the client library, but that said I'll add a personal opinion.

So, this isn't a definitive answer, but I wouldn't be worried about not receiving a 1. Consider it like a probability score where 1 would mean with absolute certainty this is not a bot. That can never be guaranteed, so a 1 would never happen. It's probably safe to work on the assumption you're getting a probability score rounded down to the nearest 0.1.

**Comment by namlq93** [comment]
Me too. I want to check case score 0,1 -> 0,5. But  Recaptcha v3 always returns a 0.9 score.. How to do it?

**Comment by rowan-m** [comment]
A few things on this:
- You can see the range of scores being returned for requests on your dashboard: https://www.google.com/recaptcha/admin#list
- I get a lower score on my phone if I run in a browser I don't normally use, in incognito or private mode, and through a VPN. Trying a combination of things like this may result in a different score.
- For a testing environment though, you should set up your own mock service that returns different values. You can do this either by creating something that implements `RequestMethod` or by creating a mock service on a different URL and pass that in to your `RequestMethod`.

**Comment by jfromaniello** [comment]
any ideas why I'd get 0.9 with *chrome headless on an incognito context* ? this classify enough as a bot for me. I tried using different ISPs to change the connection, and still get 0.9. The website I am testing does an `alert(score);` of the score returned by recaptcha v3:

```javascript
const puppeteer = require('puppeteer');

async function doit(browser) {
  const context = await browser.createIncognitoBrowserContext()
  const page = await context.newPage();
  const result = new Promise((resolve) => {
    page.once('dialog', (dialog) => {
      console.log(dialog.message());
      resolve();
    });
  });

  await page.goto('https://a-website.com/');

  return result;
}

(async() => {
  const browser = await puppeteer.launch();

  const operations = [];

  for(var i =0 ; i < 10 ; i++ ) {
    operations.push(doit(browser));
  }

  await Promise.all(operations);

  await browser.close();
})();

```

**Comment by xmontero** [comment]
Indded. If it's an "autoamted test" it "should" give low score. Shouldn't it?

**Comment by nikita-seliverstov** [comment]
Used selenium automated test with bunch of console command executions still 0.9

**Comment by simonoop** [comment]
>Same with me used selenium automated test with bunch of console command executions still 0.9
+1

**Comment by abass** [comment]
Experiencing this as well. My client is getting loads of spam form submissions and yet 99% of the traffic is showing .9 - there's no way that is accurate. Anyone know what might be going on here?

**Comment by dalmenar** [comment]
+1. I try with Selenium with 0.9 score...

**Comment by mastagino** [comment]
Not sure if this is the case, but they recommend to put recaptcha V3 in multiple regular traffic pages, so that they can analyze and see what is normal traffic for your website. If you simply put it on a form, it is not enough.

**Comment by lmaxheim** [comment]
I can reproduce the error as well. Also with the approach suggested by mastagino I get the score of 0.9 for every submit I make.

**Comment by eltats** [comment]
can sum post code with selenium which return 0.9?

**Comment by aerkanc** [comment]
> can sum post code with selenium which return 0.9?
@eltats
I 've tested native javascript via developers tool console. score is 0.9 again!

**Comment by Murrengan** [comment]
Recaptcha v3 not working!
I try selenium (headless and standard) and get 0.9 on all my request  =((

**Comment by boagriuz** [comment]
Any solution/updates on this?

**Comment by paulshorey** [comment]
Same for me. I programmed a web crawler in Apify.com. Took 5 minutes. I am able to collect all my site data, which was returned by AJAX request, which is secured by recaptcha v3. Watching console logs on my remote server, it always returns 0.9 score no matter what!

**Comment by averri** [comment]
Why is this closed?! There is no explanation to the questions! I'm facing the same situation:

![image](https://user-images.githubusercontent.com/1898447/79672836-50142e00-81cd-11ea-883b-8fae87f8f7d1.png)

**Comment by xmontero** [comment]
Hummm... Isn't the "closing" action appearing in the timeline itself? Didn't github place a "Person Foo closed Issue Bar on XXX date" within the timeline? I'd like to know WHO closed and WHY closed this issue.

**Comment by sliterok** [comment]
> Hummm... Isn't the "closing" action appearing in the timeline itself? Didn't github place a "Person Foo closed Issue Bar on XXX date" within the timeline? I'd like to know WHO closed and WHY closed this issue.

https://github.com/google/recaptcha/issues/235#issuecomment-408701725

**Comment by cstrouse** [comment]
Completely bogus form entries yield 0.8 or 0.9 for me. Clients are getting spammed like crazy and this seems to do zero good. Definitely an issue here!

**Comment by Zentorer** [comment]
Yes, I'm implementing v3 and the same thing happens to me, all requests are 0.9.
Test changing ips and the results were the same.

**Comment by atlanteh** [comment]
Unless you have a useful info to share with everyone, please do not add another rather generic "I tried it too, doesn't work". You are email alerting everyone in this thread. Adding a like on the author post is just fine. Thx, and sorry for this alert

**Comment by cstrouse** [comment]
@atlanteh Have you considered that the point of this is to ***draw attention*** to a problem that is being ignored for what appears to be no reason?

**Comment by sliterok** [comment]
@cstrouse, that repository is for PHP library for recaptcha, so i guess posting here about the functional problems of captcha 3 is useless.

**Comment by ertejaspatel** [comment]
Has anyone got any workaround about how to test or force google to return low score. 

I tried 

- Selenium with headless, 
- changed chrome browser useragent to Bot
- tried in incognito window but no luck 

none of them worked for me. I always get score of 0.9

Preferred Solution: 
Ideally google should provide test configuration in settings on Admin console so that user can configure that test request should receive x score.

Thanks

**Comment by sengfoong9898** [comment]
Has anyone know how to check the recaptcha score? thank you

**Comment by almazka987** [comment]
+1 Same problem!

**Comment by ms-dinesh-lawate** [comment]
+1 Same issue! 
ReCaptcha Enterprise v3 always return same exact score i.e. 0.8999999761581421 for all the users and even with selenium testing also it gives same exact score. 
Not sure whether that number is hardcoded inside captcha library or not?

**Comment by derryberni** [comment]
+1 Same issue!

**Comment by qweluke** [comment]
+1, same problem

**Comment by dattannguyen** [comment]
+1 same issue

**Comment by julianmodiano** [comment]
Same issue here, wrote a puppeteer script that logged in for me in headless chromium 200+ times in 10 minutes and every single score came back as 0.9 - tested it on the production site in case it's somehow smart enough to realize that localhost is probably safe, and was on a VPN as well so surely it shouldn't save the IP as safe from when I'd previously logged in legitimately. Seems like it's basically useless...

**Comment by flcoder** [comment]
+1 same

**Comment by ashatat** [comment]
did anyone get an explanation for this issue?

**Comment by raymondjacobson** [comment]
+1 same

**Comment by hugobarbato** [comment]
+1 SAME

**Comment by john-larson** [comment]
It has been almost 3 years since this issue was opened. So, I would like to ask for everyone's opinion on the current status of the problem. Does v3 get to a stable point after some time in the production environment so that it effectively tells bots from humans? Or is it still totally useless and we should use v2 instead? It would really help if you could share your experience after some time of using it. Which way did you go?

**Comment by xmontero** [comment]
We kept to be in v2. I would expect someone from the recaptcha team to explain how to reproduce a "failure" from a selenium or so. Until having it clear, we are in v2.

**Comment by rddrdhd** [comment]
+1 same
I tried using Selenium and JS code for submitting form every 5 seconds. Everytime my score was 0.9
Looks like I'll have to use v2

**Comment by marcelopham** [comment]
Google shouldn't be advertising Google Recaptcha v3 as "reCAPTCHA protects your website from fraud and abuse." and "Proven". I am on the same boat as everybody above - a simple selenium script will get you a 0.9 score 100% of the times .... I just can't imagine how many webmasters think "they're protected" by Google recaptcha and their sites are being spammed with bots ...
And why is the issue "Closed"??

**Comment by felixmeziere** [comment]
Exact same problem here,  getting 0.9 score with my cypress bot every single time... is ReCaptcha v3 even serious?

![image](https://user-images.githubusercontent.com/11617630/110152450-ac7a3f00-7dd9-11eb-95a6-ef71f7a5ff43.png)

**Comment by jamheadart** [comment]
I've just implemented v3 on one button on one page of my site and over a couple of days I submitted the same form a few times and got scores of 0.9. OK. My site has 2-5 requests per day, most of which are me testing it, all 0.9 score. Then on one random day there were 150+ requests, so I assume "definitely some spamming there from God knows where, I bet it's marked some of those down!" All 0.9. How is it actually supposed to work? What exactly is it supposed to be detecting? Those 150 requests weren't valid form submissions; they didn't carry through nor send an e-mail, and I really doubt they were all human. I just don't get how a score can even change at this point.

**Comment by fabioselau077** [comment]
+1

**Comment by robo-monk** [comment]
+1 - why is this issue closed?

**Comment by lucasbasquerotto** [comment]
It was [closed](https://github.com/google/recaptcha/issues/235#issuecomment-408701725) with the comment:

> This is more of a question with the reCAPTCHA service rather than the client library, but that said I'll add a personal opinion.
> 
> So, this isn't a definitive answer, but I wouldn't be worried about not receiving a 1. Consider it like a probability score where 1 would mean with absolute certainty this is not a bot. That can never be guaranteed, so a 1 would never happen. It's probably safe to work on the assumption you're getting a probability score rounded down to the nearest 0.1.

It seems that this was closed because this repository is about the PHP client of recaptcha, rather than the recaptcha service. If I search in my browser for `google recaptcha v3 github`, the first link that I see points to this repository, so it seems there isn't a github repository about the recaptcha service. 

It would be good to know where to open an issue then, although, wherever it is, it would have probably much less visibility and activity than here in github. For example, I was using an HTTP rest request in java without any libraries/sdk, but due to the results from the API it seemed to me that something was wrong, and seeing this issue was important for me, because I had similar problems to the people here.

About the 2nd part of the quoted text, rounding down to the nearest 0.1 would do no good if all scores are high.

**Comment by paulshorey** [comment]
Is there any alternative to Google's invisible v3? Does anyone know of any script or hack to tell if it's a real person browsing the site/app? If not, I'm going to build it.

**Comment by marcelopham** [comment]
> Is there any alternative to Google's invisible v3? Does anyone know of any script or hack to tell if it's a real person browsing the site/app? If not, I'm going to build it.

hcaptcha

**Comment by paulshorey** [comment]
Ooh! Thanks! They have an "invisible" mode now. That's new.
https://docs.hcaptcha.com/invisible/

**Comment by shagimuratov** [comment]
Try https://cleantalk.org. It is completely invisible and doesn't fire any confirmation requests (bot/human) for the visitors.

**Comment by paulshorey** [comment]
Thanks. Cleantalk.org looks great for PHP websites. But I was hoping for an
invisible captcha alternative like Google's, JavaScript, for any site, that
monitors if the user scrolls naturally and clicks things, or if likely an
automation calling events rather than actually clicking.

**Comment by harshagarwal00** [comment]
Guys does ReCaptcha Enterprise help in any way?

**Comment by sitefinitysteve** [comment]
I see this is closed now, but is there a resolution? Bots are clearing us with 0.9 with ease, there's ONLY 0.9 scores on the dash.

**Comment by washowasho** [comment]
Hello - Any resolution or advice for this? I am still getting 0.9 as well... no matter what I do.

**Comment by XiaoxiaYao** [comment]
Yeah...I used it on iOS app. Always return 0.9. How to test 0.1?

**Comment by k407** [comment]
Same issue, ReCaptcha Enterprise always returns score 0.8999999761581421

**Comment by DelinWorks** [comment]
I think the good old way of generating deformed characters and asking the user to input those is the best approach

**Comment by yossi-chen** [comment]
Did anyone get around this? Also getting the 0.8999999761581421 score for automated tests

**Comment by scottsus** [comment]
+1 same issue

**Comment by PeterKvayt** [comment]
+1

**Comment by dukedaily** [comment]
+1

**Comment by alexmercerind** [comment]
+1

**Comment by Kevin-Aaaquil** [comment]
+1

**Comment by bermawy-sure** [comment]
+1

**Comment by BrunoRevez** [comment]
+1

**Comment by juniorborelli** [comment]
+1

**Comment by alexandergull** [comment]
Hello everyone in this thread.

Check out the CleanTalk investigation into this long-standing issue.

https://blog.cleantalk.org/researching-the-issue-of-score0-9-in-recaptcha-v3

Hope this helps.

**Comment by arivanandhanc** [comment]
I can test in my dev site I got 0.3
