### ISSUE TITLE
Recaptcha is requesting recaptcha__en.js file multiple times

### ISSUE THREAD

**Issue by Rueff19** [google/recaptcha#236]
Hi there,

I was having this problem with one of my projects and to try to figure out what was wrong I decided to run the example code from recaptcha docs.

Even with this example code the page is still requesting the file multiple times.

Here is a jsFiddle with the example code: https://jsfiddle.net/7h7rnqbn/

Just open the network tab and see the file requests.

**Comment by rowan-m** [comment]
It looks like the widget itself re-uses the `recaptcha__en.js` file. In the network tab you should see different initiators for those requests.

**Comment by sandeepsingh3** [comment]
what is the resolution for this issue ?

**Comment by Rueff19** [comment]
@sandeepsingh3 
Apparently there isn't one....
I waited for so long for a response that I moved on. After a month or two @rowan-m responded. He just stated what I already knew(that is the recaptcha widget that re-uses the file) and closed the issue.

**Comment by Malvoz** [comment]
@rowan-m 
Is that not an issue? Requesting 77.1kb~ several times is obviously redundant.

Testing at https://www.google.com/recaptcha/intro/v3beta.html:<br>
![recaptcha](https://user-images.githubusercontent.com/26493779/44628462-58f12580-a940-11e8-9162-d49e9a463405.png)

**Comment by jj-plane** [comment]
I still get this issue.

**Comment by briedis** [comment]
Still getting the issue. Loading same files 3 times, and each is 250KB unzipped, which is quite a lot!

**Comment by Malvoz** [comment]
This issue may be resolved in https://github.com/google/recaptcha/issues/331.

**Comment by andcha** [comment]
@Malvoz No, this issue has not resolved yet.
On one hand google pagespeed complains of reducing number of request and here recaptcha is unnecessarily adding an extra request for same file.

One request is being initiated by `https://www.google.com/recaptcha/api.js` and another by `https://www.google.com/recaptcha/api2/anchor`

If anyone finds any workaround to this mess then please post here.

**Comment by alonseg** [comment]
this Issue still bothers us and add significant 'drag' to our load time

**Comment by lugus** [comment]
same issue

**Comment by Cooperdale** [comment]
Same here. Very heavy issue, I'll probably get rid of recaptcha for the time being.

**Comment by andcha** [comment]
More than two years have passed and still no solution. What a disappointment this is turning out to be.

**Comment by kenigbolo** [comment]
Any updates to this? Might be good to get some insights if this would be fixed sometime soon or in the distant future

**Comment by jazkh** [comment]
> this Issue still bothers us and add significant 'drag' to our load time

use explicit render method to avoid loading recaptcha during page load.

**Comment by koubinhanz** [comment]
> **@alonseg**
> 
> > this Issue still bothers us and add significant 'drag' to our load time
> 
> use explicit render method to avoid loading recaptcha during page load.

with explicit render the issue is exactly the same. the file (exact content) is downloaded 3 times. I really don't understand this behavior from Google as their from #perfmatters point. very disapointed

**Comment by jbaris** [comment]
I'm facing this issue. Any news?

**Comment by milabron** [comment]
Google imposes how to do things, but even they don't comply. In my village, this is called politics.

**Comment by ThodorisElissaios** [comment]
any news?

**Comment by luiznasciment0** [comment]
+1 :(

**Comment by Nodws** [comment]
use another method, google says its not their problem

**Comment by AndrejGajdos** [comment]
Why was this issue closed?

**Comment by lamka02sk** [comment]
Google really seem to care about performance of our websites.

**Comment by vgstef** [comment]
We also have this issue. What can we do?

**Comment by ansmlc** [comment]
Have the same issue. It has a significant negative impact on performance of our sites. I guess we’ll have to look for alternative solutions. This is not worth it.

**Comment by Malvoz** [comment]
See https://github.com/google/recaptcha/issues/236#issuecomment-544536676.

**Comment by sntgchns** [comment]
c'mon! 50% of website performance is ruined by a script of the best company? Fix that s**t please![https://www.gstatic.com/recaptcha/releases/0hCdE87LyjzAkFO5Ff-v7Hj1/recaptcha__en.js](url)
loads 4 times in my case, the multiple script loads weights 4 times all my website images!!!

**Comment by luxaeter** [comment]
any updates on this issue ![recaptcha js](https://github.com/google/recaptcha/assets/33124659/36e2fed3-0358-4d45-ab4e-0c648da40f76)

**Comment by arifje** [comment]
Still having this issue, loaded 3 times:

![Screenshot 2024-03-06 at 13 47 07](https://github.com/google/recaptcha/assets/1286410/260c4bae-b1c7-41b1-ae8c-71c6a3d5747a)

**Comment by rajparekh07** [comment]
One crazy way to fix this -> Use service worker -> intercept if recaptcha_en.js -> cache it.

Next request -> serve from the cache. 

Since I am sure the request is well versioned, it wouldnt be hard to bust the cache.

**Comment by LevanArabuli** [comment]
same in 2025

**Comment by sntgchns** [comment]
> does anyone has a workaround for this? Nov. 2025

No, you have 2 options: stop using recaptcha using cloudflare's DNS, or delay the script's loading until the moment you load the element you want to protect.

**Comment by rfgonzalezweb** [comment]
>  I used the intersection API to load bine the script only when the input field is in the viewport

I think I will do the same, inject the script only when needed because Lighthouse is complaining badly about the performance of my site.
thank you both @sntgchns @danielghirasim
