### ISSUE TITLE
recaptcha Verify() method returns invalid-input-secret

### ISSUE THREAD

**Issue by engharb** [google/recaptcha#237]
Hello,

I am starting using this lib, and when I submit my form and verify the secret I got always 'invalid-input-secret' ?

Do you have any idea?

**Comment by maxight** [comment]
I encountered the same error and was able to resolve it.
The thing is that you should use two different secret keys, one on the client-side, and another one (not the same) on the server-side.

When you open secret keys in google page (https://www.google.com/recaptcha/admin/site/XXXXXXXXX/setup), then you'll see two keys: first one is for client-side, the second one is for Verify() method on the server-side.

**Comment by gigil-mindcoopers** [comment]
Same for me even using different key one for client side(site key) and other for server verification(secret key). Still I'm getting the error code ['invalid-input-secret']

**Comment by faseelsaeed** [comment]
Maybe a little late to the party. But changing the server side ReCaptcha class  fixed it for me.

Original code
```
public function ReCaptcha ($secret) {
        if ($secret == null || $secret == "") {
            die("To use reCAPTCHA you must get an API key from <a href='"
                . self::$_signupUrl . "'>" . self::$_signupUrl . "</a>");
        }
        $this->_secret=$secret;
}
```

changed to 

```
public function __construct($secret) {
        if ($secret == null || $secret == "") {
            die("To use reCAPTCHA you must get an API key from <a href='"
                . self::$_signupUrl . "'>" . self::$_signupUrl . "</a>");
        }
        $this->_secret=$secret;
       
    }
```

Hope that helps someone.

**Comment by nikleshraut** [comment]
Thanks @faseelsaeed, changing constructor method from same as class to `__construct` solved my problem.

**Comment by jorgedsdias** [comment]
The solution presented by @faseelsaeed works very well. Thanks

**Comment by MarcosBL** [comment]
Thanks @faseelsaeed ! working like a charm !
