### ISSUE TITLE
Broken, doesn't work as a CAPTCHA service and should be removed from internet

### ISSUE THREAD

**Issue by DFNCTSC** [google/recaptcha#240]
For the past year reCAPTCHA has been broken. 9 out of 10 correct CAPTCHA submissions are returned as "Please try again".

Many people have made videos about this but people just roll over and take it.

@rowan-m You really need to fix this.

**Comment by havrancek** [comment]
I´m completely locked out.. for few weeks now, can´t enter anywhere where is recaptcha, because it doesn´t work, i can spend hours clicking and all i can see is "please try again".. i am desperate & resignated, trying to figure out new curses about this "great feature"

**Comment by DFNCTSC** [comment]
@havrancek I knew other people were experiencing this but few will speak out. I know so many other that complain about this in private messages constantly by are afraid of Google.

**Comment by pfurini** [comment]
I second this. Google Recaptcha is completely broken, and should never be used again in production sites. At least it will never be on my sites again.

**Comment by DFNCTSC** [comment]
Will you make any comment about this @rowan-m ? Do you realize that reCAPTCHA thinks semi-trucks are buses? Why it thinks banners or business logos are the same thing as street signs? Will you address the reason why reCAPTCHA has gotten worse over the years -- to the point where it's really not even comparable to competing CAPTCHA services?

This video is comedic in nature but is honest in its point and I think you should check it out if you haven't already:
https://www.youtube.com/watch?v=BVFYFr4Vy8I

**Comment by rowan-m** [comment]
I've been updating this client to support v3 of the API which doesn't rely on presenting challenges, just returns a confidence score for requests. You can see this on the `v1.2` branch in this repo or try it at http://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php

I hope the updates alleviate some of your frustration with the challenges.

**Comment by DFNCTSC** [comment]
Thank you for the reply Rowan. It means a lot. I understand that optical image recognition automation scripts are abound out there and improving just as much as one can fight it but there is no doubt a certain limit of discomfort for users that should be reached and never exceeded. I appreciate any resolution you can provide to our issues. I pine for the days of clicking your CAPTCHAless reCAPTCHA and not seeing any challenges -- especially if you just Turing tested the same machineID 5 times in the last 5 minutes and they always passed.

The link you provided errors [regardless of cookies].

> This page isn’t working
> recaptcha-demo.appspot.com redirected you too many times.
> Try clearing your cookies.
> ERR_TOO_MANY_REDIRECTS

**Comment by rowan-m** [comment]
Sorry, try https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php
I was messing around trying to ensure http → https redirects on AppEngine.

**Comment by DFNCTSC** [comment]
@rowan-m This is what I get whenever I load the page.

`{
  "success": false,
  "hostname": "recaptcha-demo.appspot.com",
  "challenge_ts": "2018-08-02T05:32:16Z",
  "apk_package_name": null,
  "score": 0.1,
  "action": "homepage",
  "error-codes": [
    "score-threshold-not-met"
  ]
}`

**Comment by DFNCTSC** [comment]
@rowan-m Also, this issue shouldn't be closed because nothing has been improved in the release of reCAPTCHA for end-user experience regardless of what changes you may have made.

It still doesn't do what it's main purpose does, anymore. It used to work just fine a few years ago. But you have since then broke it. Try reverting to an old build and you'll see it's a fact.

**Comment by DFNCTSC** [comment]
@rowan-m The latest update has seemed to help a lot in terms of the script actually working but as time goes on it's apparent that it's getting worse -- this is similar to what happened with the previous versions of reCAPTCHA. I mean you are making us work to teach your MLA what is or what isn't a traffic light/crosswalk/bus/stairs/etc but as times goes on it gets less and less accurate which is the exact opposite of what the intention is, right?

**Comment by coupdeforce** [comment]
I'm still told to try again at least twice most of the time.  I just assumed it was a scam to get people to solve more at once.  It used to trust me automatically a lot of times and get checked without solving any, especially after just solving one, but hasn't done that at all in the last few months.  It seems like the focus has been changed to predominantly be for gathering data from the task rather than being an actual reliable captcha service.  If it wants more tasks to be completed then that's fine in itself, but it can't be dishonest about it and say "try again" like the last one was done wrong.  It should be saying something like "good job, now please solve another one" in those cases, if it is indeed simply requiring more tasks and not incorrectly validating submissions.

**Comment by DFNCTSC** [comment]
@rowan-m Reference for issue https://github.com/google/recaptcha/issues/370 It's back.

@coupdeforce Yep. The algorithm that controls the confidence metric has been ran astray, probably due to the huge increase of users due to COVID-19. You're not the only one that's experiencing constant issues.

**Comment by Geolim4** [comment]
@rowan-m Same here, I'm getting asked at least two times to try again before being accepted.
This is issue is getting seriously annoying for end-users :/

**Comment by SpeedyCraftah** [comment]
I've also noticed if you solve captcha multiple times, let's say 5x in an hour, captcha will start thinking you're a bot and giving you almost impossible puzzles, sometimes it even pops up with "your computer may be sending automated queries" and not allow me to solve captchas for a few hours.
