### ISSUE TITLE
Sign View is badly broken

### ISSUE THREAD

**Issue by bgspence** [google/recaptcha#241]
The Street View reCAPTCHA will usually refuse to provide a Verify button, but just Next. If the Verify button appears, he only selection that once worked was for 4 vertical squares. Now, that always fails.

The audio reCAPTCHA insists that I am "sending automated queries." This might be because when the Next button appears I just quickly select one square and try the next image.

I'm using the current mac version of Safari.

![image](https://user-images.githubusercontent.com/41170559/42934996-63cc4ad6-8afd-11e8-92be-a2b1c81bde28.png)

**Comment by bgspence** [comment]
If the user fails with one style like Street View switch to Store Fronts next

This is ridiculous...
![image](https://user-images.githubusercontent.com/41170559/42935540-bade96c0-8afe-11e8-9470-759d28352b27.png)

**Comment by pfurini** [comment]
Same experience for me. I already make several sites remove recaptha from their registration forms, because it was impossible for me, and a ton of other users, to successfully complete the verification process.
As already stated in another issue, I already lost my trust in this service, and I can't use it on my sites if that means losing potential acquisitions.

**Comment by rowan-m** [comment]
These are issues with the reCAPTCHA service itself rather than the client library, which is what this repo focuses on. There are additional support options at https://groups.google.com/forum/#!forum/recaptcha that may be more appropriate for you.

**Comment by pfurini** [comment]
@rowan-m Ok, that's fair and makes sense.
But please consider (you or another project lead) adding this hint to the README file also.
Every relevant google search on this kind of issues can potentially lead to this repo, and that's a source of confusion.

Regards,
P.F.

**Comment by rowan-m** [comment]
I'm working through a number of updates at the moment to bring in the v3
support, so I'll also take this on board and make the documentation more
informative along with providing an issue template. Thanks for the
suggestion.

**Comment by bgspence** [comment]
That link is useless. That’s why I had to try somewhere, anywhere else. Do you have a useful link to solving the f’d up loops you can get into? Implementers need to monitor how many times a user gets failed by Google and either give them another way to pass, or use another human check as an alternative. Simply check the times Google fails a user, if it seems like a human pattern then pass the person. Google in not always right. This was not written by a bot.

**Comment by bgspence** [comment]
This needs reopening. See my other message.
