### ISSUE TITLE
ReCaptcha V3 score is static

### ISSUE THREAD

**Issue by sliterok** [google/recaptcha#243]
Re-opening #235 
Probmel wasn't that the score is 0.9 and not 1.0, problem is that score is STATIC.
It never changes.

**Comment by rowan-m** [comment]
I'm updating the `v1.2` branch to make use of the v3 API clearer. From your own machine, it can be challenging to get different scores. Try having a look at https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php

If I run that on my phone in my normal browser and connections I get:
```json
{
  "success":true,
  "hostname":"recaptcha-demo.appspot.com",
  "challenge_ts":"2018-08-01T09:35:26Z",
  "apk_package_name":null,
  "score":0.9,
  "action":"homepage",
  "error-codes":[]
}
```

If I then switch to incognito mode and connect to a VPN through Turkey, I get:
```json
{
  "success":false,
  "hostname":"recaptcha-demo.appspot.com",
  "challenge_ts":"2018-08-01T09:36:31Z",
  "apk_package_name":null,
  "score":0.1,
  "action":"homepage",
  "error-codes":[ "score-threshold-not-met"]
}
```

If you have enough traffic through your site, then you can also check https://www.google.com/recaptcha/admin which will show you the distribution of scores for your key.

**Comment by HazCod** [comment]
@rowan-m so I get score 0.3 on a regular macOS Mojave+Safari (uBlock origin+1password), while logged into my google account. Ideas?
