### ISSUE TITLE
Fallback style Recaptcha not firing callback.

### ISSUE THREAD

**Issue by Mlong2177** [google/recaptcha#246]
Hello,

On my application, the submit button is disabled until the captcha is solved.  (Don't worry, there's ALSO back end validation)

However, it has come to my attention that visitors on a 56k modem will often meet the 'fallback' style captcha.

This fallback style captcha doesn't seem to fire a callback, and thus the submit button is never enabled.

Please see #63 for an old report.

Here is a code snippet to reproduce the issue.  (written by @defualt)
```
<script>
        function recaptcha_callback (){
            console.log('RECAPTCHA CALLBACK!!',arguments);
        }
    </script>
    <script src="https://www.google.com/recaptcha/api.js?fallback=true" async defer></script>
    <div class="g-recaptcha" data-sitekey="KEYKEYKEYKEY" data-callback="recaptcha_callback"></div>
```

As you can see, the recaptcha_callback is never called.

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
