### ISSUE TITLE
IE 11 invisible Recaptcha - Object expected

### ISSUE THREAD

**Issue by andrejGasparAccenture** [google/recaptcha#251]
Invisible Recaptcha is not working properly on IE 11. When you initialize recaptcha, browser will return error after a while with console log 'Object expected'. Looks like the variable is a string instead of object.

This is happening only on IE browser, other browsers are ok. please check the attachments.

Any suggestions?

![recap](https://user-images.githubusercontent.com/42602309/44449489-92e3c400-a5ee-11e8-8bb9-8eb3dc36895a.PNG)
![captchaobj](https://user-images.githubusercontent.com/42602309/44449495-9aa36880-a5ee-11e8-8384-848584790139.PNG)
![captchaund](https://user-images.githubusercontent.com/42602309/44449499-9c6d2c00-a5ee-11e8-8936-7854b05ad1a1.PNG)

**Comment by youpixxl** [comment]
Same issue, only on IE. Any workaround ?

**Comment by Shivansh-Bajaj** [comment]
Same issue, Do we have any solution?

**Comment by ybelenko** [comment]
Same with standard reCaptcha2(not invisible). Any workarounds?

**Comment by pctimhk** [comment]
Same issue. Any updates?

**Comment by miantosca** [comment]
Has anyone successfully resolved this or found a work around?

**Comment by atoupet-toki** [comment]
up?

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
