### ISSUE TITLE
AJAX Integration 

### ISSUE THREAD

**Issue by c0fe** [google/recaptcha#256]
Is this client workable with AJAX forms? If so, any examples of implementation?

**Comment by rowan-m** [comment]
There are a number of choices here.

You can look at the v3 example where the reCAPTCHA request is entirely separate from any user interaction.
https://github.com/google/recaptcha/blob/master/examples/recaptcha-v3-request-scores.php
https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php

You can see examples here on how to programmatically invoke the challenge in v2
https://developers.google.com/recaptcha/docs/invisible#explicit_render

Finally, this client library just processes the response string from the reCAPTCHA service. By default in v2 that comes back as an additional field in the form response, but you can see the other methods here:
https://developers.google.com/recaptcha/docs/verify
