### ISSUE TITLE
The captcha error message is truncated

### ISSUE THREAD

**Issue by SammiJC** [google/recaptcha#261]
**Issue description**
When you validate the captcha and leave it to expire the error message appears truncated
![image](https://user-images.githubusercontent.com/2851720/45615416-b4f52880-ba6c-11e8-9b21-04e9e93ad103.png)

**Environment**
Live and Development environment

 * OS name and version: Windows 10
 * Browser name and version: Chrome Version 69.0.3497.92

**Reproducing the issue**
https://anuas.associationadmin.org/ContactUs/index/portal/organization
  
  ***User steps***
1. Click on link
2. Check: I am not a robot
3. Switch the tab so the website is not visible
4. When you go back to the inactive page the captcha error will be truncated

**Comment by umeshpatadiya** [comment]
Getting same issue :(

**Comment by OlegKozlovskui** [comment]
Could you please fix this issue?

**Comment by abenjamin765** [comment]
+1

**Comment by haydenkshaw** [comment]
+1 still an issue

**Comment by susingh** [comment]
+1 this is still an issue, could we please fix this?

**Comment by Yaolegol** [comment]
still

**Comment by milix2019** [comment]
any fix for this yet?

**Comment by qiqqq** [comment]
+1

**Comment by milix2019** [comment]
I had this issue when it expires and give that error message. I did a workaround but still is not the best solution. I have added the onExpired function and when it fires, I increased the height like so. Hope it helps anyone out there.


  <ReCAPTCHA
    onExpired={() => this.onExpired()}
    ref={this.recaptchaRef}
  />

 onExpired() {
    //  I am refering to the ReCAPTCHA  iframe 
    const frameElement = document.getElementsByTagName('iframe');
    if (frameElement && frameElement[0]) {
      setTimeout(() => {
        frameElement[0].height = 100;
      }, 500);
    }
  }

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
