### ISSUE TITLE
[Deprecation] 'webkitURL' is deprecated. Please use 'URL' instead.

### ISSUE THREAD

**Issue by kkimdev** [google/recaptcha#263]
When recaptcha__en.js is loaded on Chrome, it gives the following warning

```
[Deprecation] 'webkitURL' is deprecated. Please use 'URL' instead.
```

It looks like recaptcha__en.js uses `window.webkitURL`.  I think a common practice for handling this is doing `window.URL || window.webkitURL` instead.

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
