### ISSUE TITLE
reCAPTCHA v3 Beta has redundant "Privacy" and "Terms" links in the source code

### ISSUE THREAD

**Issue by imranalikhaja** [google/recaptcha#266]
**Issue description**
There are redundant "Privacy" and "Terms" links in the DOM and this leads repeating the links for screen reader users in the list of links. 

**Environment**
Live and Development environment.

 * OS name and version: Windows 10 Enterprise
 * `google/recaptcha` version: v3 Beta
 * Browser name and version: Chrome Version 69.0.3497.92 (Official Build) (64-bit)

**Reproducing the issue**

  * URL (optional): 
https://www.google.com/recaptcha/intro/v3beta.html

  * Code (optional):
```
<div class="rc-anchor-normal-footer"><div class="rc-anchor-logo-large" role="presentation">
<div class="rc-anchor-logo-img rc-anchor-logo-img-large"></div>
</div><div class="rc-anchor-pt">
<a href="https://www.google.com/intl/en/policies/privacy/" target="_blank">Privacy</a>
<span aria-hidden="true" role="presentation"> - </span>
<a href="https://www.google.com/intl/en/policies/terms/" target="_blank">Terms</a>
</div>
</div>
<div class="rc-anchor-invisible-text">
<span>protected by <strong>reCAPTCHA</strong></span>
<div class="rc-anchor-pt">
<a href="https://www.google.com/intl/en/policies/privacy/" target="_blank">Privacy</a>
<span aria-hidden="true" role="presentation"> - </span>
<a href="https://www.google.com/intl/en/policies/terms/" target="_blank">Terms</a>
</div>
</div>
  
```
  ***User steps***

1. Visit page https://www.google.com/recaptcha/intro/v3beta.html
2. Inspect the reCAPTCHA badge on the bottom right corner. OR With screen reader turned on (JAWS), bring up the list of links (Insert + F7).

**Comment by rditulli** [comment]
Is this going to be fixed? The aria-hidden="true" doesn't hide the redundant links from keyboard/screen reader users. They still tab to blank/empty links. It also affects the "submit" button that follows the recaptcha from being announced properly by AT.

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
