### ISSUE TITLE
Cannot authenticate on localhost

### ISSUE THREAD

**Issue by HazCod** [google/recaptcha#267]
**Issue description**
I am using recaptcha v3 with clientside + backend PHP verification.

**Environment**
PHP 7.2

 * OS name and version: alpine linux 3.8
 * PHP version: 7.2
 * Web server name and version: nginx
 * `google/recaptcha` version: 2.1 latest
 * Browser name and version: safari macos 12.0

**Reproducing the issue**
I am using a recaptcha v3 where the domain is set to 'localhost'.
I am accessing the website on https://localhost/
I am logged in to my google account.
  
  ***Logs***
```
 Checking 'login/login' with minimum score 0.5 and timeout 120

...

Failed captcha, reason: score-threshold-not-met with score 0.1
```

**Comment by HazCod** [comment]
Hi @rowan-m , I always receive a score of 0.1 regardless of running locally (localhost) or more representative when hosted on a provider. (xxx.host.com)

Is there any way to debug -why- I received that score?

**Comment by rowan-m** [comment]
I really wouldn't focus on the score you're getting on a developer machine. From https://developers.google.com/recaptcha/docs/v3 
> reCAPTCHA adapts to your use cases by seeing real traffic on your site. For this reason, scores in a staging environment may differ from production.

As a developer, your usage of the site is unlikely to match a normal user. If you need specific scores in a dev / staging environment I would strongly suggest creating a mock service that you can use that will return predictable scores for you.

**Comment by HazCod** [comment]
I am having the same issue in production by the way. :-)

**Comment by rowan-m** [comment]
Closing this off since it's related to scores returned by the service. You need to focus on looking at your overall scores per action in https://www.google.com/recaptcha/admin and create a mock service if you need predictable responses in another environment.
