### ISSUE TITLE
Low Score

### ISSUE THREAD

**Issue by MeinPseudonym** [google/recaptcha#271]
My reCaptcha Score when logged into my Google Account in Chrome is 0.1, when i use Incognito Window 0,7 and when i use Firefox, that I never use normally 0.9 ....

https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php

That's not normal, isn't it?

**Comment by rowan-m** [comment]
The scores returned on the example site are not representative of what you would get in a full production site. You should refer to your [dashboard in the admin interface for your site](https://www.google.com/recaptcha/admin) to see your distribution of scores and adjust the threshold accordingly.
