### ISSUE TITLE
I have a question regarding to recaptcha badges

### ISSUE THREAD

**Issue by HauenJeong** [google/recaptcha#277]
Hello I am currently applying your service to our website. Everything is good using recaptcha, however, I wonder is there any problem or abuse of term of service that hide recaptcha badges? Please tell me to apply correctly!

Thank you!

**Comment by rowan-m** [comment]
The reCAPTCHA overlay should appear when you load the script. Can you provide some specific details as to exactly what's happening or a link to some code demonstrating the problem?

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
