### ISSUE TITLE
Uncaught (in promise) Timeout Error (Updated 10/25/2018)

### ISSUE THREAD

**Issue by hasanalizxc** [google/recaptcha#278]
Dear Google Family and Github Users,

I was entering letgo website until yesterday. There is no error until yesterday. When i try to enter login page i am writing my credentials and click Login button but i am taking this error since 2 days. And i couldn't solve this. My OS Windows 7. My Chrome version is 70.0.3538.77 (latest). My Java version is Version 8 Update 191 (build 1.8.0_191-b12).

When i click login button i am taking this error in Console and pop-up is coming up and i am selecting correct pictures from chart and when i press OK, taking same error as like below (uncaught in promise timeout).

I tried to login with Firefox on Windows but result is same as Chrome and same error.
EDIT2: I tried with portable web browsers (Chromium, Maxthon, Falkon, Iron, Qupzilla) but result is same error like below.

I realized one more error like this:

The FetchEvent for "https://tr.letgo.com/tr" resulted in a network error response: the promise was rejected.

`2bouncer.letgo.com/api/authentication?include=user,user_accounts:1 POST https://bouncer.letgo.com/api/authentication?include=user,user_accounts 424 (Failed Dependency)
tr:3 Uncaught (in promise) timeout

  | nrWrapper | @ | tr:3
-- | -- | -- | --
  | Promise.then (async) |   |  
  | nrWrapper | @ | tr:3
  | setTimeout (async) |   |  
  | nrWrapper | @ | tr:3
  | D | @ | recaptcha__tr.js:105
  | (anonymous) | @ | recaptcha__tr.js:317
  | nrWrapper | @ | tr:3
  | r | @ | tr:3
  | gL | @ | recaptcha__tr.js:316
  | NY | @ | recaptcha__tr.js:505
  | QU | @ | recaptcha__tr.js:516
  | lz.LP | @ | recaptcha__tr.js:508
  | f9 | @ | recaptcha__tr.js:507
  | t.reset | @ | recaptcha.js:55
  | t.componentWillUnmount | @ | recaptcha.js:107
  | ui | @ | react-dom.production.min.js:172
  | ci | @ | react-dom.production.min.js:176
  | fa | @ | react-dom.production.min.js:211
  | ca | @ | react-dom.production.min.js:205
  | la | @ | react-dom.production.min.js:204
  | Di | @ | react-dom.production.min.js:200
  | enqueueSetState | @ | react-dom.production.min.js:130
  | b.setState | @ | react.production.min.js:13
  | (anonymous) | @ | AuthContainer.jsx:86
  | nrWrapper | @ | tr:3
  | Promise.then (async) |   |  
  | nrWrapper | @ | tr:3
  | (anonymous) | @ | AuthContainer.jsx:84
  | (anonymous) | @ | Login.jsx:253
  | (anonymous) | @ | Login.jsx:107
  | ro | @ | react-dom.production.min.js:125
  | no | @ | react-dom.production.min.js:125
  | fa | @ | react-dom.production.min.js:214
  | ca | @ | react-dom.production.min.js:205
  | la | @ | react-dom.production.min.js:204
  | va | @ | react-dom.production.min.js:216
  | Cn | @ | react-dom.production.min.js:85
  | nrWrapper | @ | tr:3
`

**P.S: I can login my account on Linux machine with Firefox without any problem.**

Could you please help me about this issue?

Thanks in advance.

Best Regards.

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
