### ISSUE TITLE
No Analytics on reCAPTCHA Admin

### ISSUE THREAD

**Issue by gilmorem560** [google/recaptcha#283]
Good afternoon, my organization recently implemented reCAPTCHA v3 for a few forms on our website, and while all the code pipelines appear to be working, we're getting absolutely no analytics via the admin panel. The section of the window where analytics would appear simply shows:

"Note: The scores for this site may not be accurate before running with sufficient live traffic. Please see our developer site for more information."

I was hoping to look into the analytics to begin developing our score behaviors, but currently I'm finding no way to do this through the admin panel. I'm considering capturing the score returned by siteverify and cataloguing it with the form responses anyway for simplicity, but is there any extra step we need to be able to monitor metrics via the admin panel?

**Comment by marcotibben** [comment]
I had that here for a couple of days too, but now analytics do start coming in (after about 3 days).. BUT; I use actions everywhere in the code, but there is no action analytics showing up in the admin whatsoever.. it's exactly one week after creating the key now..

**Comment by gilmorem560** [comment]
If it's any help, the information is coming in properly with the JSON response from siteverify, so we are able to catalogue scores with responses and have been keeping our own metrics, but the Google-side application does not appear to be working. I've noticed that very briefly, something does try to load:

![image](https://user-images.githubusercontent.com/36053668/48567550-20634700-e8b2-11e8-800b-bc274a83bd9d.png)

An Analytics section will pop up with a date selector, but it then disappears completely and is replaced with the message I listed above.

**Comment by AkshayBaldia** [comment]
I too faced the issue

**Comment by vonbv** [comment]
We are encountering the same issue. Debugging the code shows a successful server validation and we can get the score.  However, nothing is logged on the admin panel.

**Comment by Anastasiya888** [comment]
We have the same issue and we are sending a lot of requests.

**Comment by goalie7960** [comment]
Is this still an issue?

I'm getting data in the # of requests and score distribution panels (although delayed), but nothing in "Top 10 actions" or "Top 10 suspicious traffic actions".

![image](https://user-images.githubusercontent.com/162022/53021747-e57c2c80-3427-11e9-85db-a9cff4dcfb2a.png)

**Comment by chandangarg** [comment]
I am getting same issue as above.
Everything configured properly and data in the number of requests and score distribution, but nothing in "Top 10 actions" or "Top 10 suspicious traffic actions". let me know if we have any specific solution.
Thanks
![recaptcha-admin](https://user-images.githubusercontent.com/6594352/53472514-cddb1e80-3a8d-11e9-890c-e67d8aceb8a8.png)

**Comment by PowerlessCube** [comment]
> I am getting same issue as above.
> Everything configured properly and data in the number of requests and score distribution, but nothing in "Top 10 actions" or "Top 10 suspicious traffic actions". let me know if we have any specific solution.
> Thanks
> ![recaptcha-admin](https://user-images.githubusercontent.com/6594352/53472514-cddb1e80-3a8d-11e9-890c-e67d8aceb8a8.png)

Same issue, we are looking to implement version 3 and I'm seeing a similar view in my reCaptcha analytics graphs.  I don't see metrics on actions.

**Comment by goalie7960** [comment]
For me this problem went away when we deployed to production and waited a few days. I don't know why our dev key didn't work but the prod one seemingly did.

**Comment by pankajjain1** [comment]
We also implemented reCAPTCHA v3 and seeing only one action not all action in our QA environment.WE want to validate before going to production.Anybody knows the issue?
![reCAPTCHA](https://user-images.githubusercontent.com/10199740/60689811-c930d780-9e7e-11e9-92b0-e7c17f470b23.png)

**Comment by Connum** [comment]
Good to know I'm not the only one having this issue. But unbelievable that there hasn't been any response from Google or a solution in over half a year...

**Comment by pankajjain1** [comment]
> Good to know I'm not the only one having this issue. But unbelievable that there hasn't been any response from Google or a solution in over half a year...

I contacted recaptcha support and they confirmed because of low traffic in lower environments all actions are not showing

**Comment by antonio-petricca** [comment]
Same issue for me!

**Comment by rlewis2013** [comment]
@pankajjain1 How did you contact support for Google reCaptcha? Do you have an email address or contact page that you can share the link to? Thanks, Robert

**Comment by reneebeling** [comment]
@pankajjain1 Did they say, how much traffic do you need to see the top 10 actions? Thanks a lot. 👍  Rene

**Comment by Kimtn129** [comment]
Same issues for me! Getting this meesage from recaptcha admins dashboard _"Note: The scores for this site may not be accurate before running with sufficient live traffic. Please see our developer site for more information.". So anyone can tell me about how much traffic that needed to show the correct Total request and top 10 actions?

**Comment by monokee** [comment]
Same issue here. Still...........

**Comment by kevinlonigro** [comment]
Same issue across all environments: development (most activity), staging and production (least)

**Comment by yumindeckard** [comment]
> > Good to know I'm not the only one having this issue. But unbelievable that there hasn't been any response from Google or a solution in over half a year...
> 
> I contacted recaptcha support and they confirmed because of low traffic in lower environments all actions are not showing


https://medium.com/@steve.yegge/dear-google-cloud-your-deprecation-policy-is-killing-you-ee7525dc05dc

**Comment by adchsm** [comment]
We're experiencing this issue too, on multiple domains/environments, and even in environments where we have automated testing running hundreds if not thousands of tests nightly.

We have approx 10 forms each with a unique action, and only 2 are showing up in the reCAPTCHA dashboard. The forms all re-use the same execution code, so we're sure it's working as we are obtaining our tokens, scores, and some info in the dashboard.

Does anyone know what qualifies as sufficient traffic?

**Comment by MonDeveloper** [comment]
Same issue here.
More than 2 years and this issue is still open with no solution, no workaround and no possibility to involve Google Support.

Please Google, don't become the next "Old Microsoft" :-)

![image](https://user-images.githubusercontent.com/5941887/102789114-f9867180-43a3-11eb-8ba8-b6bddf0c343c.png)

**Comment by Connum** [comment]
> Please Google, don't become the next "Old Microsoft" :-)

Honestly, I don't expect anything good from Google anymore and am in the process of switching all Google services that I use to something else and sell the Google devices that I own...

**Comment by tomtam6** [comment]
Has any one been successful with registering Actions activity in the admin panel?

**Comment by sayamfresco** [comment]
Why can't show any captcha verification record on analytics.

**Comment by nokibsarkar** [comment]
After 3 years, still the same issue

**Comment by bmatthewshea** [comment]
After 4 years, still the same issue 
"No Data"


![no_data_under_recaptcha_admin](https://user-images.githubusercontent.com/984097/153632459-4b854940-ff83-49bb-a882-34fb423b9e98.jpg)

**Comment by Connum** [comment]
Google doesn't care. They're no longer the good ones. Ever since they focus on "doing the right thing", they seem to only do what's right for them and their profit. Time to look for an alternative!

**Comment by shawn-eary** [comment]
> Same issue here. More than 2 years and this issue is still open with no solution, no workaround and no possibility to involve Google Support.
> 
> Please Google, don't become the next "Old Microsoft" :-)
> 
> ![image](https://user-images.githubusercontent.com/5941887/102789114-f9867180-43a3-11eb-8ba8-b6bddf0c343c.png)

Honestly, at this point, I'd like to see Microsoft offer a reCAPTCHA alternative that is backed by Azure.

**Comment by ogmo0n** [comment]
Was dealing with this today myself. Outside of this issue, the admin console leaves a lot to be desired. It really feels like I would be better off logging everything myself like someone above said they do. This admin console is kind of a turd compared to what they offer for ads.

**Comment by SergeyXXI** [comment]
How many requests should be, to be displayed in captcha statistics?

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
