### ISSUE TITLE
Origin not allowed!

### ISSUE THREAD

**Issue by zertex** [google/recaptcha#284]
**Issue description**
Every page of website show alert dialog "Origin not Allowed!" onload.
Even so reCaptcha3 still works.
How I can fix it?

All work perfectly only on subdomains...

I disable origin checking, but problem persists

 * OS name and version: CentOS7
 * PHP version: PHP 7.1
 * Web server name and version:  Apache/2.4.6
 * `google/recaptcha` version: 3
 * Browser name and version: Chrome last, Firefox last

**Reproducing the issue**
I don't know how reproduce issue... I did everything by examples

**Comment by HoshiYamazaki** [comment]
How did you fix that issue?

**Comment by zertex** [comment]
That was my mistake... My js code fired this alert. I am use Window.postMessage(), and forgot fill origin
