### ISSUE TITLE
Recaptcha fails inside google chrome when using Django Recaptcha Ajax

### ISSUE THREAD

**Issue by PSzczepanski1996** [google/recaptcha#288]
https://github.com/praekelt/django-recaptcha/issues/162
I know it's not directly releated to this project since it's package maintainer problem, but maybe somebody have an idea how to fix that.

What I got while using AJAX (everything when I don't use AJAX requests "just works") is:

> Uncaught DOMException: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame.
>     at RR.wE.xl (https://www.gstatic.com/recaptcha/api2/v1542004393985/recaptcha__pl.js:529:376)
>     at ml (https://www.gstatic.com/recaptcha/api2/v1542004393985/recaptcha__pl.js:533:272)
>     at Object.init (https://www.gstatic.com/recaptcha/api2/v1542004393985/recaptcha__pl.js:542:44)
>     at https://www.google.com/recaptcha/api2/bframe?hl=pl&v=v1542004393985&k=6Ley7XsUAAAAAOkmsN1CVThsgorMxXLI7eqLc_Sp&cb=jhtqelkyq62o:184:30

And it's inside recaptcha__pl.js file at line 529, so I am not sure if it's really python package problem.
Any ideas how to resolve that issue?

**Comment by HoshiYamazaki** [comment]
And yes, I use it inside bootstrap modal.

**Comment by ammmmb** [comment]
fuck you! google recaptcha!

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
