### ISSUE TITLE
Multiple requesting of style and javascript

### ISSUE THREAD

**Issue by epcgrs** [google/recaptcha#290]
I have 3 recaptchas, but the script is requesting multiple times the same css and js files. I've tried with only one recaptcha but the error remains the same, looking for several people who went through it but no answer.

I'm using
PHP v 7.1

Take a look:
http://prntscr.com/lwyhbr

**Comment by k2xl** [comment]
seeing this issue too. seems wasteful that it's requesting the same file over and over

**Comment by TripShade** [comment]
This is my temp work around saves at least one trip after the first.

```javascript
workbox.routing.registerRoute(
	/^https:\/\/www.gstatic\.com\/recaptcha\/*/,
	workbox.strategies.staleWhileRevalidate({
		cacheName: 'google-recaptcha',
	})
);
```

**Comment by jasonfedor** [comment]
This file is requested multiple times as it is loaded in different iframe contexts. Note that it is cached, so the browser does not actually fetch it multiple times. In the original screenshot, cache is disabled.
