### ISSUE TITLE
Safety - Time validity

### ISSUE THREAD

**Issue by smohannagaraj** [google/recaptcha#291]
I have a doubt about recaptcha.

I am currently making simple post request to recaptcha server and check success is true.

Is there any possibility that someone verify recaptcha once and save the response and then he can make POST request to my site?

Clearly, I want to know what is the response for the recaptcha verified before 1 week? (If someone saves the response code and uses every time)

**Comment by smohannagaraj** [comment]
Sorry.  I am unable to explain correctly.  If any one understand this, please briefly comment about my question so that the google employee can find solve my doubt.

**Comment by muliyul** [comment]
No you can't submit the same response twice.

**Comment by ammmmb** [comment]
fuck you! google recaptcha!
