### ISSUE TITLE
safari reCAPTCHA v3 API

### ISSUE THREAD

**Issue by ozturkmuhammed** [google/recaptcha#292]
Google Recaptcha V3 is not working on Safari Browser in iOS devices. Is there any solution for it ? 

https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php

![2018-12-25 18_06_30-recaptcha demo - request scores](https://user-images.githubusercontent.com/10061989/50424086-d9348280-086f-11e9-85f7-66d60e8c710b.png)

**Comment by birdkiwi** [comment]
This is Safari for windows: discontinued, last version: 5.1.7 on May 9, 2012

**Comment by rowan-m** [comment]
As stated in the previous comment, this looks like an unsupported platform.
