### ISSUE TITLE
Captcha redirects user to google.com (iOS)

### ISSUE THREAD

**Issue by lillin** [google/recaptcha#293]
Hi there!
We have contact form with captcha v.2 in our project. When users successfully pass captcha they are redirected to google.com page instead of seeing active "Send" button (it is previously disabled). Issue occurs only on iOS devices and appears occasionally. Searching was showed any results regarding this problem.
Bug was reproduced on iPhone 6S+ (iOS 12.0) Safari.

**Comment by ammmmb** [comment]
fuck you! google recaptcha!

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
