### ISSUE TITLE
Bot in chrome incognito and human in opera browser

### ISSUE THREAD

**Issue by bv-sumit** [google/recaptcha#294]
One of the user when doing the signup from chrome incognito mode the google recaptcha v3 was giving 0.1 score due to which i marked him as a bot. While when the same person signed up through opera browser, the score was 0.7. How to resolve this issue. Also can you state the reason for this.

**Comment by asilva3** [comment]
Same. Incognito (0.1) non-incognito (0.9) but what if real users want to use incognito?

**Comment by ammmmb** [comment]
fuck you! google recaptcha!

**Comment by rowan-m** [comment]
Unrelated to client.
