### ISSUE TITLE
reCAPTCHA scrolling to bottom of pagg

### ISSUE THREAD

**Issue by SumitShitole** [google/recaptcha#298]
After clicking I am not a robot and image verification it will navigate to end of the page on iPhone 8.

**Comment by ammmmb** [comment]
fuck you! google recaptcha!

**Comment by pldilley** [comment]
I'm observing the same bug.

Device: iPhone 7 Plus, iOS 12.4
Browser: Safari 12.1
Url: https://www.bell.ca/Fibe-TV

Steps:
1. Go to above Url
2. Click "Check availability" or "Check another address"
3. Type in "55 Lisgar" into the search box
4. A list of results for Toronto, ON should appear as you type
5. Select the corresponding option (was second for me)
6. Wait until recaptcha pops up
7. Observe that the Verify button is inaccessible
8. Try to scroll, and observe that this doesn't work with recaptcha

Expected result: Verify button and accessibility controls are reachable
Actual result: The controls are below the fold, blocking user from being able to continue on the site.

Screenshot:
![2236D097-B2DA-4F2C-8619-41D3F875C519](https://user-images.githubusercontent.com/5225644/63484260-ffe1a200-c46c-11e9-89a5-f5d25b044462.png)

P.S. @SumitShitole Would it have killed you to at least add a few details 😝

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
