### ISSUE TITLE
Inconsistent behavior on recaptcha anchor mouseover

### ISSUE THREAD

**Issue by Malvoz** [google/recaptcha#299]
When hovering the recaptcha anchor, the behavior differs when hovering from the top-side vs hovering from the left-side as shown below.

![recaptcha issue](https://user-images.githubusercontent.com/26493779/54080117-6ae95300-42e9-11e9-8188-d5d93c20c973.png)

Script loaded:
https://www.gstatic.com/recaptcha/api2/v1551681158638/recaptcha__sv.js

I presume this isn't the expected behavior.

**Comment by ammmmb** [comment]
fuck you! google recaptcha!

**Comment by Malvoz** [comment]
Can't reproduce this anymore.
