### ISSUE TITLE
is the .ready() function available in V2?

### ISSUE THREAD

**Issue by marcodeka** [google/recaptcha#301]
Hi, to be sure and to prevent issues, I would like to know if the .ready() function is public and working in the Recaptcha VS library?
Thank you

**Comment by rowan-m** [comment]
Sorry, it's been a while since I've looked at the v1 API to remember what the `.ready()` function did exactly. It sounds like the `onload` callback is what you're looking for.

```html
<script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit" async defer>
<script type="text/javascript">
var onloadCallback = function() {
  // do what you need when the reCAPTCHA library is loaded
};
</script>
```
