### ISSUE TITLE
Example missing, please add 

### ISSUE THREAD

**Issue by venkymadurai** [google/recaptcha#309]
**Issue description**
Hello: recaptcha-v3-request-scores.php refers to examples/v3scores. I guess this is to get the token. But in the "examples" directory, there is neither any  file called "v3scores" nor any directory with the same name.

Can you please add this example, for the sake of completeness?

Thanks for this fantastic contribution!!!!

**Comment by rowan-m** [comment]
Hi @venkymadurai thanks for reporting. The `examples/v3scores` string is just a tag for the action, rather than a link to a specific URL. I'm updating the example to make this clearer.

**Comment by rowan-m** [comment]
Hopefully this should be clearer now
https://github.com/google/recaptcha/blob/master/examples/recaptcha-v3-request-scores.php#L45
