### ISSUE TITLE
Noticed exception 'ErrorException' with file_get_contents

### ISSUE THREAD

**Issue by vitorloureiro** [google/recaptcha#310]
**Issue description**
The PHP file_get_contents throws one exception in case of failure and that should be documented in the docblock of the public submit method.

Example of error : 
ErrorException: Noticed exception 'ErrorException' with message 'file_get_contents(https://www.google.com/recaptcha/api/siteverify): failed to open stream: HTTP request failed! ' in /app/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php:72 

    /**
     * Submit the POST request with the specified parameters.
     *
     * @param RequestParameters $params Request parameters
     * @return string Body of the reCAPTCHA response
     */
    public function submit(RequestParameters $params)

should be 

    /**
     * Submit the POST request with the specified parameters.
     *
     * @param RequestParameters $params Request parameters
     * @return string Body of the reCAPTCHA response
     * @throws ErrorException in case of failure connecting to google
     */
    public function submit(RequestParameters $params)

**Comment by rowan-m** [comment]
@vitorloureiro Thanks for reporting. It looks like `ErrorException` is a result of converting errors to exceptions rather than an issue in the library, see: https://www.php.net/manual/en/class.errorexception.php

**Comment by vitorloureiro** [comment]
But I think the exception should be present in the docblock, because it happens in case of connection failure.
