### ISSUE TITLE
recaptcha V2 checkbox is not visible in high contrast mode

### ISSUE THREAD

**Issue by mattbrough** [google/recaptcha#311]
**Issue description**

In Windows high contrast mode, the recaptcha V2 checkbox is not visible in Internet Explorer 11.

Although users can click the label text, there is no indication of status (spinner, checkmark) and no affordance to indicate to new users that the content is a checkbox.

![image](https://user-images.githubusercontent.com/15336790/57523855-7698da80-7369-11e9-9e3d-d41546388e24.png)

**Environment**

 * OS name and version: Windows 10
 * Browser name and version: Internet Explorer 11

**Reproducing the issue**

  * URL (optional): https://www.google.com/recaptcha/api2/demo
  
  ***User steps***

1. Enable Windows high contrast mode (settings > High Contrast > Use high contrast)
2. Visit page in Internet Explorer 11
3. Observe that checkbox is not visible.

**Note**

Setting z-index >0 for recaptcha-checkbox-border div shows the checkbox border; however the spinner and checkmark are CSS background images which are also not shown in Windows high contrast mode. 

```
.recaptcha-checkbox-border {
    z-index: 1;
}
```

**Comment by ammmmb** [comment]
fuck you! google recaptcha!

**Comment by mattbrough** [comment]
Thank you for that insightful comment.

**Comment by srinivasch29** [comment]
I too faced the same issue in both IE11 and firefox browsers, spent considerable amount of time to fix it but couldn't fix it.

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
