### ISSUE TITLE
Android recaptcha v2 scores nearly 0 recently

### ISSUE THREAD

**Issue by qyzhaojinxi** [google/recaptcha#317]
**Issue description**

Android recaptcha v2 scores nearly 0 recently. It always scored 0.79 before. It happened about 5.21.2019. Can you tell me what's happended?

**Environment**

Google recaptcha v2 on android app

**Comment by ammmmb** [comment]
fuck you! google recaptcha!

**Comment by rowan-m** [comment]
Unrelated to client.
