### ISSUE TITLE
Google ReCaptcha Verification Bug In The Current Year of 2019

### ISSUE THREAD

**Issue by KrowofAgony** [google/recaptcha#319]
I hope that everyone has a Great Fourth of July if you are in the US! What better way to start this off by VERIFICATION! There is a verification bug in the current version of ReCaptcha that pissed me the fuck off. Thus, I took screen caps of this verification bug. Google, you are a multi-billion dollar corporation and your ReCaptcha service has this verification bug. It's pathetic, really, that this bug exists and it HAS NOTHING TO DO WITH MY BROWSER AND ITS SETTINGS. Here are the attached images, enjoy it and have a Great Fourth of July!
![recaptchasucks01](https://user-images.githubusercontent.com/7153059/60665329-30746a80-9e32-11e9-9847-a231b2d73184.png)
![recaptchasucks02](https://user-images.githubusercontent.com/7153059/60665341-38340f00-9e32-11e9-8856-bba7af23c213.png)
![recaptchasucks03](https://user-images.githubusercontent.com/7153059/60665349-3d915980-9e32-11e9-87b1-035b3778f7c3.png)
![recaptchasucks04](https://user-images.githubusercontent.com/7153059/60665363-42560d80-9e32-11e9-90b0-f176351e5b31.png)
![recaptchasucks05](https://user-images.githubusercontent.com/7153059/60665366-471ac180-9e32-11e9-8117-98a3fd8eedc6.png)
![recaptchasucks06](https://user-images.githubusercontent.com/7153059/60665377-4b46df00-9e32-11e9-8e2f-855427bda1e1.png)
![recaptchasucks07](https://user-images.githubusercontent.com/7153059/60665389-50a42980-9e32-11e9-993f-01e57f7ea0e3.png)
![recaptchasucks08](https://user-images.githubusercontent.com/7153059/60665398-5568dd80-9e32-11e9-966e-a8e4797fc063.png)
![recaptchasucks09](https://user-images.githubusercontent.com/7153059/60665406-5994fb00-9e32-11e9-941a-343b98f2d832.png)
![recaptchasucks10](https://user-images.githubusercontent.com/7153059/60665411-5e59af00-9e32-11e9-8d42-51d1430b3fe2.png)
![recaptchasucks11](https://user-images.githubusercontent.com/7153059/60665414-6285cc80-9e32-11e9-9583-922a60e5d131.png)
![recaptchasucks12](https://user-images.githubusercontent.com/7153059/60665420-66b1ea00-9e32-11e9-8e88-5f45ba5cad65.png)
![recaptchasucks13](https://user-images.githubusercontent.com/7153059/60665425-6ade0780-9e32-11e9-876d-13f0c76669d4.png)

**Comment by ammmmb** [comment]
fuck you! google recaptcha!

**Comment by rowan-m** [comment]
Unrelated to client.
