### ISSUE TITLE
The CSP example seems out of date

### ISSUE THREAD

**Issue by ayumihamsaki** [google/recaptcha#322]
The CSP example found here: https://github.com/google/recaptcha/blob/master/examples/recaptcha-content-security-policy.php

Why don't you add `strict-dynamic` to the example ?

The example at the moment won't work on some old versions of Safari due to a lack of nonce-support.

Please update the CSP example to work on new and old browsers with the intent of backwards support.

Thanks.

**Comment by rowan-m** [comment]
Good catch, thank you! Will get this updated.

**Comment by ammmmb** [comment]
fuck you! google recaptcha!

**Comment by rowan-m** [comment]
[Added](https://github.com/google/recaptcha/commit/8912a4f19e06b808ab0be9c4f0cafdf40abf689f) and deployed.

**Comment by ayumihamsaki** [comment]
Thanks.
