### ISSUE TITLE
Issue: Evil, Illegal, Anti-Competitive behaviors regarding ReCaptcha.

### ISSUE THREAD

**Issue by bobmcdouble3** [google/recaptcha#324]
Not necessarily an issue with the code, but an issue with your immoral, illegal practices regarding ReCaptcha. 

For a while, I thought I was simply bad at solving captchas. Eventually, I accepted that it's due to my VPN. But in reality, ReCaptcha decides to POINTLESSLY waste your time, if any of these apply to you:

1. You use a VPN, Tor, or for some reason have a non-residential ip address
2. You don't use Chrome
3. You are not signed into Google
4. You use AdBlock, or a similar program
5. You use Privacy Badger, or a similar tracker blocker
6. You use DDG, or an alternative search engine

Personally, all of the above apply to me... It is deterring me from posting comments, reporting users, and doing other actions, on several sites. These practices are anti-competitive. They are deterring free-speech. They can easily be turned into "precision" censorship tools, if not already. In fact, I'd argue the practices are ILLEGAL under U.S. Competition Law. ReCaptcha is EVIL in general.

Perhaps more importantly, ReCaptcha is forcing users into becoming Google slaves. Therefor, further blocking the LAST HOPES of internet anonymity and privacy. With the clever advertising to developers, even "anonymous social media platforms" like 4chan ARE USING RECAPTCHA!

"Easy on humans, hard on bots" is your slogan. Well, I guess I'm no longer a human.

**Comment by ammmmb** [comment]
fuck you! google recaptcha!

**Comment by AnujShr** [comment]
LOL, You don't know how much of Spam messages and post-submission you get without using something like this project, You think it is easy to manage a web app? BOTS SPAMMERS ARE EVIL.

**Comment by rowan-m** [comment]
Unrelated to client.
