### ISSUE TITLE
amp pages recaptcha v3 response grecaptcha and action-xhr. Kindly provide the sample run out of ideal.

### ISSUE THREAD

**Issue by lennex** [google/recaptcha#326]
**Issue description**

**Environment**

 * OS name and version:
 * PHP version:
 * Web server name and version:
 * `google/recaptcha` version:
 * Browser name and version:

**Reproducing the issue**

  * URL (optional): 
  * Code (optional): 
  
  ***User steps***
  
  
    1. Visit page...

**Comment by rowan-m** [comment]
What's missing from the AMP documentation?
https://amp.dev/documentation/examples/components/amp-recaptcha-input/

**Comment by lennex** [comment]
i currently using amp-html, i dont know how to setup recaptcha v3, can you help me?
must amp-html valid
grecaptcha.execute('reCAPTCHA_site_key', {action: 'reCAPTCHA_example_action'});

where should i put the script to enable it to execute?

**Comment by lennex** [comment]
https://amp.dev/documentation/examples/components/amp-recaptcha-input/

I've read this but still dont know how..
