### ISSUE TITLE
LICENSE does not match copyright headers in php files

### ISSUE THREAD

**Issue by fsateler** [google/recaptcha#327]
LICENSE looks like a standard BSD 3-clause license, but the copyright headers look like MIT.

As part of packaging this library for debian, the debian FTP-Master team has requested that this be clarified. Perhaps the headers need to be changed to the BSD text?

**Comment by rowan-m** [comment]
The BSD-3 license is correct, I'll get the inline headers updated and make a point release. Thanks for bringing this up!

**Comment by rowan-m** [comment]
Merged #328 and [released v1.2.3](https://packagist.org/packages/google/recaptcha#1.2.3) to ensure consistent use of BSD 3-clause license everywhere.
