### ISSUE TITLE
Recaptcha v2 js loads multiple times

### ISSUE THREAD

**Issue by farley1122** [google/recaptcha#335]
**Issue description**

recaptcha__en.js loads multiple times on any page using recaptcha v2. This is a small issue when trying to optimize page speed, as with all the reloads it comes to 270KB.

**Environment**

Tested on multiple production, staging, and locally hosted servers using wordpress. 

 * PHP version: 7, 5.6
 * Web server name and version: local, various websites.
 * `google/recaptcha` version: V2
 * Browser name and version: chrome 77.0.3865.90

**Reproducing the issue**

https://patrickhlauke.github.io/recaptcha/

open network tab and see that the js loads multiple times.

**Comment by luisfranco** [comment]
It can be replicated on their own demo as well:
https://recaptcha-demo.appspot.com/recaptcha-v2-invisible.php

And, not only the `recaptcha__en.js` file is being loaded several times, but also their **fonts**:
![Screenshot 2019-10-30 11 44 00](https://user-images.githubusercontent.com/2644324/67883972-a64fc080-fb0a-11e9-8f8d-f17191a8c2bc.png)

**JS:**
![Screenshot 2019-10-30 11 44 23](https://user-images.githubusercontent.com/2644324/67883981-ac45a180-fb0a-11e9-9222-7971bf22fff2.png)

**Comment by jasonfedor** [comment]
reCAPTCHA runs in multiple different frames, which requires resources to be loaded in each. This file is cached heavily though so should require <= 1 network call to load assuming caching is turned on.

**Comment by andcha** [comment]
@jasonfedor regardless of that, it is wrong for someone looking to improve pagespeed score. Even adwords campaigns are costlier when page load speed in slow.

On one hand google pagespeed complains of reducing number of request and here recaptcha is unnecessarily adding an extra request for same file.

One request is being initiated by `https://www.google.com/recaptcha/api.js` and another by `https://www.google.com/recaptcha/api2/anchor`

If anyone finds any workaround to this mess then please post here.

**Comment by sgomes** [comment]
> This file is cached heavily though so should require <= 1 network call to load assuming caching is turned on.

@jasonfedor This is no longer true now that Chrome implements triple-keyed cache partitioning. The file will now be downloaded multiple times, because the various iframes don't share a cache.

I believe this warrants reopening this issue.

**Comment by digiage** [comment]
Please do something with that. In addition to the multiple requests for js the reCaptcha stuff consume 15 to 28 requests on my sites (the higher number may be because I use 2 reCaptchas?). That is real #perfmatters

**Comment by mandys** [comment]
This is actually an issue for us too.
Multiple loads ( both for js and css ) and lowering of page score.

**Comment by uplink42** [comment]
Are there any plans on fixing this, or at least a workaround? We have a landing page with multiple forms (newsletters, contact us, registration etc) and all those recaptchas pile up quicky and aren't cached.

**Comment by stefanosalvucci** [comment]
same issue here

**Comment by Giuse69** [comment]
same issue here

**Comment by khalilgharbaoui** [comment]
same!

**Comment by JaniKowalski** [comment]
Same issue!

**Comment by brettrobertson61** [comment]
Same issue, Page Speed Insights complains about the 587k of render blocking JS.

**Comment by parisambush** [comment]
I'm having this issue too. My site is on shared hosting with limited resources, and this causes the pages that have captcha to take a very long time to load. This needs to be fixed!

**Comment by LevanArabuli** [comment]
same in 2025 :)

**Comment by abecuwedahive** [comment]
Same issue.
