### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by htorbov** [google/recaptcha#336]
Apperantly Facebook implementet your module and there's no submit button on it (since I couldn't find ANY bug report on this captcha module, I'll report it here).

<img width="1415" alt="Screenshot 2019-10-18 at 21 34 46" src="https://user-images.githubusercontent.com/1743266/67119579-25322880-f1f0-11e9-872d-07a75a8b4ee3.png">

**Comment by sysdl132** [comment]
ARE YOU KIDDING ME???
