### ISSUE TITLE
Issue with recaptcha v2 on Firefox

### ISSUE THREAD

**Issue by A-Zakaria** [google/recaptcha#342]
Hello,

We implemented the invisible recaptcha v2 on our website but we have sometimes an issue : the banner is not loaded (images) and the captcha is not working. 

To explain the workflow that we have : 
- the user click on a button to validate his action
- we show a popup saying that we need to validation that he is not a bot
- the user click on the button on the popup (that is link to invisible captcha)
- the user is redirected if the catcha is successfull

The issue, that we have some times, is that the following image that is showing the captcha logo is not loaded : 
![image](https://user-images.githubusercontent.com/57951053/69158197-51d6aa00-0ae6-11ea-894d-91eeff9dff02.png)

Here is a screenshot of the inspector with the content of the Iframe : 
![image](https://user-images.githubusercontent.com/57951053/69158271-7599f000-0ae6-11ea-8b9a-d02efcea06f8.png)
We can clearly see that one div is missing after the script tag (just before < / body >) that shows normally the logo. 

Then in that case, when the user tries to click on the captcha button, he is not redirected and the captcha is not working. 
In the network log, we didn't find any call that failed : 
![image](https://user-images.githubusercontent.com/57951053/69159497-513f1300-0ae8-11ea-9cff-2b374bdf583a.png)

There is no error on the JS console neither.

This issue is not happening every time but sporadically.... 

Can you help please ?

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
