### ISSUE TITLE
Question regarding issue moderation.

### ISSUE THREAD

**Issue by amcgregor** [google/recaptcha#347]
Howdy!

I was a participant in the discussion on #286 (the swear-entitled complaint about UX problems), which in the last 48 hours has been completely deleted.  I have a question as to why it was deleted rather than closed/locked, as the discussion there was extremely valuable in my eyes, and linked to / referenced by multiple external sources.

Unfortunately, I can only recover everyone else's contribution to that discussion from GitHub e-mail notifications (which will miss any post-creation edits) as [preserved by Rackspace permanent archiving](http://f.cl.ly/items/0x071I1i16261J2v1P3S/Screen+Shot+2019-12-23+at+15.37.13.png), and Archive.org only snagged [_extremely_ early copies](https://web.archive.org/web/20190215120424/https://github.com/google/recaptcha/issues/286).

Why was 286 deleted, when #252 has not been?  Similarly, #324 was closed as legitimately off-topic, not deleted outright.  (Abusive reports must be far more common than I'm seeing—good job moderators!—but the amount of constructive discussion in 286 hurts my soul to see wiped from the Earth.  Which is why I'm reconstructing it from my e-mail archives.  Once something exists on the internet, **it's forever**.)

Thank you and have an excellent day!
— Alice.

**Comment by rowan-m** [comment]
Not sure why it was deleted. If there was any valuable information in there pertaining to issues with the PHP client code, feel free to raise a new issue. I tend to close the ones that are just people complaining about the service since this is explicitly not a support forum for that.

**Comment by amcgregor** [comment]
Thank you for the response.  Best of luck in the future!

— Alice.

**Comment by amcgregor** [comment]
Thank you for the restoration of public visibility to the referenced thread/issue.  ❤️  It's "rude", but an example of turning a highly negative complaint into something positive, I believe.
