### ISSUE TITLE
Error in IE11 -  Failed to execute 'createElement' on 'Document': The tag name provided is not a valid name

### ISSUE THREAD

**Issue by uriklar** [google/recaptcha#353]
**Issue description**
Console error when with IE 11 user agent in chrome

**Environment**

 * OS name and version:
MacOS Cataline

 * Browser name and version:
Chrome 80

**Reproducing the issue**
1. Go to the [recaptcha demo page](https://recaptcha-demo.appspot.com/recaptcha-v2-invisible.php)
2. Using chrome - open dev tools - 3 dots on the right menu - More tools - Network conditions - Set user agent to Internet Explorer 11
3. Reload page.

See console error:
```
Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('<IFRAME name="a-4i3qggp3bv7">') is not a valid name.
```

**Comment by AnonymousBoyReal** [comment]
Spam

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
