### ISSUE TITLE
Typo in pl translation

### ISSUE THREAD

**Issue by Waniusza** [google/recaptcha#354]
**Description:**
When waiting some time after captcha v2 verification it expires and shows error message. 
In polish translation it has typo:
It is: 'Weryfikacja wygasła, zaznacz pole wyboru ponowie.'
It should be: 'Weryfikacja wygasła, zaznacz pole wyboru **ponowNie**.'

It happends on any site, any browser, any enviroment

![image](https://user-images.githubusercontent.com/9955963/75173258-e2003d00-572e-11ea-9dbf-30f38c141917.png)

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
