### ISSUE TITLE
Is this a security problem?

### ISSUE THREAD

**Issue by sysdl132** [google/recaptcha#357]
**Issue description**
I like this checker.But there is a problem:I just need to keep pressing that box(see the image) to skip verification.
![image](https://user-images.githubusercontent.com/54708046/76314570-09036500-6312-11ea-8dd4-2fa845ca5f2a.png)
![image](https://user-images.githubusercontent.com/54708046/76314633-2c2e1480-6312-11ea-865b-45b9dbaf7930.png)

**Environment**
formspree(on the image)

 * OS name and version:windows 10
 * PHP version:unknown
 * Web server name and version:formspree
 * `google/recaptcha` version:latest(maybe)
 * Browser name and version:opera GX,firefox,Microsoft edge(2 more)(this is the latest version and the issue appears on them all)
  
  ***User steps***
  
  
    1. Visit page https://sysdl132.gitee.io/report.html (my website using formspree.You can send any messages to me when you are testing recaptcha)

    2. enter some data...

    3.get into the recaptcha and click your mouse on the box(don't stop)

    4.and it will turn to green tick after some times.

**Comment by rowan-m** [comment]
I'm not able to reproduce this, are you able to record a video?

**Comment by sysdl132** [comment]
wait a minute...

**Comment by sysdl132** [comment]
if my CPU rate is low,the problem will appear.bot my CPU rate is high now...

**Comment by sysdl132** [comment]
I'm sorry because github doesn't allow .mp4 file so please unzip the following file and watch the video.
(open a new tab first!!!!!!)
[vid.zip](https://github.com/google/recaptcha/files/4329611/vid.zip)

**Comment by sysdl132** [comment]
Oh I forget to tell you:there is a point.If I click on it,I can skip it.

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
