### ISSUE TITLE
Error on file_get_contents()

### ISSUE THREAD

**Issue by renorram** [google/recaptcha#36]
I get errors, when I upload the code on web server, with the php variable allow_url_fopen that is set 0 for prevent ddos attacks, I've tried using cURL instead of file_get_contents but my codes doesn't works, so I'm asking for help with that and I think that this problem occurred with other people.
Sorry for my bad english.

**Comment by rowan-m** [comment]
The alternative `ReCaptcha\RequestMethod\SocketPost` method should work for you here. You can use this by replacing this line:
```php
$recaptcha = new \ReCaptcha\ReCaptcha($secret);
```
with this line:
```php
$recaptcha = new \ReCaptcha\ReCaptcha($secret, new \ReCaptcha\RequestMethod\SocketPost());
```

**Comment by yamlfd** [comment]
Can you put these detail into documentation, please? Not sooo "hidden" here in a queue...

**Comment by jonnott** [comment]
*Please* mention this in the README!

**Comment by demonking** [comment]
> _Please_ mention this in the README!
yes ... please
I have looked an hour for a solution and could't find anything there.
Maybe a Troubleshoot section?

**Comment by Rishats** [comment]
It's 2019, and I'm with you guys.
