### ISSUE TITLE
many warnings, says it will not be compatible with future PHP

### ISSUE THREAD

**Issue by dax006** [google/recaptcha#363]
Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in recaptchalib.php on line 94

Warning: file_get_contents(https://www.google.com/recaptcha: failed to open stream: no suitable wrapper could be found in recaptchalib.php on line 94

Warning: Use of undefined constant error - assumed 'error' (this will throw an Error in a future version of PHP) in recaptchalib.php on line 133

Warning: Use of undefined constant codes - assumed 'codes' (this will throw an Error in a future version of PHP) in recaptchalib.php on line 133

Warning: A non-numeric value encountered in recaptchalib.php on line 133

Warning: A non-numeric value encountered in recaptchalib.php on line 133

**Comment by rowan-m** [comment]
If you're using `recaptchalib.php` that version of this library is five years old now and not actively supported. I would take a look at the current version of the library to see if you can upgrade.
