### ISSUE TITLE
missing autoload.php

### ISSUE THREAD

**Issue by Aeliot-Tm** [google/recaptcha#37]
There is line #34 in file /examples/example-captcha.php:
require_once __ DIR __ . '/../vendor/autoload.php';
But there is no such file in the library.

**Comment by renorram** [comment]
right, the vendor dir is automatically created by composer. If you not use composer you have to use an autoloader class like this https://gist.github.com/jwage/221634 or in a fast way for a simple test, just include all files.

**Comment by rowan-m** [comment]
I've made the comment in the example a bit clearer:
ac5696b7455de4e2f5ef8c9788e475514c3819f8
