### ISSUE TITLE
reCAPTCHA becoming less able to detect real users [likely due to huge increase of users during pandemic]

### ISSUE THREAD

**Issue by DFNCTSC** [google/recaptcha#370]
@rowan-m  Last time we talked was 2 years ago, right before you were pushing out v3. It seems that as time has passed the efficacy of v3 has become exactly the same as v2 and you need to start it from fresh again because it's confidence metrics are no longer working -- it thinks almost all real people are bots. I'm pretty sure this is because of the huge influx of users that are pushing the confidence model in the wrong direction.

**Comment by DFNCTSC** [comment]
Additionally, it seem as of late (possibly due to reCAPTCHA slowly progressively beginning to be less effective) that many large sites (i.e. humblebundle.com) have switched over to hCAPTCHA @ https://www.hcaptcha.com/ Just wanted to make sure you knew about this new CAPTCHA.

**Comment by rowan-m** [comment]
This repo is for issues with the PHP client.
