### ISSUE TITLE
Class ReCaptcha

### ISSUE THREAD

**Issue by toplisek** [google/recaptcha#371]
**Issue description**
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ReCaptcha has a deprecated constructor in  recaptchalib.php on line 42

**Environment**
Linux/Apache

Web applications.

**Reproducing the issue**
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ReCaptcha has a deprecated constructor in recaptchalib.php on line 42

What we should change in this example?

**Comment by rowan-m** [comment]
Versions including `recaptchalib.php` were deprecated five years ago, you should update your dependencies. There is an short upgrade guide here: https://github.com/google/recaptcha/tree/1.1.0#from-100
