### ISSUE TITLE
recaptcha__ru.js:152 Uncaught TypeError: Cannot read property 'I' of undefined

### ISSUE THREAD

**Issue by l2toplist** [google/recaptcha#373]
please fix this error, recaptcha is not loading....
https://www.gstatic.com/recaptcha/releases/wk6lx42JIeYmEAQSHndnyT8Q/recaptcha__ru.js

console error

`Uncaught TypeError: Cannot read property 'I' of undefined
    at ce (recaptcha__ru.js:152)
    at 71067377e8bc2a4518ea2974f697f5f8.js:526
ce @ recaptcha__ru.js:152
(anonymous) @ 71067377e8bc2a4518ea2974f697f5f8.js:526
load (async)
(anonymous) @ recaptcha__ru.js:547
(anonymous) @ recaptcha__ru.js:660`

Problem : u.I("rc-imageselect-target"))),
in string
 `ce=function(q,g,c,u,e,U,A,k,H,I,v){return(1==((((I=[7,4,27],q+I[1])%I[0]||(YN(c,38,Rp)?H=$r(I[0],23,"<\\/",c.kF()):(null==c?A=g:(c instanceof T5?(c instanceof T5&&c.constructor===T5&&c.W===Mv?u=c.L:(d(I[2],c),u="type_error:SafeStyle"),e=$r(I[0],I[0],"<\\/",u)):(c instanceof z2?U=$r(I[0],15,"<\\/",B_(5,c)):(k=String(c),U=ap.test(k)?k:"zSoyz"),e=U),A=e),H=A),v=H),q)^85)&11)&&(e=[100,"rc-imageselect-carousel-instructions",1],bs("rc-imageselect-carousel-leaving-left",38,l(6,!1,e[2],u.I("rc-imageselect-target"))),`

**Comment by DJB31st** [comment]
Are you using MooTools?

https://github.com/google/recaptcha/issues/374

**Comment by l2toplist** [comment]
no, i use polyfill
this js conflict
`
Function.prototype.binds = function(context) {	
	var fn = this;
	if(jQuery.type(fn) != 'function'){
		throw new TypeError('Function.prototype.bind: call on non-function');
	};
	if(jQuery.type(context) == 'null'){
		throw new TypeError('Function.prototype.bind: cant be bound to null');
	};
	return function() {
		return fn.apply(context, arguments);
	};
};
`

problem solved.
I fix this js

`
if ( ! Function.prototype.bind ) {
	Function.prototype.bind = function ( obj ) {
	    if ( typeof this !== "function" ) {
	        throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");
	    }
var slice = [].slice,
	        args = slice.call(arguments, 1),
	        self = this,
	        nop = function () {},
	        bound = function () {
	            return self.apply( this instanceof nop ? this : ( obj || {} ), args.concat( slice.call( arguments ) ) );
	        };
nop.prototype = this.prototype;
	    bound.prototype = new nop();
    return bound;
	};
}
`

**Comment by vrchen** [comment]
I'm getting a similar error on Chromium.
```
    TypeError: Cannot read property 'bg' of undefined

      at ../https:/www.gstatic.com/recaptcha/releases/iSHzt4kCrNgSxGUYDFqaZAL9/recaptcha__en.js:530:109
```
only recently started happening. we don't currently have a polyfill for `Function.prototype.binds` but I wouldn't expect a polyfill to be necessary given `bind` is supported on Chrome.

Am I thinking about this correctly?

Looking at the code, `bg` is being called on `window.botguard` which turns out to be `undefined` and causes this error.

**Comment by vrchen** [comment]
> I'm getting a similar error on Chromium.
> 
> ```
>     TypeError: Cannot read property 'bg' of undefined
> 
>       at ../https:/www.gstatic.com/recaptcha/releases/iSHzt4kCrNgSxGUYDFqaZAL9/recaptcha__en.js:530:109
> ```
> 
> only recently started happening. we don't currently have a polyfill for `Function.prototype.binds` but I wouldn't expect a polyfill to be necessary given `bind` is supported on Chrome.
> 
> Am I thinking about this correctly? Or does this mean we now need the polyfill?
> 
> Looking at the recaptcha's source code, `bg` is being called on `window.botguard` which turns out to be `undefined` and causes this error.

Turned out I just needed to bump my version of Chromium.

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
