### ISSUE TITLE
Add cURL request method

### ISSUE THREAD

**Issue by boaf** [google/recaptcha#38]
I'm working on a locked-down server that disallows both `file_get_contents` and `fsockopen`, but it does support cURL. I've hacked together a [`Curl` class](https://github.com/google/recaptcha/compare/master...boaf:curl-request-method) that implements `RequestMethod`—it seems to work well for my purposes.

Is this something that would be appropriate for the project? If this makes sense I can write the tests for it as well, with a bit of guidance (I admit!—I've never written PHPUnit tests before...).

**Comment by rowan-m** [comment]
Hey there @boaf, glad to hear you were able to implement against the interface - exactly why it's there. :) I'm more than happy if you want to submit the class as a PR and I can review with you to help build out the tests and any other changes.

**Comment by yamlfd** [comment]
Need this too for reCAPTCHA for Drupal module.

**Comment by yamlfd** [comment]
@boaf: Tried your code, but I'm getting errors "curlArray ( [0] => invalid-json )"`and the captcha is not validated.

```
$recaptcha = new \ReCaptcha\ReCaptcha($recaptcha_secret_key, new \ReCaptcha\RequestMethod\Curl());
```

**Comment by boaf** [comment]
Somewhat of a guess, but you may be dealing with outdated SSL certificates on your machine. If that's the case you need to use an updated PEM file. Take a look at the one available here if you're in a pinch: http://curl.haxx.se/docs/caextract.html

I had to go through the same thing. I downloaded the HTTP version from the above link and added it to my script's directory and referenced this new file in the `$options` array with `CURLOPT_CAPATH`, such as `CURLOPT_CAPATH => 'cacert.pem'`.

I don't know that this code is relevant to the addition of a cURL request method, though, because a server with up-to-date certs wouldn't have this problem to begin with.

I could be entirely wrong about the cause, so please do let me know if you can't get this working.

I could also be wrong about the irrelevant nature of this code...

**Comment by yamlfd** [comment]
I've set CURLOPT_SSL_VERIFYPEER => false just as a test and now it works. Importing PEM files it not really an easy task for very many people I think. We should think about adding this to the library and using the CURLOPT_CAPATH param by default. At least I have no clue where XAMPP has it's PEM file that cURL uses.

Additionally I wonder why cURL does not error with something like "Google's root certificate is missing from CA store".

I also strongly suggest to add CURLOPT_TIMEOUT or we may run a lot of zombies over time!

**Comment by yamlfd** [comment]
Timeout in https://github.com/google/recaptcha/blob/master/src/ReCaptcha/RequestMethod/SocketPost.php#L91 is 30 seconds.

I just like to note about the SSL ca issue that there is no problem at all with fsockopen. No idea why curl is using its own ca file. We can add the CA required for the google certificate only. No need for the full ca file that has all files.

**Comment by yamlfd** [comment]
I'm out here. I created my own RequestMethod files for Drupal 6/7/8 based on Drupal internal http functions. Drupal itself allows overriding the http client and therefore this is up to e.g. Drupal cURL module to do it right. I will maintain these RequestMethod files in the Drupal modules for now. This gives me more flexibility and I do not believe this will be integrated here if I share it.

**Comment by rowan-m** [comment]
Hi @yamlfd I've merged @boaf 's PR now and I'm doing some testing to see if I hit the same issues as you. Regarding your Drupal modifications, I am happy to include additional `RequestMethod` classes that do not introduce additional dependencies (except for relatively standard extensions like cURL, etc). So, if you need to add additional functionality to support Drupal that's perfect. However, if those classes depend on Drupal (or Drupal modules) then they should stay within the Drupal module.

**Comment by boaf** [comment]
Hi @yamlfd, @rowan-m,

Apologies for the silence!

@yamlfd, thanks for exploring the SSL stuff. I'm not sure what the best route would be, but might it be worth adding a secondary method to the class that injects a PEM file for those that need it?

```php
    /* Not at all tested... */
    private $certPath = NULL;

    public function __construct(string $filename)
    {
        if (file_exists($filename)) {
            $this->$certPath = $filename;
        }
    }
    /*. . .*/
    public function submit(RequestParameters $params)
    {
    /*. . .*/
        if ($this->$certPath !== NULL) {
            $options[CURLOPT_CAINFO] = $this->$certPath;
        }
```
And later...
```php
$recaptcha = new \ReCaptcha\ReCaptcha('xxxxx', new \ReCaptcha\RequestMethod\Curl($pathToCert));
/* $recaptcha->verify(...) etc etc */
```

Let me know what you think..

@rowan-m, there's a PR on my repo to implement a unit test for this class that I'd like to try to implement in a little bit... I'll submit that in another PR.

**Comment by rowan-m** [comment]
Unit tests are always good. I was fine with the current implementation not having them since it was pretty much just a sequential set of cURL calls. However, the addition of any logic in there will certainly need them.

My immediate feedback on the `$filename` parameter is that I think I'd prefer to see an individual `set` method on the class and a config object or array going into the constructor. My feeling is that there may be additional configuration options to pass in here especially considering the other proxy-related issue.

**Comment by yamlfd** [comment]
I think the certificate issue do not need to be handled here. See https://www.drupal.org/node/2481341 how this need to be fixed. It is a global php.ini addition. 

I have not seen a single install that do not require the pem file.

Yes, my classes hardly depend on Dupal. You cannot use them outside of Drupal I think. See http://cgit.drupalcode.org/recaptcha/tree/src/ReCaptcha/RequestMethod/Drupal8.php?h=8.x-2.x and there are also files in 7.x-2.x and 6.x-2.x for other Drupal versions.

**Comment by WouterDS** [comment]
Any plans on releasing ReCaptcha\RequestMethod\Curl anytime soon?
I can also only use curl, and I tested it with the master branch and it seems to work just fine. But of course it's not ideal to require google/recaptcha on the master branch.

Looking forward to see this in a release soon!

**Comment by WouterDS** [comment]
What is the reason the url request method still hasn't been included in a release?

**Comment by wouterds** [comment]
Bump? ^

**Comment by wouterds** [comment]
Bump bump bump? ^

**Comment by rowan-m** [comment]
Thank you for the enthusiasm :D I'll get on and do a minor version bump now. For future reference, you can always tell Composer to pull the `master` branch for merged features since the branch should always be stable.

**Comment by wouterds** [comment]
Thanks, @rowan-m!

**Comment by rowan-m** [comment]
@wouterds @boaf @yamlfd I've released a new version with the cURL method in there. Please note though the class is now `ReCaptcha\RequestMethod\CurlPost` so that it's consistent with the `ReCaptcha\RequestMethod\SocketPost` class and because I've introduced a `ReCaptcha\RequestMethod\Curl` wrapping the native cURL methods to allow for unit testing.
