### ISSUE TITLE
Suggestion: change the name of this repository

### ISSUE THREAD

**Issue by resynth1943** [google/recaptcha#385]
Hello,

I am unsure whether or not this is intentional, but from a first glance it may look like the reCAPTCHA is open-source, when in reality it is quite the opposite. I understand that reCAPTCHA cannot be open-sourced due to the _insane_ tracking it does, so I suggest you rename this repository. Perhaps something like `recaptcha-php` would be more appropriate.

Many thanks,
resynth1943

**Comment by rowan-m** [comment]
If I was starting this repo today, yes - the language distinction would be clear. However, this repo was created in 2014 and now has a significant number of references pointed at it - composer, to name one. Renaming is non-trivial. While the first three words of the repo description are "PHP client library", I understand that my expectation that people may read that are a little optimistic.
