### ISSUE TITLE
recaptcha v3 always 0.9 even with Bot - WHY?

### ISSUE THREAD

**Issue by ertejaspatel** [google/recaptcha#386]
Ton of people have this issue but I couldn't find any work around or solution. 
Even with Bot - Google Recaptcha returns score of 0.9 which is definitely a plugin.

I created a bot with Selenium + Nodejs and changed user agent to Google Bot 2.1 etc.. but it still returns 0.9

Usability and Experience wise - that is bit bad from Google. 

Expected solution: 

Google should provide settings in the Recaptcha Admin Panel to configure test score - which users can set themselves and test their overall functionality.

Looking forward with some proper sensible work around or solution so that can get low score and test overall functionality.

Thanks

**Comment by phillipjohnston** [comment]
I recently enabled recaptcha v3 on my website due to an increase in bots filling out forms. However, all of the bot messages receive a score of 0.9.

**Comment by rowan-m** [comment]
This repo is for issues with the PHP client.

However, a couple things you may want to consider:

- The v3 API adapts to traffic on your site. You will need to allow some time and volume to establish traffic patterns.
- Consider adding the v3 API to a selection of different actions across the site.
- You can still use the v2 API if you want the challenge to appear for detected issues.

**Comment by phillipjohnston** [comment]
Yes, I'm using the PHP client. Noted on allowing for time.

**Comment by HamadAlsoghayer** [comment]
@phillipjohnston any updates on this issue?
