### ISSUE TITLE
Cookie “SIDCC” will be soon rejected because it has the “sameSite”

### ISSUE THREAD

**Issue by edwolfe3** [google/recaptcha#393]
I'm getting a browser console warning: 

Cookie “SIDCC” will be soon rejected because it has the “sameSite”

Coming from https://www.google.com/recaptcha/api.js, https://www.google.com/recaptcha/api2/anchor and https://www.google.com/recaptcha/api2/webworker.js

When will recaptcha be sameSite compliant?

**Comment by rowan-m** [comment]
This cookie is set by the `google.com` site, but is unrelated to reCAPTCHA. Google services are rolling out their changes to update cookies for the new behaviour. This warning should not affect the behaviour of reCAPTCHA on the site where you saw this notice.
