### ISSUE TITLE
Invalid action name in recaptcha v3

### ISSUE THREAD

**Issue by gimita** [google/recaptcha#394]
When I try to check an action in recaptcha v3 and the action name contains a “-” character, I get the following error:

Invalid action name, may only include "A-Za-z/_". Do not include user-specific information.
<img width="984" alt="Screen Shot 2020-06-26 at 00 12 00" src="https://user-images.githubusercontent.com/6356539/85791188-752f9a80-b742-11ea-8211-0eacc9b5751a.png">

**Comment by rowan-m** [comment]
I can see how that message might be confusing. Where it's stating `A-Z`, it means the characters `A` through to `Z`. The `-` is indicating the range and is **not** a valid character for the action name.

From https://developers.google.com/recaptcha/docs/v3
> Actions may only contain alphanumeric characters and slashes, and must not be user-specific.

For example:
⛔ Invalid actions: `user-login`, `comment-add`, `add-to-cart`
✔️ Valid actions: `user/login`, `comment/add`, `add_to_cart`

**Comment by gimita** [comment]
Thank you for your reply.

The fact is why the “-" sign is not allowed.

I think that in many projects keys with a “-” sign are used, which need to be checked.
For example, in our project, when the current path to a location changes, we get a new one and try to check it. But many of them have a “-” sign.
