### ISSUE TITLE
Is this is a vulnerability or am I testing this on a low level ReCaptcha?

### ISSUE THREAD

**Issue by EZCLAP03** [google/recaptcha#395]
I tried for a long time to find a way to bypass the ReCaptcha(Purely for educational purposes) and to test my script on a website I used the official demo for ReCaptcha v3. Link - https://www.google.com/recaptcha/api2/demo. And just to clarify am I stupid or this is an actual issue, I wrote two lines of python code to bypass it. I used a library called pyautogui and respective of where the checkbox is located, I gave it the coordinates and made it click automatically. This worked every time. This question is for clarity and I am not fully sure if this version is under development but I have seen it in use in a fair few websites.

**Comment by rowan-m** [comment]
This repo is for issues with the PHP client.
