### ISSUE TITLE
Implementing recaptcha on my site put me on a blacklist.

### ISSUE THREAD

**Issue by keyoti** [google/recaptcha#396]
Immediately after successfully implementing recaptcha on my website (and testing it by deliberately failing the captcha test a couple of times) I am now no longer trusted, this is what happened:

-Starting getting "select the fire hydrant" type challenges instead of the usual "not a robot" checkbox.
-The fire hydrant challenges keep failing me even though I am 100% certain I have selected all hydrants.
-More troubling, 3rd party sites don't trust me any more.  Craigslist doesn't seem to be sending my emails to the seller,  Lego.com has to 2 factor me for a regular sign-in.

So implement it at your peril or in an incognito without signing in to Google.

How do I get back my trust?

**Comment by rowan-m** [comment]
This repo is for issues with the PHP client.
