### ISSUE TITLE
Google recaptcha is not working, getting 404 errot

### ISSUE THREAD

**Issue by somireddysathiDB** [google/recaptcha#397]
Hi,

We are using ALB as the client facing and have Apache reverse proxy in between ALB and application server. Implemented the below solution in Apache reverse proxy without any virtual host. getting js file If I try to access the js file from browser as "`http://<reverse proxy url>/recaptcha/api.js`". I am getting 404 error when I tried from browser as "`https://<ALB URL>/recaptcha/api.js`". I verified the Apache reverse proxy logs, connection is established with google but getting 404 error from google somehow. Can you please share your thoughts what is going wrong. appreciate your help.

```
ProxyPass "/recaptcha" "https://www.google.com/recaptcha"
ProxyPassReverse "/recaptcha" "https://www.google.com/recaptcha"

ProxyPass "/" "https://www.gstatic.com/"
ProxyPassReverse "/" "https://www.gstatic.com/"

FilterDeclare CUSTOMFILTER
  FilterProvider CUSTOMFILTER SUBSTITUTE "%{CONTENT_TYPE} =~ m|^text/html|"
  FilterProvider CUSTOMFILTER SUBSTITUTE "%{CONTENT_TYPE} =~ m|^text/css|"
  FilterProvider CUSTOMFILTER SUBSTITUTE "%{CONTENT_TYPE} =~ m|^text/javascript|"
  FilterProvider CUSTOMFILTER SUBSTITUTE "%{CONTENT_TYPE} =~ m|^application/javascript|"

<Location />
RequestHeader unset Accept-Encoding
FilterChain CUSTOMFILTER
      Substitute "s/www.google.com/<ALB URL>/ni"
      Substitute "s/www.gstatic.com/<ALB URL>/ni"
</Location>

ProxyPassReverseCookieDomain "www.google.com" "<ALB URL>"
ProxyPassReverseCookieDomain "www.gstatic.com" "gstatic.<ALB URL>"
```

**Comment by rowan-m** [comment]
I think you may have more success asking on specific ALB or Apache groups on StackOverflow as I'm not overly familiar with configuration for these services.
