### ISSUE TITLE
CONST version is incorrect

### ISSUE THREAD

**Issue by yamlfd** [google/recaptcha#40]
https://github.com/google/recaptcha/blob/1.1.1/src/ReCaptcha/ReCaptcha.php lists 1.1.0 as library version.

**Comment by yamlfd** [comment]
readme is also incorrect, maybe more files.

**Comment by rowan-m** [comment]
Unfortunately I only noticed this after I pushed the tag. :( So, I don't have a way to retroactively fix this for the 1.1.1 release, but I'll be adding some deployment scripts to ensure this is automated for the next version. Thank you for reporting it though!
