### ISSUE TITLE
Recaptcha v3 scores iPad Pro iPadOS 14 webview as 0.3 always

### ISSUE THREAD

**Issue by cyrilthomas** [google/recaptcha#409]
We use WebView on iOS apps for user sign in.  The sign in form has reCaptcha v3 integrated and always scores the WebView on iPad Pro iPadOS 14 with a 0.3 score. iPad Pro on older iPadOS versions gets a better score of 0.7 or higher.

**Comment by jelleklaver** [comment]
I had this happening as well. Got `0.3` always on iOS and not on other devices. Generating new key/secret seems to have fixed this, not sure why though..

**Comment by rowan-m** [comment]
Repo is just for PHP client issues. This is about the reCAPTCHA service.
