### ISSUE TITLE
Mailhide support?

### ISSUE THREAD

**Issue by yamlfd** [google/recaptcha#41]
- Why has the mailhide support removed from the library?
- Will it be added back soon?

**Comment by BassemN** [comment]
Yes, we need support fot mailhide

**Comment by arichiardi** [comment]
:+1:

**Comment by rowan-m** [comment]
Mailhide is part of the V1 API and does not currently have an equivalent in V2. This client library only supports V2 for the moment. However, you can still access the Mailhide functionality using the V1 client here: https://code.google.com/p/recaptcha/ Specifically, the PHP download is here: https://code.google.com/p/recaptcha/downloads/detail?name=recaptcha-php-1.11.zip&can=2&q=

**Comment by yamlfd** [comment]
I'm aware of this v1 feature, but I asked for v2 no captcha recaptcha support and not the v1. Please reopen this case as there is no solution and this is a feature request.

**Comment by yamlfd** [comment]
Why is this case still not reopenend?

**Comment by rowan-m** [comment]
This is purely a client to the v2 API, not a server. If Mailhide functionality is added in the v2 or abve API, then this client will support it.

**Comment by yamlfd** [comment]
Can your Google colleagues share infos if they plan to support it in future or not at all? It's hard that we already have a feature regression...

**Comment by cilefen** [comment]
+1

**Comment by ovidiugabriel** [comment]
Please reopen. Mailhide is not working.

**Comment by npsimons** [comment]
I'll second this. Would really like to see mailhide feature continue in reCAPTCHA. Thanks!

**Comment by Harti** [comment]
Comment for nagging/visibility

**Comment by VBGAMER45** [comment]
I guess we could just code our own version and use recaptcha v2 keys on our domain.

**Comment by alanhouser** [comment]
It's still working even though the V1 error message appears. Actually, the red text that reads "reCAPTCHA V1 IS SHUTDOWN" — if you type that, it works. (seriously)

![screencast 2018-04-25 at 10 51 42 pm](https://user-images.githubusercontent.com/4256989/39283234-56edecd4-48db-11e8-95d5-68ff827a77a8.gif)

**Comment by wilk-polarny** [comment]
@alanhouser 

> "reCAPTCHA V1 IS SHUTDOWN" — if you type that, it works. (seriously)

You can type in anything to bypass this mailhide captcha o.o

**Comment by marcelstoer** [comment]
Maybe redirect all the "bring mailhide back"-comments to #221.

**Comment by qgustavor** [comment]
Is it possible to implement just the email deobfuscation part (not the obfuscation part) so people can access obfuscated email addresses from unmaintained websites?

**Comment by irishgeoff22** [comment]
You can [hide email on website with captcha](https://veilmail.io/) using veilmail.io
