### ISSUE TITLE
Use without composer?

### ISSUE THREAD

**Issue by TheZoker** [google/recaptcha#42]
Is it possible to use this script without using composer? Its not installed on my webspace, but I need the recaptcha php script...

Thank you

**Comment by TheZoker** [comment]
I tried to use it with the 'recaptchalib.php' file, but I only got a captcha that looks like this:
![img_2015 04 21_13h23m00s_001_](https://cloud.githubusercontent.com/assets/1368405/7251234/b631f8b8-e829-11e4-8ea1-6f7cfdfd97e0.png)

Why is it so big and not the tiny one, showed on the recaptcha website?

**Comment by Rikk** [comment]
We need an autoloader... Until Google gets real and understands that not everyone needing Recaptcha will want to install a whole new software just to compile a simple autoloader!
Luckly, @orlitzky has made one: https://github.com/google/recaptcha/pull/34
Get it from his fork: https://github.com/orlitzky/recaptcha/tree/manual-install

**Comment by TheZoker** [comment]
Works great :)
Can you may tell me, why the recaptche is so big? Because normally its a way tinier isn't it?
!(https://www.google.com/recaptcha/intro/images/hero-recaptcha-demo.gif)

**Comment by Rikk** [comment]
There is an alternative mode, which is used when there is no javascript. It is also big (shows a captcha) when it has suspects about you... The screenshot looks like you fill in the first case.

**Comment by TheZoker** [comment]
Javascript is enabled in my browser (and not blocked) and on other pages the captcha is small. Could it be a issue with anything else?
