### ISSUE TITLE
reCaptcha Thinks MotorCycle is a Bicycle

### ISSUE THREAD

**Issue by EliSauder** [google/recaptcha#424]
Not sure if this is the right place to post this, but reCaptcha is seeing motorcycles as bicycles.

![image](https://user-images.githubusercontent.com/24995216/106784884-ab4eca00-6601-11eb-9cfa-5b1602fbfed1.png)

**Comment by BartAgterbosch** [comment]
Same here, except it was a multiple picture recaptcha, apparently ai is pretty dumb

**Comment by spatical** [comment]
This still happens often for me.  Are there a bunch of people saying the motorcycles are the bicycles training the A.I. that way?  In my mind, motorcycles are not bicycles.

**Comment by rowan-m** [comment]
Repo is just for PHP client issues. This is about the reCAPTCHA service. I can confirm that does not look like a bicycle to me.
