### ISSUE TITLE
"Download" image link in Audio challenge defined through CSS

### ISSUE THREAD

**Issue by BarrierbreakApp** [google/recaptcha#425]
Example URL: https://www.google.com/recaptcha/api2/demo

The "Download" image links in the reCAPTCHA non-modal dialog (that becomes available on "Get an audio challenge" button) is defined through CSS. As a result, the purpose of the image links are not clear for screen reader users. Additionally , the image links will not be visible in Internet Explorer browser on a Windows operating system for users browsing with their High Contrast mode turned on.

HTML:
`<a class="rc-audiochallenge-tdownload-link" target="_blank" href="https://www.google.com/recaptcha/api2/payload/audio.mp3?p=06AGdBq27TotpmQu6NpTsZW-b4Jk4vFmEUIqQYDoNQnLD6sdA4IJKu8iapcHo7Q6IXzuP_x5NgUMsT_RrHmwdBYDinuyroy0V3lzHcIaxm8SFSQ6dm7P4KvX7-ALZYYZN60IcUy15no7OfuLcvTGziH33-L8Sl_0_eGM-rNyQkd4TUax-7L4bVvxHkPDhPyJywdzss2iH9OH8m&amp;k=6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-" title="Alternatively, download audio as MP3"></a>`

CSS:
`.rc-audiochallenge-tdownload-link {
    background-image: url(https://www.gstatic.com/recaptcha/api2/download.png);
    background-repeat: no-repeat;
    background-size: 36px;
    color: transparent;
    display: inline-block;
    height: 36px;
    opacity: .55;
    overflow: hidden;
    width: 36px;`

Suggestion:
Implement the image link with the HTML <img> element and provide descriptive textual description  as "Download audio as MP3" using "alt" attribute in it's source code. 

`<a class="rc-audiochallenge-tdownload-link" target="_blank" href="https://www.google.com/recaptcha/api2/payload/audio.mp3?p=06AGdBq27T5LTo511syvjLbBFr-K1--45zxXYe1vSnwmxui-Hg2g3eKPnJQ4v1yEFlAoabF53Z_Ftv9Z45aunaxYSBKse3_OapjsmO44xm7oZKQTll5TKIOolSHex_vK5lfUsQ9YsAusqoav3VIHd4P08kRojTGhJGPjnFYnlzTGcsaaMVQIrjX3wKZBnPOSYnP7hZnyHe0JuD&amp;k=6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-" title="Alternatively, download audio as MP3">`
`<img src="https://www.gstatic.com/recaptcha/api2/download.png" alt="Download audio as MP3">`
`</a>`

![reCaptcha_2a](https://user-images.githubusercontent.com/16647640/107731515-3293f000-6d1c-11eb-89e7-07e16620abf6.png)

![reCaptcha_2b](https://user-images.githubusercontent.com/16647640/107731517-33c51d00-6d1c-11eb-9488-e863970864df.png)

`

**Comment by rowan-m** [comment]
These all look like automated issues for the widget unrelated to the PHP client library in this repo.
