### ISSUE TITLE
"Enter the words you hear" Input field for audio challenge does not have associated label

### ISSUE THREAD

**Issue by BarrierbreakApp** [google/recaptcha#427]
Example URL: https://www.google.com/recaptcha/api2/demo

The "Enter the words you hear" input field in the reCAPTCHA non-modal dialog (that becomes available on activating "I'm not a robot" checkbox > "Get an audio challenge" button) does not have label associated with it and the title attribute is not included in its source code either. As a result, users with visual impairments who use a screen reader will not be able to understand the purpose of the input field.

`<input type="text" id="audio-response" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" dir="ltr" class="rc-response-input-field label-input-label">`

Suggestion:
Provide unique and descriptive label for each form control using <label> element. This will help screen reader users to understand the purpose of the form control and input the details accordingly. Web pages that lack label for form controls make it difficult for screen reader users to complete the form successfully.
In addition, associate the label explicitly with the form control using the “for” and “id” attribute to ensure that assistive technologies identify the label for each form control correctly. 
Alternatively use either hidden labels or ‘title’ or ‘aria-label’ attribute to convey the purpose of the form controls to screen reader users as well as maintain the presentation.

`<input type="text"  title="Enter the words you hear" id="audio-response" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" dir="ltr" class="rc-response-input-field label-input-label"`>

![reCaptcha_7](https://user-images.githubusercontent.com/16647640/107733106-26119680-6d20-11eb-9b51-8e5b917d3b36.png)

**Comment by rowan-m** [comment]
These all look like automated issues for the widget unrelated to the PHP client library in this repo.
