### ISSUE TITLE
Non-interactive error message text receives keyboard focus

### ISSUE THREAD

**Issue by BarrierbreakApp** [google/recaptcha#428]
Example URL: https://www.google.com/recaptcha/api2/demo

Non interactive `<div>` element containing the text "Please select all matching images." error message (that becomes available on selecting the "I'm not a robot" checkbox > "Verify" button) and "Multiple correct solutions required - please solve more." error message (that becomes available on selecting the "I'm not a robot" checkbox > Get an audio challenge > enter incorrect data in input field and click on verify button) in the non-modal dialog receives keyboard focus. 
This resulted in keyboard-only users having to go pass an additional tab stop while navigating between the page content.
Note: Users with mobility impairments (who find it difficult to control the mouse) rely on a keyboard to interact with a web page's content and functionality.

`<div class="rc-imageselect-error-select-more" style="" tabindex="0">Please select all matching images.</div>`
`(...)`
`<div class="rc-audiochallenge-error-message" style="" tabindex="0">Multiple correct solutions required - please solve more.</div>`

Suggestion:
Remove the 'tabindex' attribute from the non-focusable elements in the page source.

`<div class="rc-imageselect-error-select-more" style="">Please select all matching images.</div>`
`(...)`
`<div class="rc-audiochallenge-error-message" style="">Multiple correct solutions required - please solve more.</div>`

![reCaptcha_8a](https://user-images.githubusercontent.com/16647640/107735369-8b1bbb00-6d25-11eb-941e-3c1d1bfa6c85.png)

![reCaptcha_8b](https://user-images.githubusercontent.com/16647640/107735374-8d7e1500-6d25-11eb-8b5f-613300ae8098.png)

**Comment by rowan-m** [comment]
These all look like automated issues for the widget unrelated to the PHP client library in this repo.
