### ISSUE TITLE
Non-interactive text that is available after activating "Help" button receives keyboard focus

### ISSUE THREAD

**Issue by BarrierbreakApp** [google/recaptcha#429]
Example URL: https://www.google.com/recaptcha/api2/demo

Non-interactive element `<div>` containing the text "Click on any tiles you see with the object described in the text. If new images appear with the same object, click those as well. When there are none left, click Verify." (that becomes available on selecting the "I'm not a robot" checkbox > "Help" button) receives the keyboard focus. This resulted in keyboard-only users having to go pass an additional tab stop while navigating between the page content.
Note: Users with mobility impairments (who find it difficult to control the mouse) rely on a keyboard to interact with a web page's content and functionality.

`<div class="rc-challenge-help" style="" tabindex="0">Click on any tiles you see with the object described in the text. If new images appear with the same object, click those as well. When there are none left, click Verify.</div>`

Suggestion:
Remove the 'tabindex' attribute from the non-focusable elements in the page source.

`<div class="rc-challenge-help" style="">Click on any tiles you see with the object described in the text. If new images appear with the same object, click those as well. When there are none left, click Verify.</div>`

![reCaptcha_9](https://user-images.githubusercontent.com/16647640/107735960-e69a7880-6d26-11eb-821e-5852f958e62c.png)

**Comment by rowan-m** [comment]
These all look like automated issues for the widget unrelated to the PHP client library in this repo.

**Comment by Remon09i** [comment]
Nice

**Comment by Remon09i** [comment]
Nice

**Comment by Remon09i** [comment]
Good

**Comment by Remon09i** [comment]
Good
