### ISSUE TITLE
Uncaught TypeError: Cannot read property 'register' of undefined

### ISSUE THREAD

**Issue by yashikagarg13** [google/recaptcha#43]
Every now and then, I see this issue
Uncaught TypeError: Cannot read property 'register' of undefined
I am not sure why this happens. It is at line rpc.v.js:23

**Comment by rowan-m** [comment]
Hi @yashikagarg13 this is coming from the JS, so shouldn't be an issue within the PHP client here. Have you tried checking what's detailed in this stackoverflow issue: http://stackoverflow.com/questions/5848193/uncaught-typeerror-in-google-recaptcha

**Comment by yashikagarg13** [comment]
@rowan-m IT was an issue with how I was using it in the application. Fixed now! thanks a lot!
