### ISSUE TITLE
Captch control buttons defined through CSS

### ISSUE THREAD

**Issue by BarrierbreakApp** [google/recaptcha#431]
Example URL: https://www.google.com/recaptcha/api2/demo

The captcha controls such as  "Get a new challenge", "Get an audio challenge" and "Help" buttons (that becomes available on activating "I'm not a robot" checkbox) are defined through CSS. Because of that, these icons will not be visible in Internet Explorer browser on a Windows operating system for users browsing with their High Contrast mode turned on.

**HTML:**
`<button class="rc-button goog-inline-block rc-button-reload" title="Get a new challenge" value="" id="recaptcha-reload-button" tabindex="0"></button>`

**CSS:**
`.rc-button-reload {
background: url(https://www.gstatic.com/recaptcha/api2/refresh_2x.png);
}`

Suggestion:
Use CSS content property (with ::before and ::after pseudo-elements) or font: awesome icons to define the images to ensure that the image become visible when the Windows High Contrast Mode is turned on.

Alternatively, ensure all informative images must be implemented with the HTML <img> element and Provide empty alt attribute (alt="") in its source code as textual description is provided for the image.

`<button class="rc-button goog-inline-block rc-button-reload" title="Get a new challenge" value="" id="recaptcha-reload-button" tabindex="0">`
`<img src="https://www.gstatic.com/recaptcha/api2/refresh_2x.png" alt=""></button>`

![reCaptcha_11a](https://user-images.githubusercontent.com/16647640/107736578-755bc500-6d28-11eb-9733-d264429623ea.png)

![reCaptcha_11b](https://user-images.githubusercontent.com/16647640/107736580-77be1f00-6d28-11eb-9299-0be7f2c2ae80.png)

**Comment by rowan-m** [comment]
These all look like automated issues for the widget unrelated to the PHP client library in this repo.
