### ISSUE TITLE
"expanded/collapsed" state not defined for Help button

### ISSUE THREAD

**Issue by BarrierbreakApp** [google/recaptcha#432]
Example URL: https://www.google.com/recaptcha/api2/demo

The state "expanded/collapsed" is not programmatically defined for the "Help" button  present in the reCAPTCHA non-modal dialog (that becomes available on activating "I'm not a robot" checkbox). As a result, screen reader users will not understand the state of the image buttons.

`<button class="rc-button goog-inline-block rc-button-help" title="Help" value="" id="recaptcha-help-button" tabindex="0"></button>`

Suggestion:
Set the aria-expanded attribute to false for the button by default. Ensure that the value of the aria-expanded attribute changes on user interaction via scripting.

![reCaptcha_13](https://user-images.githubusercontent.com/16647640/107736719-c2d83200-6d28-11eb-8b12-29e45e25ba02.png)

**Comment by rowan-m** [comment]
These all look like automated issues for the widget unrelated to the PHP client library in this repo.
