### ISSUE TITLE
"reCAPTCHA" logo image defined through CSS

### ISSUE THREAD

**Issue by BarrierbreakApp** [google/recaptcha#433]
Example URL: https://www.google.com/recaptcha/api2/demo

The logo image of "reCAPTCHA" is defined through CSS. As a result, the image will not be visible in Internet Explorer browser on a Windows operating system for users browsing with their High Contrast mode turned on.

**HTML:**
`<div class="rc-anchor-logo-portrait" aria-hidden="true" role="presentation">`
`<div class="rc-anchor-logo-img rc-anchor-logo-img-portrait"></div><div class="rc-anchor-logo-text">reCAPTCHA</div>`
`</div>`

**CSS:**
`.rc-anchor-logo-img {
 background: url(https://www.gstatic.com/recaptcha/api2/logo_48.png);
background-repeat: no-repeat;
}`

Suggestion:
Apply the following changes:
• Use CSS content property (with ::before and ::after pseudo-elements) to define the images to ensure that the logo image become visible when the Windows High Contrast Mode is turned on.
Alternatively, implement the image with the HTML <img> element and provide empty "alt" attribute (alt="") in it's source code as the textual alternative is provided for the image.
• Remove role="presentation" and "aria-hidden" attribute from the source code of the <div> element containing the image. 

`<div class="rc-anchor-logo-portrait">`
`<div class="rc-anchor-logo-img rc-anchor-logo-img-portrait">`
`<img src="https://www.gstatic.com/recaptcha/api2/logo_48.png" alt="">`
`</div>`
`<div class="rc-anchor-logo-text">reCAPTCHA</div>`
`</div>`

![reCaptcha_14a](https://user-images.githubusercontent.com/16647640/107736953-46921e80-6d29-11eb-9252-ea5fa37fc9af.png)

![reCaptcha_14b](https://user-images.githubusercontent.com/16647640/107736954-47c34b80-6d29-11eb-9e12-a8a24cbd82f0.png)

**Comment by rowan-m** [comment]
These all look like automated issues for the widget unrelated to the PHP client library in this repo.
