### ISSUE TITLE
"selected" icon on selecting images in CAPTCHA control are defined through CSS

### ISSUE THREAD

**Issue by BarrierbreakApp** [google/recaptcha#434]
Example URL: https://www.google.com/recaptcha/api2/demo

The "selected" icon that gets displayed on selecting images in CAPTCHA control are defined through CSS. As a result , the images will not be visible in Internet Explorer browser on a Windows operating system for users browsing with their High Contrast mode turned on.

**HTML:**
`<div class="rc-imageselect-checkbox"></div>`

**CSS:**
`.rc-imageselect-checkbox {
background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAKQWlDQ1BJQ0MgUHJvZmlsZQAASA2dlndUU9kWh8+(...));
display: none;
position: absolute;
}`

Suggestion:
Use CSS content property (with ::before and ::after pseudo-elements) to define the images to ensure that the images becomes visible when the Windows High Contrast Mode is turned on.

![reCaptcha_15a](https://user-images.githubusercontent.com/16647640/107737131-b4d6e100-6d29-11eb-9e41-459e5178bb45.png)

![reCaptcha_15b](https://user-images.githubusercontent.com/16647640/107737133-b7393b00-6d29-11eb-927e-f27502a24859.png)

**Comment by rowan-m** [comment]
These all look like automated issues for the widget unrelated to the PHP client library in this repo.
