### ISSUE TITLE
"reCAPTCHA" text in the captcha not available for screen reader users

### ISSUE THREAD

**Issue by BarrierbreakApp** [google/recaptcha#435]
Example URL: https://www.google.com/recaptcha/api2/demo

The "reCAPTCHA" text in the captcha is not available for screen reader users. As a result, screen reader users may miss out information in the form.

`<div class="rc-anchor-logo-portrait" aria-hidden="true" role="presentation">`
`<div class="rc-anchor-logo-img rc-anchor-logo-img-portrait"></div>`
`<div class="rc-anchor-logo-text">reCAPTCHA</div>`
`</div>`

Suggestion:
Remove the "aria-hidden" attribute and role="presentation" from the <div> element of the source code.

`<div class="rc-anchor-logo-portrait">`
`<div class="rc-anchor-logo-img rc-anchor-logo-img-portrait"></div>`
`<div class="rc-anchor-logo-text">reCAPTCHA</div>`
`</div>`

![reCaptcha_16](https://user-images.githubusercontent.com/16647640/107737351-3fb7db80-6d2a-11eb-9c41-d1cb3e07c1d5.png)

**Comment by rowan-m** [comment]
These all look like automated issues for the widget unrelated to the PHP client library in this repo.
