### ISSUE TITLE
Missing "alt" attribute for reCAPTCHA Challenge's image

### ISSUE THREAD

**Issue by BarrierbreakApp** [google/recaptcha#437]
Example URL: https://www.google.com/recaptcha/api2/demo

Empty "alt" attribute (i.e. alt="") is not provided for the decorative images in the reCAPTCHA Challenge non-modal dialog (that becomes available on checking "I'm not a robot" checkbox). As a result, the HTML validator generated the following error:
• Error: required attribute "ALT" not specified.

`<td role="button" tabindex="0" class="rc-imageselect-tile" aria-label="Image challenge">`
`(...)`
`<img class="rc-image-tile-33" src="https://www.google.com/recaptcha/api2/payload?p=06AGdBq24DqoT37ejX8mTb-zVUFPeHKtIOuPQ14H5hgQBpHav3BoxC55g0Gh3xHlKoflNvE3l0HZOHmgeOP7ROGfKApJW0el39YxeoZoQVm7nZwLit9wcHrfMSvwrkGqjAJGozXIrqr3CvNLKSgei-cbHHuRCx8Zi6YZaHeBBrKLxptX78X5Hvzc5b9OHAXS4uGkoifwuJTwd8HBOBbvaXJGeJSDBG4Ruj6A&amp;k=6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-" style="top:0%; left: 0%">`
`(...)`
`</td>`

Suggestion:
Provide alternate text for all the images using the ‘alt’ attribute. Ensure that the alternate text is descriptive of the image purpose. If the image is decorative, specify an empty alt attribute (alt = "") as given below:

`<td role="button" tabindex="0" class="rc-imageselect-tile" aria-label="Image challenge">`
`(...)`
`<img alt="" class="rc-image-tile-33" src="https://www.google.com/recaptcha/api2/payload?p=06AGdBq27iWHxmuCUA5j7mRGur-TCcfsF-PcwRLqA8qqtrAX-TwEFQ_mGVYXpSHNjVvcWy9Qn54Ui8T8oLeFrHEZ5qLNWzqvQp4YCyBr7SZQCgm0nUlDo7F9VOsIEnCabGJNYdC4kzszZy3VQy4ylkjnDt25DW_aZyIqFDe7wetC_Vd-mSy0_XIp4UqGUqIXcwLgbEf3D4qTN5&amp;k=6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-" style="top:0%; left: 0%">`
`(...)`
`</td>`

![reCaptcha_6](https://user-images.githubusercontent.com/16647640/107751577-97167580-6d43-11eb-9a8c-745b2e6bafc0.png)

**Comment by rowan-m** [comment]
These all look like automated issues for the widget unrelated to the PHP client library in this repo.
