### ISSUE TITLE
is it possible to add whitelist with ip address?

### ISSUE THREAD

**Issue by fspider** [google/recaptcha#438]
I want to make some customers reliable so that recaptcha can not be shown for them.
For this, is that possible to create whitelist with some ip address?
Or how can we make it possible to bypass for some customers?

**Comment by rowan-m** [comment]
You can certainly do whatever security checks you want inside your own site and then only include reCAPTCHA in a page if you do not already have confidence in the user. For example, you might choose to not include reCAPTCHA on pages where users are already signed in.
