### ISSUE TITLE
Not works for PHP v.7.4.15 and PHP v.8.02 but works with PHP v.7.4.13

### ISSUE THREAD

**Issue by vinceAmstoutz** [google/recaptcha#440]
**Issue description**

**Environment**

 * OS name and version: Windows 10 Pro
 * PHP version: **Not works for PHP v.7.4.15 and PHP v.8.02 but works with PHP v.7.4.13**
 * Web server name and version: Symfony server with Symfony 5.2
 * `google/recaptcha` version: v.3
 * Browser name and version: Google Chrome  v.88.0.4324.182

**Reproducing the issue**

  * Test if it's works with  PHP v.7.4.15 and PHP v.8.02 (because for me it's works only with PHP 7.4.13)
  
  ***Recap***
  
  
The recaptcha is considered invalid when I use a version other than PHP 7.4.13 ( when I use PHP v.7.4.15 or PHP v.8.02)

**Comment by fredl2020** [comment]
same here... 7.4.15 : OK 
other : NOK

**Comment by vinceAmstoutz** [comment]
> same here... 7.4.15 : OK 
> other : NOK

For you it's works with 7.4.15 ? Me only with 7.4.13..

**Comment by fredl2020** [comment]
Yes when I switched to 7.4.15 it worked then
But now im so frustrated with recaptcha that Im thinking migrating to honeypot (for CF7 plugin)

**Comment by fredl2020** [comment]
edit you're right even with 7.4.15 it's bugging but with error "Error try again refreshing the page".... im so fedup with recaptcha integration

**Comment by fredl2020** [comment]
I checked on 3 website with recaptcha v3 PHP 7.3.26 seems OK

**Comment by vinceAmstoutz** [comment]
> I checked on 3 website with recaptcha v3 PHP 7.3.26 seems OK

Yo can also use recaptcha v.3 with PHP 7.4.13 😉

**Comment by vinceAmstoutz** [comment]
Still, it's annoying that the newer versions don't work and that it's so complicated.

**Comment by rowan-m** [comment]
Latest release should address this.
