### ISSUE TITLE
reCAPTCHA exists

### ISSUE THREAD

**Issue by Fatih120** [google/recaptcha#447]
**Issue description:**
reCAPTCHA is a service or an option that is available for webmasters - however, it is poorly designed, bad for user experience, and has no regard for one's privacy. It is bad.

**Environment:**
TCP/IP WWW

**Steps to Reproduce:**
Go onto a site which requires the use of reCAPTCHA (many such cases available).

**Suggested Changes:**
It would be objectively best to remove the entire repository, either through an emptying PR or complete annihilation of the project. It would then convince webmasters and large organizations to start using the much-better [hCaptcha](https://www.hcaptcha.com/) so that we no longer have to coexist in a reality where the issues reCAPTCHA sows are prominent.

Thank you for looking into this and I hope a suitable change will be made. It is bad.

**Comment by mikemirten** [comment]
hCaptcha is not better, the same annoying crap as reCaptcha, takes a lot of time to solve.

**Comment by Fatih120** [comment]
> hCaptcha is not better, the same annoying crap as reCaptcha, takes a lot of time to solve.

By your logic both take long to solve, therefore neither would be better in that regard — except that hcaptcha is anything but Google, therefore winning anyway.

I'm skeptical by your claim anyway because h is very friendly especially when testing with proxies, never have I ever needed to do a retry when using that service.
