### ISSUE TITLE
Endpoint needs to be configurable

### ISSUE THREAD

**Issue by playitcool** [google/recaptcha#454]
https://github.com/google/recaptcha/blob/f911286ad361c9fba1b422c07f040852c0c193a3/src/ReCaptcha/ReCaptcha.php#L52

Enterprise customers need to call a different endpoint. This should be a configuration that's injected in as a dependency. Am I missing something obvious?

**Comment by chrisw-ig** [comment]
I have this issue also.

**Comment by playitcool** [comment]
https://github.com/googleapis/google-cloud-php-recaptcha-enterprise - found repo for enterprise sdk :)
