### ISSUE TITLE
Recaptcha v3 keeps returning 0.1 score

### ISSUE THREAD

**Issue by lucacordioli** [google/recaptcha#455]
I've been using recaptcha v3 for a couple of months now and all went smoothly, but recently the recaptcha keeps returning 0.1 or 0.3 and the requests are coming from legit users. The code wasn't modified so I don't know what could it be. I have binded it to a submit event on a button and I keep refreshing it but as I said before it was working just fine.

**Comment by junradio** [comment]
Same here :(
REcaptcha suddenly got to return 0.1 or 0.3 since several days ago.

**Comment by fozzedout** [comment]
It was raised as an issue this morning, we're having to disable recaptcha checks for now.

**Comment by chadsmall** [comment]
Same with us - starting on or around 4/5-4/12/21 our scoring dropped significantly into the .1 and .3 range for a high percentage of users to the point we are reverting scoring and considering move back to V2. Any info available on change. We have not changed our implementation.

**Comment by landyman** [comment]
Same here. Our slide happened from 4/13 - 4/16. We've been using v3 for a long time and have average scores of 0.8 until that time. Now, the average score is 0.2. We only found out because several users reached out and said they couldn't submit our forms.

![image](https://user-images.githubusercontent.com/71241/115766413-cd342f00-a35c-11eb-86f6-ce669ceda9f2.png)

**Comment by chadsmall** [comment]
We don't have average score data captured, but this is our less than .5 score failure threshold that we had configured - now reverted while we figure this out. 
![image](https://user-images.githubusercontent.com/46945/115793362-9e847b80-a391-11eb-97eb-9c5df4c06396.png)

**Comment by LeoBorquez** [comment]
I have the same problem, the score drop from 0.9 to 0.3 - 0.5, we are using cloud run and angular.

**Comment by fozzedout** [comment]
Seems to be magically resolved for me over the weekend. Going from a 0.1 to a 0.9 for no apparent reason.
I'll assume that the Google AI was having a tweak.

**Comment by jonathanbl** [comment]
We are facing the same issue, our reCAPTCHA scores are hovering between 0.1 - 0.3 for no reason. Seems like the issue randomly started early morning EDT on Monday April 26th.

**Comment by chadsmall** [comment]
reCaptcha team, anything on this blip? We are likely going to enhance our V3 to fallback to a V2 check on failure at some score level. Our latest - seems to be on the recovery path. These are averages for one of our web apps
![image](https://user-images.githubusercontent.com/46945/116135537-dc85e600-a696-11eb-9681-fc15283efabe.png)

**Comment by formido** [comment]
Looking at the issues list, there's little to no interaction from Google. It's not clear how we should escalate this.

**Comment by bgp1** [comment]
We have also started to receive complaints from customers that they are unable to log into our product anymore. Login and register pages are protected by Recaptcha. I have been able to consistently replicate as getting a 0.1 score trying to log in. In some cases we just get 0.0 score. We now have nearly 10% of our users receiving 0.1 scores. We have disabled until this can be resolved. Mostly commenting so I can follow this thread.

**Comment by kimsmith5545** [comment]
Just so U all know I was working on trying to claim property. That when mess up sorry Whereat1app Parent Company of Alphabet

**Comment by kimsmith5545** [comment]
Add ur company to my phone 1765 621-8006 I am an independent bot on my phone

**Comment by davit555** [comment]
Going to migrate to Hcaptcha, since the issue still persists and no one from Google is going to fix this !!!

**Comment by VirgileD** [comment]
Hello, since yesterday, although nothing was changed on my site which uses reCaptchaV3, legitimate login requests are almost all rejected. I was forced to set the min acceptable level to 0.0 so it means my service is not protected anymore. Anyone has any hints about the problem?

**Comment by uinnova-wuxin** [comment]
xczxczxczxczx

**Comment by michaelterryio** [comment]
reCAPTCHA never worked again for us, despite no code changes. We switched to a honeypot strategy and it's working at least as well as reCAPTCHA ever did

**Comment by kimsmith5545** [comment]
Everything is protected I promise you that do that it is all protected it's all protected under another platform platform and mine company is over it OK it is under a project and everybody knows it as Google cloud and Microsoft edge Microsoft edge as you know is the best of the best

**Comment by kimsmith5545** [comment]
It is because I just claim my business today yesterday is why and why and my company called where at 1 app is the sole owner of this site site you can go under my oh under my name  Using TWS/Bootstrap..I made to no long steal from me..Mainly because of Google..they ask me if I wanted to use they logo or my own and I chose to use Google logo with there permission and U seen what that's done for me.

**Comment by kimsmith5545** [comment]
All 3 sites that have A-day with developer developer is under my company  And if people want to use my company's Secure sites you can do so it's more secure than Microsoft edge I promise you that

**Comment by kimsmith5545** [comment]
> reCAPTCHA never worked again for us, despite no code changes. We switched to a honeypot strategy and it's working at least as well as reCAPTCHA ever did

Google reCAPTCHA is Whereat1app..I can use any computer out there..but the 48 new Languages won't be revealed un I am gone...

**Comment by yosepstephen** [comment]
<img width="518" alt="Screen Shot 2022-01-04 at 20 40 31" src="https://user-images.githubusercontent.com/97105995/148068130-529ac0f1-a7d1-45c2-ac07-60536fec8beb.png">

Yes as you can see in my dashboard it only return 0.1 / 0.3 / 0.7 or 0.9.. the other value is zero. And it really happened to some REAL USER the value is below 0.1 or 0.3. We have have also using the enterprise version (we paid the service) but the algorithm is still buggy and make some of our users cannot login to our services
