### ISSUE TITLE
Keep up your great work

### ISSUE THREAD

**Issue by Zhwt** [google/recaptcha#456]
**Issue description**
Your captcha is good as hell. I can watch beautiful car pictures, traffic lights, and sidewalks all over the world. And I can solve little puzzles to kill time, which is good. Oh, it also tried to convince me that I'm a robot.

**Environment**

 * Browser name and version: Almost every browser, even on your android.

**Reproducing the issue**

    1. Open some page, whatever, just trigger that wonderful Recaptcha.
    2. Try to solve it for 5 minutes.
    3. And another one 5 minutes.
    4. And another one.
    5. Say to yourself "I can do this!" and try again.

**How to improve**

Keep up your good work, try to make it as worse as Arkose Lab does.

**Comment by kimsmith5545** [comment]
I know what U mean

**Comment by rowan-m** [comment]
Hope you're doing ok out there, human buddy.
