### ISSUE TITLE
Why is Audio not an option?

### ISSUE THREAD

**Issue by RobinOehler** [google/recaptcha#458]
When I choose Audio instead of this (shitty) image click challenge which takes forever to be finished I get flagged as bot and can't even do an Image Captcha without a page reload. What is this Madness? What if I'm a blind user?

**Comment by kimsmith5545** [comment]
It is Whereat1app Assistance for Google Assistance

**Comment by b2ag** [comment]
In my case I use uMatrix, VPN and all the privacy goodness which makes Recaptcha hate me. This leads to me hating Recaptcha too. Result is me uses a sort of hack which solves the captcha for me by solving the audio challenge. This whole Recaptcha (as all the captchas) are a joke and only keep (and stress) out the uninformed.

**Comment by rowan-m** [comment]
Repo is just for PHP client issues. This is about the reCAPTCHA service.
