### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by vladsf** [google/recaptcha#46]
Older (ver 1.0) has proxy support -

define("RECAPTCHA_HTTP_PROXY", "proxy.foo.com");
define("RECAPTCHA_USE_PROXY", true);

do you plan to have this in ver 2.0?

**Comment by yamlfd** [comment]
I have solved this by creating my own RequestMethod for Drupal 6/7/8 modules and it now uses Drupal internal http requests and no longer the limiting library RequestMethod's.

**Comment by vladsf** [comment]
I am not using Drupal. Recaptcha v. 1.0 has proxy support now, what was the point to remove it in v2.0?

**Comment by d2grenier** [comment]
I definitely need proxy support as well - tried implementing something using curl with the new API, but I couldn't get it working.

**Comment by wouldsmina** [comment]
it's an old issue but it could still be used today...

I use recaptcha behind a proxy too. I used curl request method with a small modification in src/ReCaptcha/RequestMethod/CurlPost.php:79 
```php
        $options = array(
            CURLOPT_POST => true,
            CURLOPT_POSTFIELDS => $params->toQueryString(),
            CURLOPT_HTTPHEADER => array(
                'Content-Type: application/x-www-form-urlencoded'
            ),
            CURLINFO_HEADER_OUT => false,
            CURLOPT_HEADER => false,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_SSL_VERIFYPEER => true,
            CURLOPT_HTTPPROXYTUNNEL => true,
            CURLOPT_PROXY => 'proxy.domain.tld:3128'
        );
```

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
