### ISSUE TITLE
Help me integrate

### ISSUE THREAD

**Issue by omidsolo** [google/recaptcha#463]
Hey all,
I'm showing reCaptcha on my web form:

<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<div class="g-recaptcha" data-sitekey="public_key"></div>

I just can't read the value, I've uploaded the PHP files to my server but:

PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home2/admin/public_html/site.com/ReCaptcha/ReCaptcha/RequestMethod/Post.php on line 80
PHP Warning:  file_get_contents(https://www.google.com/recaptcha/api/siteverify): failed to open stream: no suitable wrapper could be found in /home2/admin/public_html/site.com/ReCaptcha/ReCaptcha/RequestMethod/Post.php on line 80

Any advise? I'm not PHP developer so can't debug it :(

**Comment by rowan-m** [comment]
According to the error message, this setting in your PHP configuration is disabled: https://www.php.net/manual/en/filesystem.configuration.php#ini.allow-url-fopen

There are a number of things to investigate here, though apologies as this is quite developer focused advice. If it doesn't make sense, it would be worthwhile contacting whoever provides your PHP environment to see what they can do.

* Check and upgrade your PHP version.
* See if you can enable the setting in your PHP configuration
* Try running with some of the other request methods, e.g.

```php
$recaptcha = new \ReCaptcha\ReCaptcha($secret, new \ReCaptcha\RequestMethod\Curl());
$resp = $recaptcha->setExpectedHostname('recaptcha-demo.appspot.com')
                  ->verify($gRecaptchaResponse, $remoteIp);
```
