### ISSUE TITLE
Cannot use explicit render for enterprise recaptcha

### ISSUE THREAD

**Issue by sneakyfildy** [google/recaptcha#465]
Hi. api.js?render=explicit worked fine for V3 recaptcha, then we started to pay for enterprise version, but it is not possible to .render(siteKey, {}) it into any container, only way of using score-based enterprise recaptcha  is to use auto-render enterprise.js?render=siteKey way.
Is it expected?

**Comment by rowan-m** [comment]
This is just a PHP client library for reCAPTCHA. For Enterprise support, you should check: https://cloud.google.com/recaptcha-enterprise/docs/getting-support
