### ISSUE TITLE
Unable to find a way to test if the integration works correctly

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [google/recaptcha#466]
Unable to find a way to test if the integration works correctly (like using some kind of bot or forcing the value to be 0.1)

Searching on google someone suggested to use Incognito mode, but it doesn't work for me, it returns a high score... are there ways to force the score to be like 0.1? I can't find any reference anywhere

**Comment by a-Zszywacz** [comment]
I have sent something like 400 mails to test this, and every mail from Googlebot have score 0.9. I have try via VPS on Firefox and opera. Every time I have got 0.9.
I remember these days that it was possible.

**Comment by rowan-m** [comment]
Repo is just for PHP client issues. This is about the reCAPTCHA service.
