### ISSUE TITLE
Captcha is not repsonsive

### ISSUE THREAD

**Issue by yamlfd** [google/recaptcha#47]
The captcha is too wide for sidebars. The default login form for Drupal is in a sidebar. Please see the screenshot.

![2015-05-14_102154](https://cloud.githubusercontent.com/assets/4450722/7628411/34c0096c-fa23-11e4-9bc2-8055fad76cf2.png)

**Comment by rowan-m** [comment]
This is a tricky one. The easy part of the question is that this is not related to the PHP client library but is how the widget gets displayed. However, clearly that's not going to help you :P I'll check with the rest of the team but currently the only options to change the appearance are specified here: https://developers.google.com/recaptcha/docs/display#config

**Comment by rowan-m** [comment]
Confirmed with the team that this is the case currently, i.e. the widget is a fixed size. However, we're aware this is an issue and there are some things in the pipeline to help. So, no immediate resolution for you but watch this space.

**Comment by yamlfd** [comment]
Great. Thank for Team feedback. Lookinf forward to these new features.

**Comment by rowan-m** [comment]
@yamlfd you should now be able to try the `data-size="small"` attribute in the tag. Hopefully that will get something a bit of a better fit for you.

**Comment by yamlfd** [comment]
Thanks for unofficial info. Looks better for sure, but still overflows in some screen width. Are you planing to implement a fully responsive/flexible width version in future?

**Comment by Appalab** [comment]
by adding [overflow:hidden] value in css, is it forbidden or against the TOS? but I really need the responsive one.

**Comment by hamedmohammadi** [comment]
@Appalab 
html sample:
<div id="recaptcha" data-sitekey="MAP-CODE" class="g-recaptcha"><div>

css :
.g-recaptcha {
    transform: scale(0.81);
    transform-origin: 0px 0px 0px;
}

you need to transform the scale of whole container div in order to match your position.
2 approach is needed for responsiveness the first one is to use media and the second one is to use js to change the scale dynamically

**Comment by Appalab** [comment]
thanks, it looks nice now.
