### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading '__wrapper_2__')

### ISSUE THREAD

**Issue by systemGene** [google/recaptcha#477]
This happened not long ago. Can't register/login to sites that have reCAPTCHA on them.
I have already cleared my browsing and cookie data
reCAPTCHA works on other browsers
I am using Google Chrome and it is updated.

Please help!

![image](https://user-images.githubusercontent.com/65501694/142724275-4a8efe56-3274-4f1f-a540-963a41e5e980.png)
![image](https://user-images.githubusercontent.com/65501694/142724282-deb3fb9e-7b3e-4cfd-a021-cd524264edd5.png)

**Comment by robbielove** [comment]
@aniespica 
I had this issue (in chrome) and found that the extension 'urban vpn' caused this error and disabling it stopped the error from occurring - alternatively try using incognito window - if it works then try disable your extensions one by one in normal mode
(magento 2 recaptcha module) 
![Uploading Screen Shot 2022-01-21 at 12.02.27 pm.png…]()

**Comment by systemGene** [comment]
> @aniespica I had this issue (in chrome) and found that the extension 'urban vpn' caused this error and disabling it stopped the error from occurring - alternatively try using incognito window - if it works then try disable your extensions one by one in normal mode (magento 2 recaptcha module) ![Screen Shot 2022-01-21 at 12 02 27 pm](https://user-images.githubusercontent.com/13571547/150452411-8a57405b-b143-400a-852a-869a30e59994.png)

THANK YOU SO MUCH! This problem also started to show on incognito mode after enabling Urban VPN on Incognito aswell. Safe to say it's gone now and im relieved. Thanks dude.

**Comment by systemGene** [comment]
> Hello @systemGene, I'm having the same issues with the reCAPTCHA, do you find the solution to make it work with the Chrome browser?

Follow @robbielove solution :')

**Comment by robbielove** [comment]
Glad I could help others because this problem is hard to diagnose as to why you were getting the error 

I had to get this ReCaptcha working for a task I was working on so a solution had to be found. I had experienced the issue before and remember doing something to get around it
