### ISSUE TITLE
SameSiteCookie Issue with re-captcha

### ISSUE THREAD

**Issue by uc-aan** [google/recaptcha#481]
**Issue description**
<html>
<body>

Issue type
--
SameSite cookie
/recaptcha/api.js?render=…(www.google.com)
…api2/anchor?ar=…(www.google.com)
…api2/webworker.js?hl=en&v=-FJgYf1d3…(www.google.com)
…api2/bframe?hl=en&v=-FJgYf1d3…&k=6Lcq_iMaA…(www.google.com)
…api2/reload?k=6Lcq_iMaA…(www.google.com)

</body>
</html>

**Environment**

 * OS name and version: windows 11
 * PHP version: php7
 * Web server name and version: apache
 * `google/recaptcha` version: recaptcha v2
 * Browser name and version: chrome

**Reproducing the issue**

  * URL (optional): 
  * Code (optional): 
  
  ***User steps***
  
  
    1. Visit page...

**Comment by rowan-m** [comment]
Repo is just for PHP client issues. This is about the reCAPTCHA service.
