### ISSUE TITLE
YOUR DOCS SUCK AND I DONT WANT THEM

### ISSUE THREAD

**Issue by jsnyder10** [google/recaptcha#486]
**Issue description**

**Environment**

 * OS name and version:
 * PHP version:
 * Web server name and version:
 * `google/recaptcha` version:
 * Browser name and version:

**Reproducing the issue**

  * URL (optional): 
  * Code (optional): 
  
  ***User steps***
  
  
    1. Visit page...

**Comment by rowan-m** [comment]
Ok. I will not make you read them.
