### ISSUE TITLE
Recaptcha V2 suddlenly is not being shown on Firefox

### ISSUE THREAD

**Issue by ProceduralMan** [google/recaptcha#492]
Since 10 AM this morning Google recaptcha v2 is not showing on firefox browser

Same page shows OK on Chrome/Cromium browser

Example: https://www.coinstake.in/

**Comment by ProceduralMan** [comment]
Google's recaptcha demos whow ok, though

**Comment by rowan-m** [comment]
Repo is just for PHP client issues. This is about the reCAPTCHA service.
