### ISSUE TITLE
Recaptcha v3 / v2 loading multiple times ( and submitting form request multiple times )

### ISSUE THREAD

**Issue by ayanamidev** [google/recaptcha#494]
This is something that doesn't happen with hCaptcha.

Trying to load reCaptcha with the following script tag

```html
<script src="https://www.google.com/recaptcha/api.js?render=explicit"></script>
```

and rendering elements with the following code

```js
const loadCaptcha = (config, captcha) => {
	if (config && captcha && typeof captcha.render === 'function') {
		captchaContainer = captcha.render('captcha_container', {
			'sitekey': config.siteKey
		});
	};
};

grecaptcha.ready(function() {
	loadCaptcha(config, grecaptcha);
});
```

Actually I have found that it could be possibly related with that reCaptcha uses iframe and trying to load multiple frames, as per reported by https://github.com/google/recaptcha/issues/335#issuecomment-548039753.

However, since the issue doesn't being reproduced by hCaptcha and since this could raise the load of the backend server, I think this is a showstopper for reCaptcha.

Any suggestions?

**Comment by ayanamidev** [comment]
Related issues

https://github.com/google/recaptcha/issues/415
https://github.com/google/recaptcha/issues/335

**Comment by seandelaney** [comment]
@ghost

> Found the solution, looks like it was related to the event listener from Browser and isn't related with gCaptcha.
> https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation

Where did you use `stopImmediatePropagation`

**Comment by stepanjakl** [comment]
I am facing the same issue, where recaptcha script loads twice. It seems to load again when I use the `grecaptcha.render()` function.

**Comment by JMLucas96** [comment]
Same issue here, any solution?
