### ISSUE TITLE
Uncaught (in promise) Timeout When user clicks on the check box of the recaptcha.

### ISSUE THREAD

**Issue by samthrusha123** [google/recaptcha#504]
I'm adding like this to my cshtml page(It's a asp .net Core web application)

![image](https://user-images.githubusercontent.com/44087954/195866736-04662cae-8807-40a2-ab66-e70c0f35a0a4.png)

When page loaded for the first time. When user click on the check box, It's showing the loader symbol continuously like below

![image](https://user-images.githubusercontent.com/44087954/195866009-599d8533-557f-43b6-823c-63c9b0859140.png)

When we refresh the page it work fine. But at the first time we're facing this issue.

Is there any solution for it ?

In the console I'm seeing the below error

![image](https://user-images.githubusercontent.com/44087954/195866333-1f60e7b3-d0a4-42cb-93fa-b889e18abd98.png)

**Comment by rowan-m** [comment]
Repo is just for PHP client issues. This is about the reCAPTCHA service.
