### ISSUE TITLE
Photos are culturally insensitive

### ISSUE THREAD

**Issue by northlandiguana** [google/recaptcha#51]
I am frustrated with the decision to move to a recaptcha strategy that asks the user to choose among different photos of food. I am building a website for use in Senegal, where the official language is French. How do I know someone in Senegal is going to recognize the foods shown to French language users? I have a hard enough time myself recognizing the pictures of hamburgers and sushi given the small size and low resolution of the photos. I dread to think how a vegan would react to having to pick out pictures of steak or the effects of separating pictures of food from pictures of beer and liquor on a recovering alcoholic. Please go back to using pictures of numbers, or at least provide a choice of the type of captcha test to give the user.

**Comment by Erutan409** [comment]
Personally, I wouldn't refer to as insensitive; which is just politically charged IMO.  I look at it from a practicality aspect.  So, I do AGREE with you that it was weird that they went the direction of choosing pictures.

**Comment by rowan-m** [comment]
This particular repo is only for the PHP client, so the code here only governs submitting and verifying the form response. The actual display of the images and so on comes from the reCAPTCHA service itself. However, the team does keep a very close eye on the effectiveness / appropriateness of the various methods used and is continuing to refine and improve them.
