### ISSUE TITLE
PHP 8.2 deprecations

### ISSUE THREAD

**Issue by raspgot** [google/recaptcha#512]
**Issue description**
PHP 8.2 deprecations are being triggered.
`Creation of dynamic property ReCaptcha\ReCaptcha::$hostname is deprecated in \recaptcha\ReCaptcha\ReCaptcha.php on line 216`

**Environment**
 * OS name and version:
 * PHP version: 8.2.1
 * `google/recaptcha` version: php_1.2.4

**Solution**
https://www.php.net/releases/8.2/en.php#deprecate_dynamic_properties
Add `AllowDynamicProperties` attribute in `\recaptcha\ReCaptcha\ReCaptcha.php : 40`
```php
#[\AllowDynamicProperties]
class ReCaptcha
{
    ...
}
```

**Comment by tommygooden** [comment]
There seem to be a PR for it [PR-510](https://github.com/google/recaptcha/pull/510) but it is not yet approved. I am here waiting on the approval myself.

**Comment by pthreat** [comment]
@tommygooden Same, I'm kind of feeling this project is dead

**Comment by rowan-m** [comment]
Merged and released.
