### ISSUE TITLE
Verify window hides behind the bottom

### ISSUE THREAD

**Issue by silencerspirit** [google/recaptcha#515]
Hi!

If you go to the page and immediately open the form, then when the captcha is called, the window is displayed incorrectly and hides behind the bottom of the browser and user **can't click verify button**.

<img width="220" alt="image" src="https://user-images.githubusercontent.com/22055696/217197899-778b37be-6b16-4f93-be9c-0817ec3e7924.png">

If you close the form, scroll up and down and open the form when the lower part of the browser is hidden, the captcha is displayed normally

<img width="220" alt="image" src="https://user-images.githubusercontent.com/22055696/217198382-669b1e01-d694-4a67-b6f9-f445a86e5e85.png">

**Comment by rowan-m** [comment]
Repo is just for PHP client issues. This is about the reCAPTCHA service.
