### ISSUE TITLE
reCaptcha missing problem

### ISSUE THREAD

**Issue by becart** [google/recaptcha#56]
Hi, 
I use JaObelisk template on my site. I use ReCaptcaha and all properly configured. When you try to register using modules Ja Login (top right corner) all works.
But if you mess up the registration, module redirects you to the registration page and there is a problem. ReCaptcha does not appear and it is impossible to complete the registration.
I try to open registration page http://planinarenje.ba/registracija, but ReCaptcha missing. On this page ReCaptcha missing in ja Login module too. On all other pages Ja Login works properly.
I try with default Protostar template but is same
![screen shot 2015-06-22 at 12 13 32](https://cloud.githubusercontent.com/assets/5500427/8312032/ac464ad8-19da-11e5-95ae-65607e9e723a.jpg)

How can I solve it?
Thanks, 
Midhat

**Comment by rowan-m** [comment]
Hey @becart I took a quick look and saw that you're calling `grecaptcha.render("jform_captcha"…` where  `jform_captcha` should be the id of the element where you want to render the form. I do not see an element with the id `jform_captcha` in the page.
