### ISSUE TITLE
symfony2 error

### ISSUE THREAD

**Issue by javier-reguillo** [google/recaptcha#57]
when I execute
```
$resp = $recaptcha->verify($_POST['g-recaptcha-response'], $_SERVER['REMOTE_ADDR']);
```
the app crash... 

mode 1:
```
$recaptcha = new \ReCaptcha\ReCaptcha($recaptcha_privatekey);
```
Warning: file_get_contents():
500 Internal Server Error - ContextErrorException
in vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php at line 68 
...vendor\google\recaptcha\src\ReCaptcha\RequestMethod\Post.php', '68', array('params' => object(RequestParameters), 'peer_key' => 'CN_name', 'options' => array('http' => array('header' => 'Content-type: application/x-www-form-urlencoded ', 'method' => 'POST', 'content' => 'secret=************************&response=03AHJ_Vuu9kYDTuTfBDI26JBqZ0oUZpaX2P3DKycIbaheF4p9Xy1ZjayGfP6lzUqq95LTvi1mZyC0ds8P48umLA8yS7l_fyRHHKRlJo7IWjlCUN315QcIuAxxszqPBkOq3ZzAHEmmr89OFR39c5JIYQC_LPWiD-V9jrKyBH_6hB08oy5gmwlUoW-BqwXIHPdtc1uwo87dKZ-R4e4Om2qxzcP0Fa6E3sIBmAEs5A1AP7gYUoMkYI-Q3uUZfiPhqLKgXW3pgSlSYsjryWed-wAloVn6bTGP_ECA3kqjLDijl6SsULZp2RHBQ94cbS7QmjuHG6uO1QHJkYRHs7D5cAN4koqw39YHrtSwkDynFSMtPKOX8--3gOFuJCqYskjAvHjInU0JbgTlR6jJT_69cFnqjMcWIEeHOHK6h3HRW5T0c4-Css_7_AanpX-QOoMvyAAQY9wgFXij2PBJR&remoteip=127.0.0.1&version=php_1.1.0', 'verify_peer' => true, 'CN_name' => 'www.google.com')), 'context' => resource))

and mode 2:
```
$recaptcha = new \ReCaptcha\ReCaptcha($recaptcha_privatekey, new \ReCaptcha\RequestMethod\SocketPost());
```
Warning: fsockopen():
500 Internal Server Error - ContextErrorException
in vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Socket.php at line 50
...vendor\google\recaptcha\src\ReCaptcha\RequestMethod\Socket.php', '50', array('hostname' => 'ssl://www.google.com', 'port' => '443', 'errno' => '0', 'errstr' => '', 'timeout' => '30'))

suggestion?

**Comment by javier-reguillo** [comment]
google/recaptcha 1.1.1 installed with composer

**Comment by rowan-m** [comment]
For future reference, please don't include your secret when posting error logs. I've removed that from your comment, but I'd strongly recommend recreating your key at https://www.google.com/recaptcha/admin

I can't diagnose the issue from the error output you've included so I can only suggest a few sanity checks for you:
- can you run the unit tests in your environment?
- can you run the example in your environment?
- do other outgoing network calls work from your environment?
- try clearing the Symfony cache: `php app/console cache:clear`
