### ISSUE TITLE
No response in some environments

### ISSUE THREAD

**Issue by MPolleke** [google/recaptcha#59]
Thank you for making reCAPTCHA available.
In my WordPress plugin I have it integrated, first the prior version, and just this week the current version. Some users are reporting problems however. Upon debugging, everything seem okay. The $params that are being sent to the service are all in order. However, there is no response from the reCAPTCHA service. The JSON string is empty when running print_r on it.
I don't really know how to debug this further, since on my setups everything works. The latest bugreport is here:
https://wordpress.org/support/topic/recaptcha-key-error?replies=24
In my testsetup I used the user's key with their domainname, and it just works. It reports success. Is there anyway that you can help?

**Comment by WouterDS** [comment]
I’ve seen from our logging system that we sometimes don’t get a response back when verifying the response with PHP.
Sometimes (rare, but it happens) it times out.

**Comment by chainlubesystems** [comment]
Hi,
I am also using Gwolle Guestbook on my homepage and always get the following error message if I use recaptcha:

Array
ReCaptcha\Response Object ( [success:ReCaptcha\Response:private] => [errorCodes:ReCaptcha\Response:private] => Array ( [0] => invalid-json ) )
Beim Speichern des Gästebuch-Eintrags sind Fehler aufgetreten.
Der reCAPTCHA-Schlüssel wurde nicht korrekt eingetragen, obwohl er erforderlich ist.

I have not the technical knowledge to debug this but maybe I can help you answer important questions to help debugging the error. So here is some data:

My Wordpress-Theme: Alyeska (http://themeforest.net/item/alyeska-responsive-wordpress-theme/164366)
Konsole in Firefox says: getAttributeNode() should not be used anymore. Use getAttribute() instead.
The URL to my Guestbook is http://www.cls-evo.de/kontakt/gaestebuch-2/

If you have further questions about my setup, just write here and I will do my best to answer them!

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
