### ISSUE TITLE
Secure token support?

### ISSUE THREAD

**Issue by rlweb** [google/recaptcha#60]
This is missing secure token support? I've so far been unable to generate a secure token in PHP which works with the recaptcha.

Anyone know how to generate AES/ECB/pdkdf2 token?!

**Comment by Dayjo** [comment]
I'm also wondering about this. Need to be able to roll this out to multiple sites without generating keys for each domain, but there seems to be no docs and extremely unclear as to how to go about doing this.

For instance;
![](http://c.dayjo.me/image/13312f2h3D33/Image%202015-08-04%20at%2012.22.22%20pm.png)

"Encrypt it" ... erm.. how?

**Comment by Dayjo** [comment]
@rlweb for your reference - I am using this; https://github.com/slushie/recaptcha-secure-token

It appears there's not really any documentation as to how the encryption should work, but I got it working with this class.

**Comment by rowan-m** [comment]
I haven't added support for this yet, but will get on this.

**Comment by Dayjo** [comment]
@rowan-m @slushie's implementation appears to work fine but he does warn about some security issues. Obviously not needing to rely on two libraries for this would be good :+1:

**Comment by rowan-m** [comment]
Closing this as the Java implementation is pretty old now and the secure token stuff is not documented any where other than that code example.
