### ISSUE TITLE
Does not work with Google Charts

### ISSUE THREAD

**Issue by mistercz** [google/recaptcha#62]
I prepared sample page... http://plnkr.co/edit/2oioaxLaFJnJ78oSxChh
1) reCaptcha does not work on this page. You can find error "TypeError: Cannot read property 'register' of undefined"  in console.
2) If you comment this line " google.load("visualization", "1", {packages: ["corechart"],"callback":drawVisualization});" all works as expected.

Please advise what to do.
Thank you

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
