### ISSUE TITLE
I think there is some issue here

### ISSUE THREAD

**Issue by Melhosh** [google/recaptcha#67]
when I tried to write the following on my script manually
$resp = $recaptcha->verify($gRecaptchaResponse, $remoteIp);

The response of captcha never be true
then I tried to replace it by:
$resp = $recaptcha->verify($_POST['g-recaptcha-response'], $remoteIp);

Is it true now, or there are there something errors?

**Comment by rowan-m** [comment]
`$gRecaptchaResponse` should be set to the `g-recaptcha-response` field you receive from the POST data.

**Comment by Melhosh** [comment]
So, that is mean the following code is correct:
$resp = $recaptcha->verify($_POST['g-recaptcha-response'], $remoteIp);

**Comment by rowan-m** [comment]
That will work. You should also populate the `$remoteIp` variable with an appropriate value, e.g. `$_SERVER['REMOTE_ADDR']`.
