### ISSUE TITLE
Don't localize the widget automatically 

### ISSUE THREAD

**Issue by tharshanlk** [google/recaptcha#68]
This is very inconvenient, for example I'm from Sri Lanka and here we use 3 languages. (English, Sinhala, Tamil)

By default the ReCaptcha renders in Sinhala and majority of Tamil people don't understand Sinhala and there is no easy option to switch the language either.

I know the developer has option to override the language but this is really getting frustrated. The captcha itself is a difficult thing to solve sometimes and this makes things even more complicated for international users.

Another example is: Android startup screen, language is automatically chosen.

Why don't we let the developer decide the localization rather than setting it automatically because it's a functional part of the UI/UX?

Thanks

Seems like other users also have the same problem: https://groups.google.com/forum/#!topic/recaptcha/KQC8oN0-2sA
https://groups.google.com/forum/#!topic/recaptcha/Z9-DNgt447Y
https://groups.google.com/forum/#!topic/recaptcha/9ec6tVmk59w

![image](https://cloud.githubusercontent.com/assets/2081895/9867937/94e18432-5b90-11e5-9533-cc27b1e4faf0.jpg)

**Comment by sasureshkumar** [comment]
Thank you @vdharshan . It is really very inconvenient and can not move further for sign up process where reCaptcha is used.

**Comment by Arkonsel** [comment]
I signed up for an account JUST so I could agree with this. I moved to Sri Lanka recently, I do not read Sinhala (though I'm learning) and google translate doesn't work on reCaptcha so when I get asked to identify something, I have no idea what it wants me to do. Please please PLEASE fix this, it's so frustrating to have to keep dealing with.
![sigh](https://cloud.githubusercontent.com/assets/14921373/10216051/eecd9f7a-6843-11e5-87b3-6690fb463406.png)

**Comment by wouterds** [comment]
I don't understand the issue guys, you can provide the language you want the widget to have if you don't want it to autodetect.

`<script src="//www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit&hl=LANGUAGE_HERE" async defer></script>`

**Comment by Arkonsel** [comment]
I don't own or have any power to change the website in question since I'm complaining about reCaptchas on other websites, like Tumblr. 

I'm saying that as a USER, it's really annoying to go to various websites and have Captchas pop up in the local language because of auto-detection of the country. Making it match the browser language settings would be a lot more convenient.

**Comment by wouterds** [comment]
Oh, if it's not using the browser language but detecting it based on your geographical location of your isp that would fucked up indeed.

**Comment by Arkonsel** [comment]
Yep. Now you see my problem.

Also like the original poster said, there are three main languages in Sri Lanka. While everyone speaks English and can handle English instructions, the Tamils are unlikely to speak Sinhala so they'd be just as confused as I am.

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
