### ISSUE TITLE
How to add multiple recaptchas

### ISSUE THREAD

**Issue by dev4press** [google/recaptcha#70]
If I have 2 or 3 forms on the page, and I want to add recaptcha in every one of them, this will not work with this library, because only first added DIV with g-recaptcha class will be converted and the others will not. Can you please provide example on how to add multiple captchas to a page?

**Comment by wouterds** [comment]
Just initialize them on the fly with JS `window.grecaptcha.render(id, { sitekey: config.apiKeys.googleReCaptcha })`

**Comment by arcanedev-maroc** [comment]
You can use this package : https://github.com/ARCANEDEV/noCAPTCHA

Example on how to add multiple captchas to a single page: 

https://github.com/ARCANEDEV/noCAPTCHA/blob/master/examples/multiple-captchas.php

**Comment by dev4press** [comment]
Thanks!
