### ISSUE TITLE
data-callback not firing

### ISSUE THREAD

**Issue by apriebe** [google/recaptcha#74]
# data-callback not getting called
The following is a very simple implementation of Google ReCaptcha using ReactJS. The attrs data-type and data-theme work, however the data-callback and data-expired-callback never get called. There are no errors thrown either. 
Google Chrome Version 45.0.2454.101 (64-bit)

<img width="331" alt="screen shot 2015-10-14 at 9 06 43 am" src="https://cloud.githubusercontent.com/assets/7946363/10486101/03114dce-7253-11e5-94b9-d7e341019818.png">

## Footer HTML
    <script src='https://www.google.com/recaptcha/api.js'></script>

## Javascript/JSX

    (function() {
    "use strict";

    /**
     * Represents a Google ReCaptcha
     */
    class Captcha extends COS.Input.Base
    {

        getCaptchaResponse(response) {
            alert('working: ', response);
        }

        renderEdit()
        {
            return (
                <div
                    ref="captcha"
                    id="captcha"
                    name="captcha"
                    data-type="audio"
                    data-theme="dark"
                    data-sitekey="6Lc9fg4TAAAAAGYyFskow-g2b4IQ_rLvsLkHicuS"
                    data-callback={this.getCaptchaResponse}
                    className="g-recaptcha"></div>
            );
        }

    }

        Captcha.makeDefaultProps({
            // Extend Default Props here
        });

        COS.Input.Captcha = Captcha;
    })();

## How it renders in the HTML

    <div id="captcha" name="captcha" data-type="audio" data-theme="dark" data-sitekey="6Lc9fg4TAAAAAGYyFskow-g2b4IQ_rLvsLkHicuS" data-callback="function (response) {
            alert('working: ', response);
        }" class="g-recaptcha" data-reactid=".2.$29.8.$39.1.$60.1.1.$83.1.0.1.1:$311.1"><div>

**Comment by rowan-m** [comment]
The `data-callback` and `data-expired-callback` attributes expect a string the defines the name of the function in the global namespace that should be fired. You cannot define the function within the attribute.

**Comment by apriebe** [comment]
Thanks Rowan. So Google ReCaptcha isn't really designed to work with React then? 

I added a global function:

    function recaptchaWorks(response) {
        alert("WORKS");
    }

And changed the data-callback

    data-callback="recaptchaWorks"

This works now, however it doesn't give me access to the response within the class where it is actually needed. Do you know of a workaround for this?

**Comment by rowan-m** [comment]
https://developers.google.com/recaptcha/docs/verify
The callback function should receive a string parameter with the response as specified in the linked docs. Is that coming through?

**Comment by apriebe** [comment]
Yes.

**Comment by rowan-m** [comment]
Sounds good to me!

**Comment by dev-riseapps** [comment]
> This works now, however it doesn't give me access to the response within the class where it is actually needed. Do you know of a workaround for this?

You can do something like this

```
class A extends React.Component{
	constructor(props) {
		super(props);
		window.handleRecaptcha = this.handleRecaptcha;
	}

	handleRecaptcha(){
		alert('You can handle captcha inside the class here');
	}

	render(){
		return <div className="g-recaptcha" 
			data-callback="handleRecaptcha" 
			data-sitekey="..."/>
	}
}
```

**Comment by AfonsoCFonseca** [comment]
@dev-riseapps thank you, that solved my issue ;)

**Comment by fcastrocs** [comment]
For others using functional components, this is how I got it to work.

`import React from "react";
import jwt from "jsonwebtoken";

declare global {
  interface Window {
    responseGoogle: any;
  }
}

window.responseGoogle = (res: any) => {
  const decoded = jwt.decode(res.credential);
  console.log(decoded);
};

function Header() {
  return (
    <>
      <div
        id="g_id_onload"
        data-client_id=""
        data-context="signin"
        data-ux_mode="popup"
        data-callback="responseGoogle"
        data-auto_prompt="false"
      ></div>

      <div
        className="g_id_signin"
        data-type="standard"
        data-shape="rectangular"
        data-theme="outline"
        data-text="signin_with"
        data-size="large"
        data-logo_alignment="left"
      ></div>
    </>
  );
}
`
