### ISSUE TITLE
Error code messages?

### ISSUE THREAD

**Issue by alexhass** [google/recaptcha#78]
I'm wondering why the responds do not have a "error-message" that contains "The response parameter is invalid or malformed." just as one example.

e.g. 

```
{
"success": false,
"error-codes": ["invalid-response"],
"error-message": "The response parameter is invalid or malformed." 
}
```

I have a case open at https://www.drupal.org/node/2599804 we need to catch and handle where the HTTP connection may fail, too. I think error handling could be optimized in the library as it seems very inflexible or at least I'm not sure where to place the error handling.

If the submit post the content in Drupal7Post class it may return these predefined error codes, but drupal_http_request can also fail like fsocket does and may return a http status code like `stdClass Object ( [code] => -101 [error] => Network is unreachable )`. In such a case the libary tells the user `invalid-json` = "The json response is invalid or malformed" what is highly misleading to the root cause. The issue is the http request and not the responds from google.

I could now add a lot of error handling inside RequestMethod->submit(), but it looks strange that error handling is done in submit() and fromJson(). 

Where would you add it?

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.

**Comment by alexhass** [comment]
Can you reopen this case, please? It is still valid.

**Comment by rowan-m** [comment]
Could you raise a new issue for this against the most recent version of the library. Additionally, you may want to try some of the other request methods, e.g.
```php
$recaptcha = new \ReCaptcha\ReCaptcha($secret, new \ReCaptcha\RequestMethod\SocketPost());
```

**Comment by alexhass** [comment]
That is waste of time. Please reopen the case. I cannot use SocketPost as we use Drupal8Post().

**Comment by rowan-m** [comment]
If the connection failed, would it work for you if the service returned this?
```json
{
  "success": false,
  "error-codes": [
    "bad-connection"
  ]
}
```

**Comment by alexhass** [comment]
That should work fine. Can you create a new release soon?

**Comment by rowan-m** [comment]
`v1.2.1` released.
