### ISSUE TITLE
ReCaptcha::__construct, Adding of Doc comment that doesn't contain necessary @throws tags.

### ISSUE THREAD

**Issue by heykarthikwithu** [google/recaptcha#79]
ReCaptcha::__construct($secret, RequestMethod $requestMethod = null), Adding of Doc comment that doesn't contain necessary @throws tags.

**Comment by heykarthikwithu** [comment]
https://www.drupal.org/files/issues/2604730.patch

**Comment by rowan-m** [comment]
Thanks for raising!
