### ISSUE TITLE
Argument 2 passed to ReCaptcha\ReCaptcha::__construct() must be an instance of ReCaptcha\RequestMethod, instance of ReCaptcha\RequestMethod\Curl given

### ISSUE THREAD

**Issue by unrivaledcreations** [google/recaptcha#80]
I encountered this interesting error with recaptcha while developing for Silex (Symfony2).  The error reads:

```
Catchable fatal error: Argument 2 passed to ReCaptcha\ReCaptcha::__construct() must be an instance of ReCaptcha\RequestMethod, instance of ReCaptcha\RequestMethod\Curl given
```

The error is caused by:
`$recaptcha = new \ReCaptcha\ReCaptcha( CAPTCHA_SECRET_KEY, new \ReCaptcha\RequestMethod\Curl() );`

The fix is to modify the class definition, `google/recaptcha/src/ReCaptcha/RequestMethod/Curl.php`:
_Original:_

```
class Curl
{...}
```

_Fixed:_

```
class Curl extends Post
{...}
```

It appears that it must either "implements RequestMethod" or "extend" something that does.

**Comment by rowan-m** [comment]
The `Curl` class is a wrapper for the `curl_*` functions, the actual request method is the `CurlPost` class. However, this is not particularly readable as shown by the confusion it's caused. I'll probably move these down into a lower namespace to make it clear it's a supporting class.

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
