### ISSUE TITLE
Initial load sometimes doesnt load the callback

### ISSUE THREAD

**Issue by robbiegod** [google/recaptcha#83]
I've noticed that after I clear my cache and visit my website sometimes the Google reCaptcha doesnt load.  I receive an error saying that my reCaptcha container div doesn't exist.  Here is how i have it setup on my website.

I have an external javascript file with the following in it:

```
var CaptchaCallback = function(){

"use strict";

// var formIDs = [];
$("form").each(function() {
    var formID = $(this).data("formid"); 
    grecaptcha.render('sem-captcha-'+formID, {'sitekey' : '[site_key]'});
});

};
```

In my footer file, I am calling the scripts like this:

```
<script src='https://www.google.com/recaptcha/api.js?onload=CaptchaCallback&render=explicit' async defer></script>
<script async type="text/javascript" src="<?php echo $this->getThemePath(); ?>/js/site.reCaptcha.js"></script>
```

I'm loading these scripts inside of concrete5 page.  Should i put the recaptcha/api.js call in my header file?  Is there i can check to make sure that the api is loaded and my container div is available.  I would also like to fire my callback only after the api and the site.reCaptcha.js file have completely loaded.

I think i want the page to load first, then the api and then my callback.  That should guarantee everything is where it needs to be before the callback is fired.

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
