### ISSUE TITLE
Multiple reCaptcha not working.

### ISSUE THREAD

**Issue by jeffersondevasconcelos** [google/recaptcha#94]
For some reasons I need to use two recaptchas instances in the same page. With the argument 'explicit' in URL that calls the API, I can render the two recaptchas, but, when I try to submit the second form is sent the first. I has checked all html markup and tryed to create triggers using submit values in POST to send the right form after submit, but the results are not good.

Any help will be appreciated! Thank you!

**Comment by jeffersondevasconcelos** [comment]
Hi Jason,

first, thank you for your attention! The code is on localhost. Follow the
image attached to show the application. Is a product page where the client
can send a contact to get more information about the property. In footer,
overall the site, exists another form where any client can send a
information request to the property agency.

To create this page I did an instance of reCaptcha using 'new ReCaptcha' in
product page and another in footer. I'm sending the three files, just for
you see the code. This files are included in product page and footer. To
render the two reCaptcha, was necessary to use the argument 'explicit' in
url that calls the APÌ from Google.

Thank you, again!

2016-03-01 14:26 GMT-03:00 jasonfedor <notifications@github.com>:

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
