### ISSUE TITLE
Injected Chars on reCaptcha's Responses

### ISSUE THREAD

**Issue by romuloctba** [google/recaptcha#98]
'Sup guys, how are you?

I've tried some diffrent sites, in different browsers and different OS's, computers and  Access Points:

The reCaptcha's response returns the following characters BEFORE the correct response, thus invalidating the JSON: `)]}'`

Attached screenshot 
![screenshot from 2016-03-18 10-52-17](https://cloud.githubusercontent.com/assets/2955932/13879813/27095b8e-ecf8-11e5-8dda-bd78faf43c24.png)

BTW: It was fine untill some days ago, and the webpage shown in the screenshot is not mine: I just found it on google for testing, after finding the problem in the sites I work on

**Comment by romuloctba** [comment]
BTW: It was fine untill some days ago

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
